// cards.js - Catálogo Maestro
// Este archivo reúne todos los arrays definidos en los archivos de la carpeta database/ y asigna la serie
// Bump DB_VERSION whenever card data changes to invalidate draft localStorage cache
const DB_VERSION = '1784208702590';

const tsubasaAll = [
    ...tsubasaCards,
    ...genzoCards,
    ...kojiroCards,
    ...holandaCards,
    ...wakashimazuCards,
    ...urabeCards,
    ...sorimachiCards,
    ...sanoCards,
    ...sawadaCards,
    ...takasugiCards,
    ...izawaCards,
    ...kishidaCards,
    ...kisugiCards,
    ...takiCards,
    ...levinCards,
    ...gentileCards,
    ...ginoCards,
    ...krausCards,
    ...dinamarcaCards,
    ...pierreCards,
    ...napoleonCards,
    ...amorosCards,
    ...jeanCards,
    ...mexicoCards,
    ...tailandiaCards,
    ...sudafricaCards,
    ...rusiaCards,
    ...uruguayCards,
    ...chinaCards,
    ...croaciaCards,
    ...eeuuCards,
    ...portoCards,
    ...makeloloCards,
    ...thoramCards,
    ...italiaCards,
    ...espanaCards,
    ...holandaCardsNuevos,
    ...duschampsCards,
    ...mbappaCards,
    ...zedaneCards,
    ...sueciaCards,
    ...argentinaCards,
    ...otrosFranciaCards,
    ...egiptoCards,
    ...markEvansCards,
    ...judeSharpCards,
    ...nathanCards,
    ...tecmoCards,
    ...raimonCards,
    ...occultCards,
    ...gabiCards,
    ...wildCards,
    ...brainCards,
    ...otakuCards,
    ...shurikenCards,
    ...farmCards,
    ...kirkwoodCards,
    ...zeusCards,
    ...reoCards,
    ...riccardoCards,
    ...solCards,
    ...zanarkCards,
    ...goldieLemonCards,
    ...sorCards,
    ...ryomaCards,
    ...feiRuneCards,
    ...victorCards,
    ...jpCards,
    ...arionCards,
    ...simeonCards,
    ...vulpeenCards,
    ...drakulCards,
    ...destraCards,
    ...sanctusCards,
    ...lancerCards,
    ...quentinCards,
    ...romeroCards,
    ...jawatoCards,
    ...finnCards,
    ...angdemCards,
    ...angdem2Cards,
    ...ogreCards,
    ...terryCards,
    ...calapirataCards,
    ...falcoCards,
    ...earthElevenCards,
    ...alpinoCards,
    ...buddyFuryCards,
    ...briarCards,
    ...southCirrusCards,
    ...luzSomCards,
    ...crossCards,
    ...fuegoHieloCards,
    ...inazumaKidsCards,
    ...recoveredCards,
    ...riberaKasaminoCards,
    ...sallysCards,
    ...scoutsOneCards,
    ...scoutsPartTwoCards,
    ...scoutsPartThreeCards,
    ...scoutsPartFourCards,
    ...kingPrimeCards,
    ...dvalinCards,
    ...geminisCards,
    ...romeroEspanaCards,
    ...celticCards,
    ...uzbekistanCards
];
tsubasaAll.forEach(c => c._series = 'tsubasa');

const bluelockAll = [
    ...isagiCards,
    ...raichiCards,
    ...yukimiyaCards,
    ...karasuCards,
    ...nagiCards,
    ...kiyoraCards,
    ...hiiragiCards,
    ...himizuCards,
    ...hioriCards,
    ...sub20Cards,
    ...chigiriCards,
    ...hugoCards,
    ...lokiCards,
    ...tresagaCards,
    ...baptisteCards,
    ...hidalgoCards,
    ...chevalierCards,
    ...noaCards,
    ...franciaBLCards,
    ...franciaHieloCards,
    ...kunigamiCards,
    ...saeCards,
    ...nikoCards,
    ...kuronaCards,
    ...shidouCards,
    ...barouCards,
    ...gagamaruCards,
    ...lavinhoCards,
    ...cucurellaCards,
    ...espanaLegendsCards,
    ...legendsUpdateCards,
    ...luisSuarezCards,
    ...updatesV2Cards
];
bluelockAll.forEach(c => c._series = 'bluelock');

const coachesAll = typeof coachesDB !== 'undefined' ? [...coachesDB] : [];
coachesAll.forEach(c => c._series = 'coach');

const cardsDB = [...tsubasaAll, ...bluelockAll, ...coachesAll];
