const alpinoCards = [
    {
        id: "ArtTundraOro",
        name: "ART TUNDRA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RM",
        secondaryPositions: ["LM", "RW", "CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/ArtTundraOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ArtTundra",
        name: "ART TUNDRA",
        version: "Hielo",
        rarity: "Especial",
        rating: 85,
        position: "RM",
        secondaryPositions: ["LM", "RW", "CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/ArtTundra.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "BlainChills",
        name: "BLAIN CHILLS",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "LM",
        secondaryPositions: ["RM", "LW", "CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/BlainChills.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BlakeWintry",
        name: "BLAKE WINTRY",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CM",
        secondaryPositions: ["CDM", "CAM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/BlakeWintry.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BobSledOro",
        name: "BOB SLED",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CAM",
        secondaryPositions: ["CM", "CF", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/BobSledOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BobSled",
        name: "BOB SLED",
        version: "Hielo",
        rarity: "Especial",
        rating: 87,
        position: "CAM",
        secondaryPositions: ["CM", "CF", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/BobSled.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "BorelAurora",
        name: "BOREL AURORA",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CAM",
        secondaryPositions: ["CM", "CF", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/BorelAurora.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "FritzBrisk",
        name: "FRITZ BRISK",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/FritzBrisk.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "GrisleyBearOro",
        name: "GRISLEY BEAR",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/GrisleyBearOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "GrisleyBear",
        name: "GRISLEY BEAR",
        version: "Hielo",
        rarity: "Especial",
        rating: 86,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/GrisleyBear.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "GuylAcier",
        name: "GUYL ACIER",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/Guyl'Acier.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "HimeshHimalaya",
        name: "HIMESH HIMALAYA",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/HimeshHimalaya.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "IggieLooOro",
        name: "IGGIE LOO",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/IggieLooOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "IggieLoo",
        name: "IGGIE LOO",
        version: "Hielo",
        rarity: "Especial",
        rating: 88,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/IggieLoo.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "MattherHorne",
        name: "MATTHER HORNE",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "LB",
        secondaryPositions: ["LWB", "CB", "RB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/MattherHorne.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "NjordSnioOro",
        name: "NJORD SNIO",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/NjordSnioOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "NjordSnio",
        name: "NJORD SNIO",
        version: "Hielo",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/NjordSnio.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "NjordSnioRes",
        name: "NJORD SNIO",
        version: "Rulebreaker",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/NjordSnioRes.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "NjordSnioPrime",
        name: "NJORD SNIO",
        version: "Mordiscos",
        rarity: "Especial",
        rating: 93,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/Alpino/NjordSnioPrime.png",
        background: "assets/Cartas/Mordiscos.png"
    },
    {
        id: "SaschaKotch",
        name: "SASCHA KOTCH",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/SaschaKotch.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "SunoAisu",
        name: "SUNO AISU",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/SunoAisu.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "WolfeWhyteOro",
        name: "WOLFE WHYTE",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/WolfeWhyteOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "WolfeWhyte",
        name: "WOLFE WHYTE",
        version: "Hielo",
        rarity: "Especial",
        rating: 85,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/WolfeWhyte.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "YuleHoarfrostOro",
        name: "YULE HOARFROST",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        secondaryPositions: ["CAM", "CDM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/YuleHoarfrostOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "YuleHoarfrost",
        name: "YULE HOARFROST",
        version: "Hielo",
        rarity: "Especial",
        rating: 86,
        position: "CM",
        secondaryPositions: ["CAM", "CDM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Alpino.png",
        image: "assets/characters/Alpino/YuleHoarfrost.png",
        background: "assets/Cartas/Hielo.png"
    }
];
