const angdem2Cards = [
    {
        id: "AstarothOro",
        name: "ASTAROTH",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/AngDem/AstarothOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Astaroth",
        name: "ASTAROTH",
        version: "Roja",
        rarity: "Especial",
        rating: 88,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/AngDem/Astaroth.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "ZanosOro",
        name: "ZANOS",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CAM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/AngDem/ZanosOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Zanos",
        name: "ZANOS",
        version: "Trophy",
        rarity: "Especial",
        rating: 87,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CAM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/AngDem/Zanos.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "Agor",
        name: "AGOR",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/AngDem/Agor.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Arakune",
        name: "ARAKUNE",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RM",
        secondaryPositions: ["LM", "RW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Racing.png",
        image: "assets/characters/AngDem/Arakune.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Belal",
        name: "BELAL",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RB",
        secondaryPositions: ["LB", "RWB", "CB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Racing.png",
        image: "assets/characters/AngDem/Belal.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Borba",
        name: "BORBA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        secondaryPositions: ["CDM", "CAM", "RM", "LM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/AngDem/Borba.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Gorja",
        name: "GORJA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/AngDem/Gorja.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Hebimos",
        name: "HEBIMOS",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/AngDem/Hebimos.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Rubu",
        name: "RUBU",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LB",
        secondaryPositions: ["RB", "LWB", "CB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/AngDem/Rubu.png",
        background: "assets/Cartas/Oro.png"
    }
];
