const angdemCards = [
    {
        id: "AnorelOro",
        name: "ANOREL",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/AngDem/AnorelOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Anorel",
        name: "ANOREL",
        version: "Trophy",
        rarity: "Especial",
        rating: 85,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/AngDem/Anorel.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "EkadelOro",
        name: "EKADEL",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LB",
        secondaryPositions: ["LWB", "CB", "RB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/AngDem/EkadelOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Ekadel",
        name: "EKADEL",
        version: "Gris",
        rarity: "Especial",
        rating: 85,
        position: "LB",
        secondaryPositions: ["LWB", "CB", "RB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/AngDem/Ekadel.png",
        background: "assets/Cartas/Gris.png"
    },
    {
        id: "Genel",
        name: "GENEL",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/AngDem/Genel.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "NenelOro",
        name: "NENEL",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/AngDem/NenelOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Nenel",
        name: "NENEL",
        version: "Hielo",
        rarity: "Especial",
        rating: 86,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/AngDem/Nenel.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "Lephiel",
        name: "LEPHIEL",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/AngDem/Lephiel.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Sachinel",
        name: "SACHINEL",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "LM",
        secondaryPositions: ["RM", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/AngDem/Sachinel.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "WenelOro",
        name: "WENEL",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CM",
        secondaryPositions: ["CAM", "CDM", "RM", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/AngDem/WenelOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Wenel",
        name: "WENEL",
        version: "Centurion",
        rarity: "Especial",
        rating: 88,
        position: "CM",
        secondaryPositions: ["CAM", "CDM", "RM", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/AngDem/Wenel.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "Gaiel",
        name: "GAIEL",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CAM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/AngDem/Gaiel.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Ientel",
        name: "IENTEL",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        secondaryPositions: ["CAM", "CDM", "RM", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/AngDem/Ientel.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Nuel",
        name: "NUEL",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RM",
        secondaryPositions: ["LM", "RW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/AngDem/Nuel.png",
        background: "assets/Cartas/Oro.png"
    }
];
