// database/argentina_cards.js
const argentinaCards = [
    {
        id: "camiloluna_oro",
        name: "CAMILO LUNA",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Argentina/CamiloLunaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "camiloluna_rulebreaker",
        name: "CAMILO LUNA",
        version: "Rulebraker",
        rarity: "Especial",
        rating: 87,
        position: "LB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Argentina/CamiloLuna.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "galvan_oro",
        name: "GALVAN",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/Argentina/GalvanOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "galvan_manshine",
        name: "GALVAN",
        version: "Manshine",
        rarity: "Especial",
        rating: 87,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/Argentina/Galvan.png",
        background: "assets/Cartas/Manshine.png"
    },
    {
        id: "pascal_oro",
        name: "PASCAL",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "RW",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/Argentina/PascalOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "pascal_manshine",
        name: "PASCAL",
        version: "Manshine",
        rarity: "Especial",
        rating: 88,
        position: "RW",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/Argentina/Pascal2.png",
        background: "assets/Cartas/Manshine.png"
    },
    {
        id: "pascal_mordiscos",
        name: "PASCAL",
        version: "Mordiscos",
        rarity: "Especial",
        rating: 90,
        position: "RW",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/Argentina/Pascal.png",
        background: "assets/Cartas/Mordiscos.png"
    },
    {
        id: "piazzola_oro",
        name: "PIAZZOLA",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Argentina/PiazzolaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "piazzola_eeuu",
        name: "PIAZZOLA",
        version: "EEUU",
        rarity: "Especial",
        rating: 88,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Argentina/Piazzola.png",
        background: "assets/Cartas/EEUU.png"
    },
    {
        id: "saviola_oro",
        name: "SAVIOLA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Argentina/Saviola.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "zanetty_oro",
        name: "ZANETTY",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Argentina/Zanetty.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "diaz_oro",
        name: "DIAZ",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Argentina/DiazOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "diaz_azul",
        name: "DIAZ",
        version: "Azul",
        rarity: "Especial",
        rating: 89,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Argentina/Diaz.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "diaz_tots",
        name: "DIAZ",
        version: "Tots",
        rarity: "Especial",
        rating: 90,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Argentina/DIaz2.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "diaz_cabras",
        name: "DIAZ",
        version: "Cabras",
        rarity: "Especial",
        rating: 91,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Argentina/DiazEsp.png",
        background: "assets/Cartas/Cabras.png"
    },
    {
        id: "diaz_prime",
        name: "DIAZ",
        version: "Prime",
        rarity: "Especial",
        rating: 92,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Argentina/DiazPrime.png",
        background: "assets/backgrounds/Fondo_Diaz.png",
        overlay: null
    },
    {
        id: "grande_diaz_oro",
        name: "G. DIAZ",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Argentina/GrandeDiaz.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "herman_samuel_oro",
        name: "H. SAMUEL",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Argentina/HermanSamuel.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jorge_ortega_oro",
        name: "J. ORTEGA",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/Argentina/JorgeOrtega.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "julio_acosta_oro",
        name: "J. ACOSTA",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Argentina/JulioAcosta.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "lionel_cruz_oro",
        name: "L. CRUZ",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Argentina/LionelCruz.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "mario_saviola_oro",
        name: "M. SAVIOLA",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/Argentina/MarioSaviola.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "pablo_castillo_oro",
        name: "P. CASTILLO",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/Argentina/PabloCastillo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ramon_martinez_oro",
        name: "R. MARTINEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Argentina/RamonMartinez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "roberto_torres_oro",
        name: "R. TORRES",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CDM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Argentina/RobertoTorres.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sergio_perez_oro",
        name: "S. PEREZ",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Argentina/SergioPerez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "tevez_oro",
        name: "TEVEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/Argentina/Tevez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "thiago_torres_oro",
        name: "T. TORRES",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/Argentina/ThiagoTorresOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "thiago_torres_cabras",
        name: "T. TORRES",
        version: "Cabras",
        rarity: "Especial",
        rating: 90,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/Argentina/ThiagoTorres.png",
        background: "assets/Cartas/Cabras.png"
    },
    {
        id: "esteban_carlos_oro",
        name: "E. CARLOS",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Argentina/EstebanCarlos.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "diego_oro",
        name: "DIEGO",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Argentina/DiegoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "messi_oro",
        name: "MESSI",
        version: "Oro",
        rarity: "Oro",
        rating: 90,
        position: "CF",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Argentina/MessiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "messi_esp",
        name: "MESSI",
        version: "Icono",
        rarity: "Especial",
        rating: 97,
        position: "CF",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Argentina/MessiEsp.png",
        background: "assets/Cartas/Icono.png"
    },
    {
        id: "aimar_icono",
        name: "AIMAR",
        version: "Icono",
        rarity: "Icono",
        rating: 94,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Argentina/Aimar.png",
        background: "assets/Cartas/Icono.png"
    }
];

// ==========================================
// OTROS FRANCIA
// ==========================================
