const arionCards = [
    {
        id: "ArionOro",
        name: "ARION",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Arion/ArionOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ArionMixTOro",
        name: "ARION",
        version: "MixTOro",
        rarity: "Oro",
        rating: 86,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Arion/ArionMixTOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ArionMixAOro",
        name: "ARION",
        version: "MixAOro",
        rarity: "Oro",
        rating: 88,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Arion/ArionMixAOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Arion1",
        name: "ARION",
        version: "Raimon",
        rarity: "Especial",
        rating: 85,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Arion/Arion1.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "ArionGk",
        name: "ARION",
        version: "Shapesifter",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        secondaryPositions: ["ST", "LW", "RW", "LM", "RM", "CM", "CAM", "CDM", "LB", "CB", "RB"],
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Arion/ArionGk.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "ArionMang",
        name: "ARION",
        version: "Flashback",
        rarity: "Especial",
        rating: 89,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Arion/ArionMang.png",
        background: "assets/Cartas/Flashback.png"
    },
    {
        id: "ArionEsp",
        name: "ARION",
        version: "EEUU",
        rarity: "Especial",
        rating: 90,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Arion/ArionEsp.png",
        background: "assets/Cartas/EEUU.png"
    },
    {
        id: "ArionEsp3",
        name: "ARION",
        version: "Centurion",
        rarity: "Especial",
        rating: 91,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Arion/ArionEsp3.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "ArionEsp2",
        name: "ARION",
        version: "Radioactiva",
        rarity: "Especial",
        rating: 92,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Arion/ArionEsp2.png",
        background: "assets/Cartas/Radioactiva.png"
    },
    {
        id: "ArionEspMang",
        name: "ARION",
        version: "SBC",
        rarity: "Especial",
        rating: 93,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Arion/ArionEspMang.png",
        background: "assets/Cartas/SBC.png"
    },
    {
        id: "ArionPeg",
        name: "ARION",
        version: "Trophy",
        rarity: "Especial",
        rating: 94,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Arion/ArionPeg.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "ArionGrifo",
        name: "ARION",
        version: "Naranja",
        rarity: "Especial",
        rating: 95,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Arion/ArionGrifo.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "ArionPrime",
        name: "ARION",
        version: "Tots",
        rarity: "Especial",
        rating: 96,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Arion/ArionPrime.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "ArionImpulso",
        name: "ARION",
        version: "Icono",
        rarity: "Especial",
        rating: 97,
        position: "RM",
        secondaryPositions: ["ST", "LW", "RW", "LM", "CM", "CAM", "CDM", "LB", "CB", "RB", "GK"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Arion/ArionImpulso.png",
        background: "assets/Cartas/Icono.png"
    }
];
