const arsenalCards = [
    {
        id: "adamstrong_oro",
        name: "ADAM STRONG",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Arsenal/AdamStrongOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "adamstrong_eeuu",
        name: "ADAM STRONG",
        version: "EEUU",
        rarity: "Especial",
        rating: 87,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Arsenal/AdamStrong.png",
        background: "assets/Cartas/EEUU.png"
    },
    {
        id: "eagles_oro",
        name: "KELLY EAGLES",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "LM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/no.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Arsenal/EaglesOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "eagles_arsenal",
        name: "KELLY EAGLES",
        version: "Arsenal",
        rarity: "Especial",
        rating: 88,
        position: "LM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/no.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Arsenal/Eagles.png",
        background: "assets/Cartas/Arsenal.png"
    },
    {
        id: "hawkes_oro",
        name: "ROBBIE HAWKES",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CDM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/no.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Arsenal/HawkesOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hawkes_arsenal",
        name: "ROBBIE HAWKES",
        version: "Arsenal",
        rarity: "Especial",
        rating: 88,
        position: "CDM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/no.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Arsenal/Hawkes.png",
        background: "assets/Cartas/Arsenal.png"
    }
];
