const calapirataCards = [
    {
        id: "BarnabasRossa",
        name: "BARNABAS ROSSA",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/BarnabasRossa.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BartBlack",
        name: "BART BLACK",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/BartBlack.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "CalicoCorsairOro",
        name: "CALICO CORSAIR",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/CalicoCorsairOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "CalicoCorsair",
        name: "CALICO CORSAIR",
        version: "Pirata",
        rarity: "Especial",
        rating: 84,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/CalicoCorsair.png",
        background: "assets/Cartas/Pirata.png"
    },
    {
        id: "CheungPo",
        name: "CHEUNG PO",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/CheungPo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "DakkarNemoOro",
        name: "DAKKAR NEMO",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CM",
        secondaryPositions: ["CAM", "CDM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/DakkarNemoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "DakkarNemoEsp",
        name: "DAKKAR NEMO",
        version: "Azul",
        rarity: "Especial",
        rating: 87,
        position: "CM",
        secondaryPositions: ["CAM", "CDM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/DakkarNemoEsp.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "DakkarNemo",
        name: "DAKKAR NEMO",
        version: "Pirata",
        rarity: "Especial",
        rating: 89,
        position: "CM",
        secondaryPositions: ["CAM", "CDM", "RM", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/CalaPirata/DakkarNemo.png",
        background: "assets/Cartas/Pirata.png"
    },
    {
        id: "DavyJonesOro",
        name: "DAVY JONES",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/DavyJonesOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "DavyJonesEsp",
        name: "DAVY JONES",
        version: "Azul",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/DavyJonesEsp.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "DavyJonesPrime",
        name: "DAVY JONES",
        version: "Tots",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/DavyJonesPrime.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "DavyJones",
        name: "DAVY JONES",
        version: "Pirata",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/CalaPirata/DavyJones.png",
        background: "assets/Cartas/Pirata.png"
    },
    {
        id: "FrankDrake",
        name: "FRANK DRAKE",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "LB",
        secondaryPositions: ["LWB", "CB", "RB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/FrankDrake.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "IshmaelAhabOro",
        name: "ISHMAEL AHAB",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/IshmaelAhabOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "IshmaelAhab",
        name: "ISHMAEL AHAB",
        version: "Azul",
        rarity: "Especial",
        rating: 85,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/IshmaelAhab.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "IshmaelAhabPrime",
        name: "ISHMAEL AHAB",
        version: "Pirata",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/CalaPirata/IshmaelAhabPrime.png",
        background: "assets/Cartas/Pirata.png"
    },
    {
        id: "NickTofobia",
        name: "NICK TOFOBIA",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/NickTofobia.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "OctavusKrakenOro",
        name: "OCTAVUS KRAKEN",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/OctavusKrakenOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "OctavusKraken",
        name: "OCTAVUS KRAKEN",
        version: "Pirata",
        rarity: "Especial",
        rating: 86,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/OctavusKraken.png",
        background: "assets/Cartas/Pirata.png"
    },
    {
        id: "RobCrusoe",
        name: "ROB CRUSOE",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/RobCrusoe.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "RogerJolly",
        name: "ROGER JOLLY",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/RogerJolly.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "SantelmoPhyre",
        name: "SANTELMO PHYRE",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "RM",
        secondaryPositions: ["LM", "RW", "CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/SantelmoPhyre.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "SinbadSaylor",
        name: "SINBAD SAYLOR",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/SinbadSaylor.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "WilliamKidd",
        name: "WILLIAM KIDD",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "LM",
        secondaryPositions: ["RM", "LW", "CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/WilliamKidd.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MarleyHookson",
        name: "MARLEY HOOKSON",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CM",
        secondaryPositions: ["CDM", "CAM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/CalaPirata/MarleyHookson.png",
        background: "assets/Cartas/Oro.png"
    }
];
