// database/china_cards.js
const chinaCards = [
    {
        id: "fei_xiang_oro",
        name: "FEI XIANG",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/China/FeiXiangOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "zhongming_oro",
        name: "ZHONGMING",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LW",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/China/ZhongmingOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "wujunren_oro",
        name: "WU JUNREN",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/China/WuJunrenOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "qinghai_oro",
        name: "QINGHAI",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/China/QinghaiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "qinghai_milan",
        name: "QINGHAI",
        version: "Milan",
        rarity: "Especial",
        rating: 86,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/China/Qinghai.png",
        background: "assets/Cartas/Milan.png"
    },
    {
        id: "xiao_oro",
        name: "XIAO",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/China/XiaoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "xiao_bastard",
        name: "XIAO",
        version: "Bastard",
        rarity: "Especial",
        rating: 89,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/China/XiaoBastard.png",
        background: "assets/Cartas/Bastard.png"
    },
    {
        id: "xiao_prime",
        name: "XIAO",
        version: "Trailblaze",
        rarity: "Especial",
        rating: 92,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/China/XiaoPrime.png",
        background: "assets/Cartas/Trailblaze.png"
    },
    {
        id: "bruce_oro",
        name: "BRUCE",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/China/BruceLau.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "coryn_oro",
        name: "CORYN",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/China/Coryn.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "michelle_oro",
        name: "MICHELLE",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/China/Michelle.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sammo_oro",
        name: "SAMMO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/China/Sammo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "david_liang_oro",
        name: "DAVID LIANG",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/China/DavidLiang.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "donnie_oro",
        name: "DONNIE",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/China/Donnie.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "bolo_oro",
        name: "BOLO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/China/Bolo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jackie_oro",
        name: "JACKIE",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/China/JackieOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jackie_trueno",
        name: "JACKIE",
        version: "Trueno",
        rarity: "Trueno",
        rating: 89,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/China/JackieTrueno.png",
        background: "assets/Cartas/Trueno.png"
    },
    {
        id: "jimmywongfu_oro",
        name: "JIMMY WONGFU",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/China/JimmyWongfuOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jimmywongfu_manshine",
        name: "JIMMY WONGFU",
        version: "Manshine",
        rarity: "Especial",
        rating: 88,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/China/JimmyWongfu.png",
        background: "assets/Cartas/Manshine.png"
    },
    {
        id: "jetlong_oro",
        name: "JET LONG",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/China/JetLong.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "stephenchang_oro",
        name: "STEPHEN CHANG",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/China/StephenChang.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "marshung_oro",
        name: "MARS HUNG",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/China/MarsHung.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gordonsiu_oro",
        name: "GORDON SIU",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/China/GordonSiu.png",
        background: "assets/Cartas/Oro.png"
    }
];

// ==========================================
// CROACIA
// ==========================================
