const coreaCards = [
    {
        id: "jangcho_corea",
        name: "JANG CHO",
        version: "Corea",
        rarity: "Oro",
        rating: 81,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Corea/Jang Cho.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "umiwang_corea",
        name: "UMI WANG",
        version: "Corea",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Augsburg.png",
        image: "assets/characters/Corea/Umi Wang.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "doyohong_corea",
        name: "DOYO HONG",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Frankfurt.png",
        image: "assets/characters/Corea/Doyo Hong.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "minhocho_corea",
        name: "MINHO CHO",
        version: "Corea",
        rarity: "Oro",
        rating: 80,
        position: "RB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Freiburg.png",
        image: "assets/characters/Corea/Minho Cho.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "songwanko_corea",
        name: "SONGWAN KO",
        version: "Corea",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Celtic.png",
        image: "assets/characters/Corea/Songwan Ko.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "changsuchoi_corea",
        name: "CHANGSU CHOI",
        version: "Corea",
        rarity: "Especial",
        rating: 86,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Corea/Changsu Choi.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "pekyongpark_corea",
        name: "PEKYONG PARK",
        version: "Corea",
        rarity: "Oro",
        rating: 83,
        position: "CDM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Corea/Pekyong Park.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "enyongkim_corea",
        name: "ENYONG KIM",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Corea/Enyong Kim.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "chiwonho_corea",
        name: "CHI WON HO",
        version: "Corea",
        rarity: "Oro",
        rating: 80,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Corea/Chi-Won Ho.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "donghyunseul_corea",
        name: "DONG HYUN SEUL",
        version: "Corea",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Sunderland.png",
        image: "assets/characters/Corea/Dong-Hyun Seul.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "junghoonyi_corea",
        name: "JUNG HOON YI",
        version: "Corea",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/Corea/Jung-Hoon Yi.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sungjinnoh_corea",
        name: "SUNG JIN NOH",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Corea/Sung-Jin Noh.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "joonhoja_corea",
        name: "JOON HO JA",
        version: "Corea",
        rarity: "Oro",
        rating: 81,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/Corea/Joon-Ho Ja.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "dohyeonnam_corea",
        name: "DO HYEON NAM",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Corea/Do-Hyeon Nam.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "shinjaechoi_corea",
        name: "SHINJAE CHOI",
        version: "Corea",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/CrystalPalace.png",
        image: "assets/characters/Corea/Shinjae Choi.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "junhobae_corea",
        name: "JUN HO BAE",
        version: "Corea",
        rarity: "Oro",
        rating: 83,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/Corea/Jun-Ho Bae.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "yongjinseo_corea",
        name: "YONGJIN SEO",
        version: "Corea",
        rarity: "Oro",
        rating: 81,
        position: "RB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/HerthaBSC.png",
        image: "assets/characters/Corea/Yongjin Seo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ujinshin_corea",
        name: "UJIN SHIN",
        version: "Corea",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Corea/Ujin Shin.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gunwooyang_corea",
        name: "GUNWOO YANG",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Corea/Gunwoo Yang.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jihunsong_corea",
        name: "JIHUN SONG",
        version: "Corea",
        rarity: "Oro",
        rating: 81,
        position: "CDM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AstonVilla.png",
        image: "assets/characters/Corea/Jihun Song.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "minseobyun_corea",
        name: "MINSEO BYUN",
        version: "Corea",
        rarity: "Oro",
        rating: 84,
        position: "CAM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/Corea/Minseo Byun.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "soyeonsim_corea",
        name: "SOYEON SIM",
        version: "Corea",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Corea/Soyeon Sim.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "junyeonglee_corea",
        name: "JUN YEONG LEE",
        version: "Corea",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Corea/Jun-Yeong Lee.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "joonhohwang_corea",
        name: "JOON HO HWANG",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Lazio.png",
        image: "assets/characters/Corea/Joon-Ho Hwang.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "parkgombull_corea",
        name: "PARK GOM BULL",
        version: "Corea",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/NottinghamFores.png",
        image: "assets/characters/Corea/Park Gom-bull.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hwangbullgim_corea",
        name: "HWANG BULL GIM",
        version: "Corea",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Corea/Hwang Bull-gim.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kimbullbit_corea",
        name: "KIM BULL BIT",
        version: "Corea",
        rarity: "Oro",
        rating: 80,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Hoffenheim.png",
        image: "assets/characters/Corea/Kim Bull-bit.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sunabeybull_corea",
        name: "SUNA BEY BULL",
        version: "Corea",
        rarity: "Oro",
        rating: 81,
        position: "RB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Leicester.png",
        image: "assets/characters/Corea/Suna Bey-bull.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hanbulldang_corea",
        name: "HAN BULL DANG",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Corea/Han Bull-dang.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "yeonbullsay_corea",
        name: "YEON BULL SAY",
        version: "Corea",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Corea/Yeon Bull-say.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "leebullgae_corea",
        name: "LEE BULL GAE",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "CAM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/Corea/Lee Bull-gae.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "seoktelbull_corea",
        name: "SEOK TEL BULL",
        version: "Corea",
        rarity: "Especial",
        rating: 85,
        position: "CAM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Corea/Seok Tel-bull.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "shinbullkot_corea",
        name: "SHIN BULL KOT",
        version: "Corea",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/Corea/Shin Bull-kot.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "baekbullwo_corea",
        name: "BAEK BULL WO",
        version: "Corea",
        rarity: "Especial",
        rating: 86,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Corea/Baek Bull-wo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "leesanbull_corea",
        name: "LEE SAN BULL",
        version: "Corea",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Schalke.png",
        image: "assets/characters/Corea/Lee San-bull.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hobulltong_corea",
        name: "HO BULL TONG",
        version: "Corea",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Benfica.png",
        image: "assets/characters/Corea/Ho Bull-tong.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sonbullgong_corea",
        name: "SON BULL GONG",
        version: "Corea",
        rarity: "Oro",
        rating: 81,
        position: "CDM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/WestHam.png",
        image: "assets/characters/Corea/Son Bull-gong.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "harhbullgull_corea",
        name: "HARH BULL GULL",
        version: "Corea",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/Corea/Harh Bull-gull.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "leeyong_un_oro",
        name: "LEE YONG-UN",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Corea/LeeYong-un.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "chaincheon_oro",
        name: "CHA INCHEON",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Monchengladbach.png",
        image: "assets/characters/Corea/ChaIncheonOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "chaincheon_bundes",
        name: "CHA INCHEON",
        version: "Bundesliga",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Monchengladbach.png",
        image: "assets/characters/Corea/ChaIncheon.png",
        background: "assets/Cartas/Bundes.png"
    }
];
