const coreaExtraCards = [
    {
        id: "jangchofuego_corea",
        name: "JANG CHO",
        version: "Fuego",
        rarity: "Especial",
        rating: 84,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Corea/Jang ChoFuego.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "jangcho_prime",
        name: "JANG CHO",
        version: "Prime",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Corea/Jang ChoFuegoPrime.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "changsuchomor_corea",
        name: "CHANGSU CHOI",
        version: "Mor",
        rarity: "Especial",
        rating: 88,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Corea/Changsu ChoMor.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "changsuchoi_tramp",
        name: "CHANGSU CHOI",
        version: "Tramp",
        rarity: "Especial",
        rating: 90,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Corea/Changsu ChoiTramp.png",
        background: "assets/Cartas/Radioactiva.png"
    },
    {
        id: "changsuchoi_prime",
        name: "CHANGSU CHOI",
        version: "Prime",
        rarity: "Especial",
        rating: 92,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Corea/Changsu ChoiPrime.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "shinjaechoi_prime",
        name: "SHINJAE CHOI",
        version: "Prime",
        rarity: "Especial",
        rating: 86,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/CrystalPalace.png",
        image: "assets/characters/Corea/Shinjae ChoiPrime.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "junyeonglee2_corea",
        name: "JUN YEONG LEE",
        version: "2",
        rarity: "Especial",
        rating: 87,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Corea/Jun-Yeong Lee2.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "junyeonglee_prime",
        name: "JUN YEONG LEE",
        version: "Prime",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Corea/Jun-Yeong LeePrime.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "junhobae_prime",
        name: "JUN HO BAE",
        version: "Prime",
        rarity: "Especial",
        rating: 86,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/Corea/Jun-Ho BaePrime.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "parkgombull2_corea",
        name: "PARK GOM BULL",
        version: "2",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/NottinghamFores.png",
        image: "assets/characters/Corea/Park Gom-bull2.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "parkgombull_prime",
        name: "PARK GOM BULL",
        version: "Prime",
        rarity: "Especial",
        rating: 90,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/NottinghamFores.png",
        image: "assets/characters/Corea/Park Gom-bullPrime.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "pekyongpark_prime",
        name: "PEKYONG PARK",
        version: "Prime",
        rarity: "Especial",
        rating: 86,
        position: "CDM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Corea/Pekyong ParkPrime.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "baekbullwofuego_corea",
        name: "BAEK BULL WO",
        version: "Fuego",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Corea/Baek Bull-woFuego.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "baekbullwocab_corea",
        name: "BAEK BULL WO",
        version: "Cab",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Corea/Baek Bull-woCab.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "baekbullwo_prime",
        name: "BAEK BULL WO",
        version: "Prime",
        rarity: "Especial",
        rating: 93,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Corea/Baek Bull-woPrime.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "seoktelbull2_corea",
        name: "SEOK TEL BULL",
        version: "2",
        rarity: "Especial",
        rating: 88,
        position: "CAM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Corea/Seok Tel-bull2.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "seoktelbull_prime",
        name: "SEOK TEL BULL",
        version: "Prime",
        rarity: "Especial",
        rating: 91,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Corea/Seok Tel-bullPrime.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "shinbullkot_roja",
        name: "SHIN BULL KOT",
        version: "Roja",
        rarity: "Especial",
        rating: 87,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/Corea/Shin Bull-kot2.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "leesanbull_prime",
        name: "LEE SAN BULL",
        version: "Prime",
        rarity: "Especial",
        rating: 86,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Schalke.png",
        image: "assets/characters/Corea/Lee San-bullPrime.png",
        background: "assets/Cartas/Naranja.png"
    }
];
