const earthElevenCards = [
    {
        id: "ZackAvalonOro",
        name: "ZACK AVALON",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/EarthEleven/ZackAvalonOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ZackAvalon",
        name: "ZACK AVALON",
        version: "Roja",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/EarthEleven/ZackAvalon.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "ZackAvalonPrime",
        name: "ZACK AVALON",
        version: "Trophy",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/EarthEleven/ZackAvalonPrime.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "KeenanSharpeOro",
        name: "KEENAN SHARPE",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Brighton.png",
        image: "assets/characters/EarthEleven/KeenanSharpeOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "KeenanSharpeB",
        name: "KEENAN SHARPE",
        version: "Raimon",
        rarity: "Especial",
        rating: 87,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Brighton.png",
        image: "assets/characters/EarthEleven/KeenanSharpeB.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "KeenanSharpe",
        name: "KEENAN SHARPE",
        version: "Centurion",
        rarity: "Especial",
        rating: 91,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Brighton.png",
        image: "assets/characters/EarthEleven/KeenanSharpe.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "TrinaVerdureOro",
        name: "TRINA VERDURE",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LB",
        secondaryPositions: ["LWB", "CB", "RB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/EarthEleven/TrinaVerdureOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "TrinaVerdure",
        name: "TRINA VERDURE",
        version: "Wild",
        rarity: "Especial",
        rating: 86,
        position: "LB",
        secondaryPositions: ["LWB", "CB", "RB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/EarthEleven/TrinaVerdure.png",
        background: "assets/Cartas/Wild.png"
    },
    {
        id: "TrinaVerdurePrime",
        name: "TRINA VERDURE",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 90,
        position: "LB",
        secondaryPositions: ["LWB", "CB", "RB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/EarthEleven/TrinaVerdurePrime.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "FrankForemanOro",
        name: "FRANK FOREMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/EarthEleven/FrankForemanOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "FrankForeman",
        name: "FRANK FOREMAN",
        version: "Roja",
        rarity: "Especial",
        rating: 87,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/EarthEleven/FrankForeman.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "FrankForemanDesp",
        name: "FRANK FOREMAN",
        version: "Rojiazul",
        rarity: "Especial",
        rating: 90,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/EarthEleven/FrankForemanDesp.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "FrankForemanPrime",
        name: "FRANK FOREMAN",
        version: "Trailblaze",
        rarity: "Especial",
        rating: 93,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/EarthEleven/FrankForemanPrime.png",
        background: "assets/Cartas/Trailblaze.png"
    },
    {
        id: "CeriseBlossomOro",
        name: "CERISE BLOSSOM",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "LM",
        secondaryPositions: ["RM", "LW", "CM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/EarthEleven/CeriseBlossomOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "CeriseBlossom",
        name: "CERISE BLOSSOM",
        version: "Chicle",
        rarity: "Especial",
        rating: 87,
        position: "LM",
        secondaryPositions: ["RM", "LW", "CM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/EarthEleven/CeriseBlossom.png",
        background: "assets/Cartas/Chicle.png"
    },
    {
        id: "CeriseBlossomPrime",
        name: "CERISE BLOSSOM",
        version: "FutureStar",
        rarity: "Especial",
        rating: 91,
        position: "LM",
        secondaryPositions: ["RM", "LW", "CM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/EarthEleven/CeriseBlossomPrime.png",
        background: "assets/Cartas/FutureStar.png"
    },
    {
        id: "ZippyLernerOro",
        name: "ZIPPY LERNER",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/EarthEleven/ZippyLernerOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ZippyLernerPrime",
        name: "ZIPPY LERNER",
        version: "Morado",
        rarity: "Especial",
        rating: 87,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/EarthEleven/ZippyLernerPrime.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "ZippyLerner",
        name: "ZIPPY LERNER",
        version: "FutureStar",
        rarity: "Especial",
        rating: 91,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/EarthEleven/ZippyLerner.png",
        background: "assets/Cartas/FutureStar.png"
    }
];
