// database/eeuu_cards.js
const eeuuCards = [
{
        id: "markkrueger_eeuu",
        name: "MARK KRUEGER",
        version: "EEUU",
        rarity: "EEUU",
        rating: 89,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/USA/MarkKrueger.png",
        background: "assets/Cartas/EEUU.png"
},
{
        id: "dylankeats_eeuu",
        name: "DYLAN KEATS",
        version: "EEUU",
        rarity: "EEUU",
        rating: 88,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/USA/DylanKeats.png",
        background: "assets/Cartas/EEUU.png"
},
{
        id: "billydash_oro",
        name: "BILLY DASH",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/USA/BillyDash.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "tedbryant_oro",
        name: "TED BRYANT",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/USA/TedBryant.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "tonystrider_oro",
        name: "TONY STRIDER",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/USA/TonyStrider.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "drakedynamo_oro",
        name: "DRAKE DYNAMO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/USA/DrakeDynamo.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "bobbyshearer_oro",
        name: "BOBBY SHEARER",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/USA/BobbyShearerOro.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "bobbyshearer_eeuu",
        name: "BOBBY SHEARER",
        version: "EEUU",
        rarity: "EEUU",
        rating: 86,
        position: "RB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/USA/BobbyShearer.png",
        background: "assets/Cartas/EEUU.png"
},
{
        id: "stevewoodmark_oro",
        name: "STEVE WOODMARK",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/USA/SteveWoodmark.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "erikeagle_oro",
        name: "ERIK EAGLE",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "LM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/USA/ErikEagleOro.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "erikeagle_eeuu",
        name: "ERIK EAGLE",
        version: "EEUU",
        rarity: "EEUU",
        rating: 88,
        position: "LM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/USA/ErikEagle.png",
        background: "assets/Cartas/EEUU.png"
},
{
        id: "shanepierce_oro",
        name: "SHANE PIERCE",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/USA/ShanePierce.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "markkrueger_oro",
        name: "MARK KRUEGER",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/USA/MarkKruegerOro.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "dylankeats_oro",
        name: "DYLAN KEATS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/USA/DylanKeatsOro.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "gabrieljax_oro",
        name: "GABRIEL JAX",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/USA/GabrielJax.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "alexhawke_oro",
        name: "ALEX HAWKE",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/USA/AlexHawke.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "petiepooma_oro",
        name: "PETIE POOMA",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/USA/PetiePooma.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "norbertpoindexter_oro",
        name: "NORBERT POINDEXTER",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/USA/NorbertPoindexter.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "bigman_oro",
        name: "BIGMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/USA/Bigman.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "charmer_oro",
        name: "CHARMER",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/USA/Charmer.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "scuba_oro",
        name: "SCUBA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/USA/Scuba.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "smokestack_oro",
        name: "SMOKESTACK",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/USA/Smokestack.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "judge_oro",
        name: "JUDGE",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/USA/Judge.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "hunter_oro",
        name: "HUNTER",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/USA/Hunter.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "yoga_oro",
        name: "YOGA",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/USA/Yoga.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "cobra_oro",
        name: "COBRA",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/USA/Cobra.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "mop_oro",
        name: "MOP",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/USA/Mop.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "moai_oro",
        name: "MOAI",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/USA/Moai.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "hellion_oro",
        name: "HELLION",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/USA/Hellion.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "howler_oro",
        name: "HOWLER",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/USA/Howler.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "wizard_oro",
        name: "WIZARD",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "RM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/USA/Wizard.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "switch_oro",
        name: "SWITCH",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "LW",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/USA/Switch.png",
        background: "assets/Cartas/Oro.png"
},

    {
        id: "bacchus_oro",
        name: "BACCHUS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/USA/BacchusOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "bacchus_custom",
        name: "BACCHUS",
        version: "Ubers",
        rarity: "Especial",
        rating: 88,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/USA/Bacchus.png",
        background: "assets/backgrounds/Fondo_Bacchus.png"
    },
    {
        id: "azwan_oro",
        name: "AZWAN",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/USA/AzwanOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "azwan_eeuu",
        name: "AZWAN",
        version: "EEUU",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/USA/Azwan.png",
        background: "assets/Cartas/EEUU.png"
    },
    {
        id: "blake_oro",
        name: "BLAKE",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/USA/BlakeOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "blake_eeuu",
        name: "BLAKE",
        version: "EEUU",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/USA/Blake.png",
        background: "assets/Cartas/EEUU.png"
    },
    {
        id: "ortiz_oro",
        name: "ORTIZ",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/USA/OrtizOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ortiz_eeuu",
        name: "ORTIZ",
        version: "Joker",
        rarity: "Especial",
        rating: 89,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/USA/Ortiz.png",
        background: "assets/Cartas/Joker.png"
    }
];

// ==========================================
// PORTO
// ==========================================
