// database/espana_cards.js
const espanaCards = [
{
        id: "fersiotorres_oro",
        name: "FERSIO TORRES",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/España/FersioTorresOro.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "fersiotorres_chikorid",
        name: "FERSIO TORRES",
        version: "Chicorid",
        rarity: "Chicorid",
        rating: 90,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/España/FersioTorres.png",
        background: "assets/Cartas/Chicorid.png"
},
{
        id: "bunny_oro",
        name: "BUNNY",
        version: "Oro",
        rarity: "Oro",
        rating: 88,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/BunnyOro.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "bunny_barcha",
        name: "BUNNY",
        version: "Barcha",
        rarity: "Barcha",
        rating: 91,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/Bunny.png",
        background: "assets/Cartas/Barcha.png"
},
{
        id: "bunny_prime",
        name: "BUNNY",
        version: "Trailblaze",
        rarity: "Trailblaze",
        rating: 94,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/BunnyPrime.png",
        background: "assets/Cartas/Trailblaze.png"
},
{
        id: "leonardoluna_oro",
        name: "LEONARDO LUNA",
        version: "Oro",
        rarity: "Oro",
        rating: 89,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/LeonardoLunaOro.png",
        background: "assets/Cartas/Oro.png"
},
{
        id: "leonardoluna_2",
        name: "LEONARDO LUNA",
        version: "Real",
        rarity: "Real",
        rating: 93,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/LeonardoLuna2.png",
        background: "assets/Cartas/Real.png"
},
{
        id: "leonardoluna_3",
        name: "LEONARDO LUNA",
        version: "Radioactiva",
        rarity: "Radioactiva",
        rating: 95,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/LeonardoLuna3.png",
        background: "assets/Cartas/Radioactiva.png"
},

    {
        id: "michael_numancia_1",
        name: "MICHAEL",
        version: "Roma",
        rarity: "Especial",
        rating: 93,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/España/Michael.png",
        background: "assets/Cartas/Espana.png"
    },
    {
        id: "michael_numancia_2",
        name: "MICHAEL",
        version: "Especial",
        rarity: "Especial",
        rating: 95,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/España/Michael2.png",
        background: "assets/Cartas/Espana.png"
    },
    {
        id: "raphael_numancia_1",
        name: "RAPHAEL",
        version: "Roma",
        rarity: "Especial",
        rating: 88,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/España/Raphael.png",
        background: "assets/Cartas/Espana.png"
    },
    {
        id: "raphael_numancia_2",
        name: "RAPHAEL",
        version: "Especial",
        rarity: "Especial",
        rating: 90,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/España/Raphael2.png",
        background: "assets/Cartas/Espana.png"
    },
    {
        id: "callusias_real",
        name: "CALLUSIAS",
        version: "Real Madrid",
        rarity: "Especial",
        rating: 91,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/Callusias.png"
    },
    {
        id: "blueno_oro",
        name: "BLUENO",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/BluenoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "callusias_oro",
        name: "CALLUSIAS",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/CallusiasOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "marientes_oro",
        name: "MARIENTES",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/MarientesOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "michael_oro",
        name: "MICHAEL",
        version: "Oro",
        rarity: "Oro",
        rating: 90,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/España/MichaelOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "olgado_oro",
        name: "OLGADO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/OlgadoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "payol_oro",
        name: "PAYOL",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/PayolOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "raphael_oro",
        name: "RAPHAEL",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/España/RaphaelOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gonzalez_oro",
        name: "GONZALEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/GonzalesOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "grandios_oro",
        name: "GRANDIOS",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/GrandiosOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "xavii_oro",
        name: "XAVII",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/XaviiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "salvadorcastelloro",
        name: "SALVADOR CASTELL ORO",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/SalvadorCastellOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "salvadorcastell_españa",
        name: "SALVADOR CASTELL",
        version: "España",
        rarity: "España",
        rating: 88,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/SalvadorCastell.png",
        background: "assets/Cartas/Espana.png"
    },
    {
        id: "manuelgutierrez",
        name: "MANUEL GUTIERREZ",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/España/ManuelGutierrez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "daniramos",
        name: "DANI RAMOS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/España/DaniRamos.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "miguelhontiveros",
        name: "MIGUEL HONTIVEROS",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/España/MiguelHontiveros.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "alvaromelendez",
        name: "ALVARO MELENDEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/España/AlvaroMelendez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "andresalonso",
        name: "ANDRES ALONSO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/España/AndresAlonso.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "josemarigonzalez",
        name: "JOSE MARI GONZALEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/España/JoseMariGonzalez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "chichomuñoz",
        name: "CHICHO MUÑOZ",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/España/ChichoMuñoz.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "leosegarra",
        name: "LEO SEGARRA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/LeoSegarra.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sergihernandezoro",
        name: "SERGI HERNANDEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/SergiHernandezOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "carlesripoll",
        name: "CARLES RIPOLL",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/CarlesRipoll.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sergihernandez_españa",
        name: "SERGI HERNANDEZ",
        version: "España",
        rarity: "España",
        rating: 90,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/SergiHernandez.png",
        background: "assets/Cartas/Espana.png"
    },
    {
        id: "raulparejo",
        name: "RAUL PAREJO",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/España/RaulParejo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "marcoscanales",
        name: "MARCOS CANALES",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/España/MarcosCanales.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "joanasensi",
        name: "JOAN ASENSI",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "LW",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/JoanAsensi.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "antonivalls",
        name: "ANTONI VALLS",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/AntoniValls.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jordibelloch",
        name: "JORDI BELLOCH",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/JordiBelloch.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gerardcarbonell",
        name: "GERARD CARBONELL",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/GerardCarbonell.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "josepanglesola",
        name: "JOSEP ANGLESOLA",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/JosepAnglesola.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "xavicasals",
        name: "XAVI CASALS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/XaviCasals.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ronaldoramallets",
        name: "RONALDO RAMALLETS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/RonaldoRamallets.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "augustogomez",
        name: "AUGUSTO GOMEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/AugustoGomez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "geraldoenrique",
        name: "GERALDO ENRIQUE",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/España/GeraldoEnrique.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "alfonsoíñigo",
        name: "ALFONSOÍÑIGO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/España/AlfonsoÍñigo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "josecosta",
        name: "JOSE COSTA",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/España/JoseCosta.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "joselopez",
        name: "JOSE LOPEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/España/JoseLopez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "víctorgarcia",
        name: "VÍCTOR GARCIA",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/España/VíctorGarciaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "antoniogarrido",
        name: "ANTONIO GARRIDO",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/España/AntonioGarrido.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "joanrodriguez",
        name: "JOAN RODRIGUEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/España/JoanRodriguez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "igorferreira",
        name: "IGOR FERREIRA",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/España/IgorFerreira.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "miguelpereira",
        name: "MIGUEL PEREIRA",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/España/MiguelPereira.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "borjacosta",
        name: "BORJA COSTA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/España/BorjaCosta.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "mateobonachea",
        name: "MATEO BONACHEA",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/España/MateoBonachea.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "migueljimenez",
        name: "MIGUEL JIMENEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/España/MiguelJimenez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "juanespindola",
        name: "JUAN ESPINDOLA",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/España/JuanEspindola.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "isaaccesar",
        name: "ISAAC CESAR",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/España/IsaacCesar.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "laudelinocastor",
        name: "LAUDELINO CASTOR",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/España/LaudelinoCastor.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "federicorubiera",
        name: "FEDERICO RUBIERA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/España/FedericoRubiera.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "carlosarroyo",
        name: "CARLOS ARROYO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/España/CarlosArroyo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gati",
        name: "GATI",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/Gati.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "rams",
        name: "RAMS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/España/Rams.png",
        background: "assets/Cartas/Oro.png"
    },
];

// ==========================================
// HOLANDA NUEVOS
// ==========================================
const holandaCardsNuevos = [
    {
        id: "brian_united",
        name: "B. KLUIVOORT",
        version: "Manchester United",
        rarity: "Especial",
        rating: 92,
        position: "CAM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Holanda/BrianKluivoort.png"
    },
    {
        id: "stijn_ajax_nuevo",
        name: "S. KLUIVOORT",
        version: "Ajax",
        rarity: "Especial",
        rating: 89,
        position: "CDM",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/StijnKluivoort2.png"
    },
    {
        id: "davi_ubers_especial",
        name: "DAVI",
        version: "Ubers Especial",
        rarity: "Especial",
        rating: 90,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Holanda/Davi.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "davi_ubers_normal",
        name: "DAVI",
        version: "Ubers",
        rarity: "Especial",
        rating: 87,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Holanda/DaviUbers.png"
    },
    {
        id: "dick_ajax",
        name: "DICK",
        version: "Ajax",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/Dick.png"
    },
    {
        id: "doleman_ajax",
        name: "DOLEMAN",
        version: "Ajax",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/Doleman.png"
    },
    {
        id: "kaiser_ajax",
        name: "KAISER",
        version: "Ajax",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/Kaiser.png"
    },
    {
        id: "klismann_ajax",
        name: "KLISMANN",
        version: "Ajax",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/Klismann.png"
    },
    {
        id: "lensenblink_ajax",
        name: "LESENBLINK",
        version: "Ajax",
        rarity: "Especial",
        rating: 86,
        position: "CM",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/Lensenblink.png"
    },
    {
        id: "luikal_barcha",
        name: "LUIKAL",
        version: "Barcha",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Holanda/Luikal.png"
    }
];

// ==========================================
// SUECIA
// ==========================================
