const falcoCards = [
    {
        id: "FalcoOro",
        name: "FALCO FLASHMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "RW",
        secondaryPositions: ["RM", "LW", "ST"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/malaga.png",
        image: "assets/characters/Falco/FalcoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "FalcoPOro",
        name: "FALCO FLASHMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "RW",
        secondaryPositions: ["RM", "LW", "ST"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Falco/FalcoPOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "FalcoPar",
        name: "FALCO FLASHMAN",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 88,
        position: "RW",
        secondaryPositions: ["RM", "LW", "ST"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/malaga.png",
        image: "assets/characters/Falco/FalcoPar.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "FalcoReg",
        name: "FALCO FLASHMAN",
        version: "Rojiazul",
        rarity: "Especial",
        rating: 89,
        position: "RW",
        secondaryPositions: ["RM", "LW", "ST"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Falco/FalcoReg.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "FalcoNorm",
        name: "FALCO FLASHMAN",
        version: "EEUU",
        rarity: "Especial",
        rating: 91,
        position: "RW",
        secondaryPositions: ["RM", "LW", "ST"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/malaga.png",
        image: "assets/characters/Falco/FalcoNorm.png",
        background: "assets/Cartas/EEUU.png"
    },
    {
        id: "FalcoAlc",
        name: "FALCO FLASHMAN",
        version: "Tots",
        rarity: "Especial",
        rating: 93,
        position: "RW",
        secondaryPositions: ["RM", "LW", "ST"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Falco/FalcoAlc.png",
        background: "assets/Cartas/Tots.png"
    }
];
