// database/farm_cards.js
const farmCards = [
    { id: "albert_green_oro", name: "ALBERT GREEN", version: "Oro", rarity: "Oro", rating: 83, position: "GK", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/AlbertGreenOro.png", background: "assets/Cartas/Oro.png" },
    { id: "albert_green_granja", name: "ALBERT GREEN", version: "Granja", rarity: "Especial", rating: 86, position: "GK", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/AlbertGreen.png", background: "assets/Cartas/Granja.png" },
    
    { id: "ben_nevis_oro", name: "BEN NEVIS", version: "Oro", rarity: "Oro", rating: 80, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/BenNevis.png", background: "assets/Cartas/Oro.png" },
    { id: "daniel_dawson_oro", name: "DANIEL DAWSON", version: "Oro", rarity: "Oro", rating: 78, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/DanielDawson.png", background: "assets/Cartas/Oro.png" },
    { id: "herb_sherman_oro", name: "HERB SHERMAN", version: "Oro", rarity: "Oro", rating: 80, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/HerbSherman.png", background: "assets/Cartas/Oro.png" },
    { id: "homer_grower_oro", name: "HOMER GROWER", version: "Oro", rarity: "Oro", rating: 77, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/HomerGrower.png", background: "assets/Cartas/Oro.png" },
    { id: "ike_steiner_oro", name: "IKE STEINER", version: "Oro", rarity: "Oro", rating: 78, position: "RM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/IkeSteiner.png", background: "assets/Cartas/Oro.png" },
    { id: "joe_small_oro", name: "JOE SMALL", version: "Oro", rarity: "Oro", rating: 79, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/JoeSmall.png", background: "assets/Cartas/Oro.png" },
    { id: "kent_work_oro", name: "KENT WORK", version: "Oro", rarity: "Oro", rating: 80, position: "LB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/KentWork.png", background: "assets/Cartas/Oro.png" },
    { id: "lorne_mower_oro", name: "LORNE MOWER", version: "Oro", rarity: "Oro", rating: 79, position: "GK", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/LorneMower.png", background: "assets/Cartas/Oro.png" },
    { id: "luke_lively_oro", name: "LUKE LIVELY", version: "Oro", rarity: "Oro", rating: 78, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/LukeLively.png", background: "assets/Cartas/Oro.png" },
    
    { id: "mark_hillvalley_oro", name: "MARK HILLVALLEY", version: "Oro", rarity: "Oro", rating: 84, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/MarkHillvalleyOro.png", background: "assets/Cartas/Oro.png" },
    { id: "mark_hillvalley_granja", name: "MARK HILLVALLEY", version: "Granja", rarity: "Especial", rating: 87, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/MarkHillvalley.png", background: "assets/Cartas/Granja.png" },
    
    { id: "orville_newman_oro", name: "ORVILLE NEWMAN", version: "Oro", rarity: "Oro", rating: 81, position: "LM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/OrvilleNewman.png", background: "assets/Cartas/Oro.png" },
    
    { id: "tom_walters_oro", name: "TOM WALTERS", version: "Oro", rarity: "Oro", rating: 82, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/TomWaltersOro.png", background: "assets/Cartas/Oro.png" },
    { id: "tom_walters_granja", name: "TOM WALTERS", version: "Granja", rarity: "Especial", rating: 85, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/TomWalters.png", background: "assets/Cartas/Granja.png" },
    
    { id: "rolf_howells_oro", name: "ROLF HOWELLS", version: "Oro", rarity: "Oro", rating: 79, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/RolfHowells.png", background: "assets/Cartas/Oro.png" },
    { id: "seward_hayseed_oro", name: "SEWARD HAYSEED", version: "Oro", rarity: "Oro", rating: 81, position: "RB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/SewardHayseed.png", background: "assets/Cartas/Oro.png" },
    { id: "stuart_racoonfur_oro", name: "STUART RACOONFUR", version: "Oro", rarity: "Oro", rating: 79, position: "ST", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Muralla.png", image: "assets/characters/Farm/StuartRacoonfur.png", background: "assets/Cartas/Oro.png" }
];
