const feiRuneCards = [
    {
        id: "FeiOro",
        name: "FEI RUNE",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Fei/FeiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "FeiMixTOro",
        name: "FEI RUNE",
        version: "MixTOro",
        rarity: "Oro",
        rating: 87,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/Fei/FeiMixTOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "FeiBMix",
        name: "FEI RUNE",
        version: "BMix",
        rarity: "Especial",
        rating: 88,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Fei/FeiBMix.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "FeiSaltos",
        name: "FEI RUNE",
        version: "Saltos",
        rarity: "Especial",
        rating: 89,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Fei/FeiSaltos.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "FeiMixTRed",
        name: "FEI RUNE",
        version: "MixTRed",
        rarity: "Especial",
        rating: 90,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/Fei/FeiMixTRed.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "FeiMixFlash",
        name: "FEI RUNE",
        version: "MixFlash",
        rarity: "Especial",
        rating: 91,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Fei/FeiMixFlash.png",
        background: "assets/Cartas/Flashback.png"
    },
    {
        id: "FeiMixTChut",
        name: "FEI RUNE",
        version: "MixTChut",
        rarity: "Especial",
        rating: 92,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Fei/FeiMixTChut.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "FeiMixBig",
        name: "FEI RUNE",
        version: "MixBig",
        rarity: "Especial",
        rating: 93,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Fei/FeiMixBig.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "FeiBig",
        name: "FEI RUNE",
        version: "Big",
        rarity: "Especial",
        rating: 94,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/Fei/FeiBig.png",
        background: "assets/Cartas/Mordiscos.png"
    },
    {
        id: "FeiArmPrime",
        name: "FEI RUNE",
        version: "ArmPrime",
        rarity: "Especial",
        rating: 95,
        position: "LW",
        secondaryPositions: ["ST", "RW", "CAM", "CM", "RM", "LM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Fei/FeiArmPrime.png",
        background: "assets/Cartas/Tots.png"
    }
];
