const fuegoHieloCards = [
    {
        id: "GazelOro",
        name: "GAZEL",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/GazelOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BryceWhitingaleCorOro",
        name: "BRYCE WHITINGALE",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/FuegoHielo/BryceWhitingaleCorOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BryceWhitingaleOro",
        name: "BRYCE WHITINGALE",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/BryceWhitingaleOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BryceBase",
        name: "BRYCE WHITINGALE",
        version: "Azul",
        rarity: "Especial",
        rating: 88,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/BryceBase.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "GazelChut",
        name: "GAZEL",
        version: "Hielo",
        rarity: "Especial",
        rating: 89,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/GazelChut.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "GazelChute2",
        name: "GAZEL",
        version: "Manshine",
        rarity: "Especial",
        rating: 90,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/FuegoHielo/GazelChute2.png",
        background: "assets/Cartas/Manshine.png"
    },
    {
        id: "BryceChut",
        name: "BRYCE WHITINGALE",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 91,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/BryceChut.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "GazelAura",
        name: "GAZEL",
        version: "Tots",
        rarity: "Especial",
        rating: 92,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/GazelAura.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "GazelTorch",
        name: "BRYCE WHITINGALE",
        version: "RojiAzul",
        rarity: "Especial",
        rating: 93,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/FuegoHielo/GazelTorch.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "GazelPayaso",
        name: "GAZEL",
        version: "SBC",
        rarity: "Especial",
        rating: 90,
        position: "RW",
        secondaryPositions: ["RM", "ST", "RB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/GazelPayaso.png",
        background: "assets/Cartas/SBC.png"
    },
    {
        id: "TorchOro",
        name: "TORCH",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/TorchOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ClaudeCorOro",
        name: "CLAUDE BEACON",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/FuegoHielo/ClaudeCorOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ClaudeOro",
        name: "CLAUDE BEACON",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/ClaudeOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ClaudeBase",
        name: "CLAUDE BEACON",
        version: "Roja",
        rarity: "Especial",
        rating: 88,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/ClaudeBase.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "TorchChut",
        name: "TORCH",
        version: "Naranja",
        rarity: "Especial",
        rating: 89,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/TorchChut.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "ClaudeChut",
        name: "CLAUDE BEACON",
        version: "Trailblaze",
        rarity: "Especial",
        rating: 90,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/FuegoHielo/ClaudeChut.png",
        background: "assets/Cartas/Trailblaze.png"
    },
    {
        id: "TorchPrime",
        name: "TORCH",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 91,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/TorchPrime.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "TorchAura",
        name: "TORCH",
        version: "Trophy",
        rarity: "Especial",
        rating: 92,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/TorchAura.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "TorchGazel",
        name: "CLAUDE BEACON",
        version: "RojiAzul",
        rarity: "Especial",
        rating: 93,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/FuegoHielo/TorchGazel.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "TorchPayaso",
        name: "TORCH",
        version: "SBC",
        rarity: "Especial",
        rating: 90,
        position: "LW",
        secondaryPositions: ["LM", "ST", "LB", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/kr.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/FuegoHielo/TorchPayaso.png",
        background: "assets/Cartas/SBC.png"
    }
];
