const geminisCards = [
    {
        id: "charon_oro",
        name: "CHARON",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "RB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/CharonOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "charon_morado",
        name: "CHARON",
        version: "Morado",
        rarity: "Especial",
        rating: 84,
        position: "RB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Charon.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "coral_oro",
        name: "CORAL",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Coral.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "diam_oro",
        name: "DIAM",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/DiamOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "diam_morado",
        name: "DIAM",
        version: "Morado",
        rarity: "Especial",
        rating: 86,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Diam.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "galileo_oro",
        name: "GALILEO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/GalileoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "galileo_morado",
        name: "GALILEO",
        version: "Morado",
        rarity: "Especial",
        rating: 86,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Galileo.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "ganymede_oro",
        name: "GANYMEDE",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/GanymedeOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ganymede_morado",
        name: "GANYMEDE",
        version: "Morado",
        rarity: "Especial",
        rating: 84,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Ganymede.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "gigs_oro",
        name: "GIGS",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Gigs.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "grengo_oro",
        name: "GRENGO",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Grengo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "io_oro",
        name: "IO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Io.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "pandora_oro",
        name: "PANDORA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CDM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Pandora.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "rihm_oro",
        name: "RIHM",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/Rihm.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "janus_oro",
        name: "JANUS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Geminis/JanusOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jordan_greenway_ares_oro",
        name: "JORDAN GREENWAY",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/JordanGreenwayAresOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jordan_greenway_sel_oro",
        name: "JORDAN GREENWAY",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Wolfsburg.png",
        image: "assets/characters/Geminis/JordanGreenwaySelOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jordan_ares",
        name: "JORDAN GREENWAY",
        version: "Ares",
        rarity: "Especial",
        rating: 87,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/JordanAres.png",
        background: "assets/Cartas/SBC.png"
    },
    {
        id: "janus_astro",
        name: "JANUS",
        version: "Astro",
        rarity: "Especial",
        rating: 88,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Geminis/JanusAstro.png",
        background: "assets/Cartas/Radioactiva.png"
    },
    {
        id: "jordan_pas",
        name: "JORDAN GREENWAY",
        version: "Pasado",
        rarity: "Especial",
        rating: 89,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Wolfsburg.png",
        image: "assets/characters/Geminis/JordanPas.png",
        background: "assets/Cartas/Flashback.png"
    },
    {
        id: "jordan_ares_prime",
        name: "JORDAN GREENWAY",
        version: "Ares Prime",
        rarity: "Especial",
        rating: 91,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Geminis/JordanAresPrime.png",
        background: "assets/Cartas/Icono.png"
    },
    {
        id: "janus_prime",
        name: "JANUS",
        version: "Prime",
        rarity: "Especial",
        rating: 92,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Geminis/JanusPrime.png",
        background: "assets/Cartas/Toty.png"
    },
    {
        id: "jordan_greenway_astro",
        name: "JORDAN GREENWAY",
        version: "Astro Prime",
        rarity: "Especial",
        rating: 93,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Wolfsburg.png",
        image: "assets/characters/Geminis/JordanGreenwayAstro.png",
        background: "assets/Cartas/Trophy.png"
    }
];
