const goldieLemonCards = [
    {
        id: "GoldieOro",
        name: "GOLDIE LEMON",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Goldie/GoldieOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "GoldieMixOro",
        name: "GOLDIE LEMON",
        version: "MixOro",
        rarity: "Oro",
        rating: 88,
        position: "CB",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/Goldie/GoldieMixOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "GoldieMix",
        name: "GOLDIE LEMON",
        version: "Mix",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Goldie/GoldieMix.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "GoldieMochi",
        name: "GOLDIE LEMON",
        version: "Mochi",
        rarity: "Especial",
        rating: 90,
        position: "CB",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/Goldie/GoldieMochi.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "GoldieMixDrag",
        name: "GOLDIE LEMON",
        version: "MixDrag",
        rarity: "Especial",
        rating: 91,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Goldie/GoldieMixDrag.png",
        background: "assets/Cartas/Chicle.png"
    },
    {
        id: "GoldieTri",
        name: "GOLDIE LEMON",
        version: "Tri",
        rarity: "Especial",
        rating: 92,
        position: "CB",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/Goldie/GoldieTri.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "GoldieArmor",
        name: "GOLDIE LEMON",
        version: "Armor",
        rarity: "Especial",
        rating: 95,
        position: "CB",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/Goldie/GoldieArmor.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "GoldieMixAma",
        name: "GOLDIE LEMON",
        version: "MixAma",
        rarity: "Especial",
        rating: 94,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Goldie/GoldieMixAma.png",
        background: "assets/Cartas/Trophy.png"
    }
];
