const inazumaKidsCards = [
    {
        id: "HermanMullerOro",
        name: "HERMAN MULLER",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/InazumaKids/HermanMullerOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "HermanMuller",
        name: "HERMAN MULLER",
        version: "Raimon",
        rarity: "Especial",
        rating: 80,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/InazumaKids/HermanMuller.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "KethClaus",
        name: "KEITH CLAUS",
        version: "Plata",
        rarity: "Plata",
        rating: 75,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/InazumaKids/KethClaus.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "RobertSilver",
        name: "ROBERT SILVER",
        version: "Plata",
        rarity: "Plata",
        rating: 73,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/InazumaKids/RobertSilver.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "IzzyIsland",
        name: "IZZY ISLAND",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/InazumaKids/IzzyIsland.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "SothernNewman",
        name: "SOTHERN NEWMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/InazumaKids/SothernNewman.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "IrwinHall",
        name: "IRWIN HALL",
        version: "Plata",
        rarity: "Plata",
        rating: 74,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/InazumaKids/IrwinHall.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "TaylorHiggins",
        name: "TAYLOR HIGGINS",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "RM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/InazumaKids/TaylorHiggins.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "JamieCoolOro",
        name: "JAMIE COOL",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "LM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/InazumaKids/JamieCoolOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "JamieCool",
        name: "JAMIE COOL",
        version: "Raimon",
        rarity: "Especial",
        rating: 81,
        position: "LM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/InazumaKids/JamieCool.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "HansRandall",
        name: "HANS RANDALL",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/InazumaKids/HansRandall.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MichaelRiverside",
        name: "MICHAEL RIVERSIDE",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/InazumaKids/MichaelRiverside.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MaddieMoonlightOro",
        name: "MADDIE MOONLIGHT",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/InazumaKids/MaddieMoonlightOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MaddieMoonlight",
        name: "MADDIE MOONLIGHT",
        version: "Raimon",
        rarity: "Especial",
        rating: 82,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/InazumaKids/MaddieMoonlight.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "BartGrantham",
        name: "BART GRANTHAM",
        version: "Plata",
        rarity: "Plata",
        rating: 75,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/InazumaKids/BartGrantham.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "KarlBlue",
        name: "KARL BLUE",
        version: "Plata",
        rarity: "Plata",
        rating: 73,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/InazumaKids/KarlBlue.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "TheakstonPlank",
        name: "THEAKSTON PLANK",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/InazumaKids/TheakstonPlank.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "KenCake",
        name: "KEN CAKE",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/InazumaKids/KenCake.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MitchGrumble",
        name: "MITCH GRUMBLE",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/InazumaKids/MitchGrumble.png",
        background: "assets/Cartas/Oro.png"
    }
];
