// database/internacional_cards.js
const internacionalCards = [
    {"id":"martino_leone_oro","name":"MARTINO LEONE","version":"Oro","rarity":"Oro","rating":83,"position":"GK","league":"Serie A","nationFlag":"https://flagcdn.com/w40/it.png","teamIcon":"teams/Torino.png","image":"assets/characters/Internacional/Martino Leone.png","background":"assets/Cartas/Oro.png"},
    {"id":"jenny_okutba_oro","name":"JENNY OKUTBA","version":"Oro","rarity":"Oro","rating":81,"position":"CB","league":"Premier League","nationFlag":"https://flagcdn.com/w40/ng.png","teamIcon":"teams/Everton.png","image":"assets/characters/Internacional/Jenny Okutba.png","background":"assets/Cartas/Oro.png"},
    {"id":"gigy_maharaja_oro","name":"GIGY MAHARAJA","version":"Oro","rarity":"Oro","rating":80,"position":"CB","league":"Premier League","nationFlag":"https://flagcdn.com/w40/in.png","teamIcon":"teams/AstonVilla.png","image":"assets/characters/Internacional/Gigy Maharaja.png","background":"assets/Cartas/Oro.png"},
    {"id":"robart_anderson_oro","name":"ROBART ANDERSON","version":"Oro","rarity":"Oro","rating":81,"position":"CM","league":"Scottish Premiership","nationFlag":"https://flagcdn.com/w40/gb-sct.png","teamIcon":"teams/Celtic.png","image":"assets/characters/Internacional/Robart Anderson.png","background":"assets/Cartas/Oro.png"},
    {"id":"maribelle_flanmir_oro","name":"MARIBELLE FLANMIR","version":"Oro","rarity":"Oro","rating":79,"position":"CAM","league":"Ligue 1","nationFlag":"https://flagcdn.com/w40/be.png","teamIcon":"teams/Lyon.png","image":"assets/characters/Internacional/Maribelle Flanmir.png","background":"assets/Cartas/Oro.png"},
    {"id":"toya_yamanouchi_oro","name":"TOYA YAMANOUCHI","version":"Oro","rarity":"Oro","rating":84,"position":"CM","league":"Bundesliga","nationFlag":"https://flagcdn.com/w40/jp.png","teamIcon":"teams/Frankfurt.png","image":"assets/characters/Internacional/Toyo Yamanouchi.png","background":"assets/Cartas/Oro.png"},
    {"id":"ming_chow_oro","name":"MING CHOW","version":"Oro","rarity":"Oro","rating":80,"position":"RM","league":"La Liga","nationFlag":"https://flagcdn.com/w40/cn.png","teamIcon":"teams/RCDEspanyol.png","image":"assets/characters/Internacional/Ming Chow.png","background":"assets/Cartas/Oro.png"},
    {"id":"judie_cassios_oro","name":"JUDIE CASSIOS","version":"Oro","rarity":"Oro","rating":78,"position":"RB","league":"Serie A","nationFlag":"https://flagcdn.com/w40/gr.png","teamIcon":"teams/Bologna.png","image":"assets/characters/Internacional/Judie Cassios.png","background":"assets/Cartas/Oro.png"},
    {"id":"joey_beat_oro","name":"JOEY BEAT","version":"Oro","rarity":"Oro","rating":81,"position":"ST","league":"Premier League","nationFlag":"https://flagcdn.com/w40/gb-eng.png","teamIcon":"teams/WestHam.png","image":"assets/characters/Internacional/Joey Beat.png","background":"assets/Cartas/Oro.png"},
    {"id":"kai_yoshizaki_oro","name":"KAI YOSHIZAKI","version":"Oro","rarity":"Oro","rating":83,"position":"ST","league":"Bundesliga","nationFlag":"https://flagcdn.com/w40/jp.png","teamIcon":"teams/Freiburg.png","image":"assets/characters/Internacional/Kai Yoshizaki.png","background":"assets/Cartas/Oro.png"},
    {"id":"sikuvot_shivan_oro","name":"SIKUVOT SHIVAN","version":"Oro","rarity":"Oro","rating":80,"position":"ST","league":"Liga Portugal","nationFlag":"https://flagcdn.com/w40/th.png","teamIcon":"teams/Sporting.png","image":"assets/characters/Internacional/Sikuvot Shivan.png","background":"assets/Cartas/Oro.png"},
    {"id":"olson_carchis_oro","name":"OLSON CARCHIS","version":"Oro","rarity":"Oro","rating":79,"position":"ST","league":"Bundesliga","nationFlag":"https://flagcdn.com/w40/se.png","teamIcon":"teams/WerderBremen.png","image":"assets/characters/Internacional/Olson Carchis.png","background":"assets/Cartas/Oro.png"},
    {"id":"mengmeng_wang_oro","name":"MENGMENG WANG","version":"Oro","rarity":"Oro","rating":80,"position":"CAM","league":"Bundesliga","nationFlag":"https://flagcdn.com/w40/cn.png","teamIcon":"teams/Wolfsburg.png","image":"assets/characters/Internacional/Mengmeng Wang.png","background":"assets/Cartas/Oro.png"},
    {"id":"kain_vijet_oro","name":"KAIN VIJET","version":"Oro","rarity":"Oro","rating":79,"position":"LB","league":"Serie A","nationFlag":"https://flagcdn.com/w40/hr.png","teamIcon":"teams/Atalanta.png","image":"assets/characters/Internacional/Kain Vijet.png","background":"assets/Cartas/Oro.png"},
    {"id":"kaos_dao_oro","name":"KAOS DAO","version":"Oro","rarity":"Oro","rating":78,"position":"GK","league":"La Liga","nationFlag":"https://flagcdn.com/w40/vn.png","teamIcon":"teams/Levante.png","image":"assets/characters/Internacional/Kaos Dao.png","background":"assets/Cartas/Oro.png"},
    {"id":"edmond_pias_oro","name":"EDMOND PIAS","version":"Oro","rarity":"Oro","rating":80,"position":"CB","league":"Eredivisie","nationFlag":"https://flagcdn.com/w40/pt.png","teamIcon":"teams/Ayax.png","image":"assets/characters/Internacional/Edmond Pias.png","background":"assets/Cartas/Oro.png"}
];
