const isagiCards = [
    {
        id: "isagi_oro",
        name: "YOICHI ISAGI",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "isagi_blue",
        name: "YOICHI ISAGI",
        version: "Flashback",
        rarity: "Especial",
        rating: 87,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiBlue.png",
        background: "assets/Cartas/Flashback.png"
    },
    {
        id: "isagi_bastard",
        name: "YOICHI ISAGI",
        version: "Bastard",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/Isagi.png",
        background: "assets/Cartas/Bastard.png"
    },
    {
        id: "isagi_ver",
        name: "YOICHI ISAGI",
        version: "Radioactiva",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiVer.png",
        background: "assets/Cartas/Radioactiva.png"
    },
    {
        id: "isagi_ness",
        name: "YOICHI ISAGI",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiNess.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "isagi_cel",
        name: "YOICHI ISAGI",
        version: "FutureStar",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiCel.png",
        background: "assets/Cartas/FutureStar.png"
    },
    {
        id: "isagi_dual",
        name: "YOICHI ISAGI",
        version: "Trophy",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiDual.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "isagi_kai",
        name: "YOICHI ISAGI",
        version: "RojiAzul",
        rarity: "Especial",
        rating: 93,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiKai.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "isagi_gun",
        name: "YOICHI ISAGI",
        version: "Tots",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiGun.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "isagi_luck",
        name: "YOICHI ISAGI",
        version: "Toty",
        rarity: "Especial",
        rating: 95,
        position: "ST",
        secondaryPositions: ["CF", "CAM", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Isagi/IsagiLuck.png",
        background: "assets/Cartas/Toty.png"
    }
];
