const jpCards = [
    {
        id: "JPOro",
        name: "JEAN-PIERRE LAPIN",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        secondaryPositions: ["LB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/JP/JPOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "JPMixOro",
        name: "JEAN-PIERRE LAPIN",
        version: "MixOro",
        rarity: "Oro",
        rating: 86,
        position: "GK",
        secondaryPositions: ["LB"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/JP/JPMixOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "JPSalto",
        name: "JEAN-PIERRE LAPIN",
        version: "Salto",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        secondaryPositions: ["LB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/JP/JPSalto.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "JP",
        name: "JEAN-PIERRE LAPIN",
        version: "Centurion",
        rarity: "Especial",
        rating: 88,
        position: "GK",
        secondaryPositions: ["LB"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/JP/JP.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "JPEsp",
        name: "JEAN-PIERRE LAPIN",
        version: "Esp",
        rarity: "Especial",
        rating: 89,
        position: "GK",
        secondaryPositions: ["LB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/JP/JPEsp.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "JPEsp2",
        name: "JEAN-PIERRE LAPIN",
        version: "Esp2",
        rarity: "Especial",
        rating: 90,
        position: "GK",
        secondaryPositions: ["LB"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/JP/JPEsp2.png",
        background: "assets/Cartas/Radioactiva.png"
    },
    {
        id: "JPMix2",
        name: "JEAN-PIERRE LAPIN",
        version: "Mix2",
        rarity: "Especial",
        rating: 91,
        position: "LB",
        secondaryPositions: ["GK"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/JP/JPMix2.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "JPMix",
        name: "JEAN-PIERRE LAPIN",
        version: "Mix",
        rarity: "Especial",
        rating: 92,
        position: "GK",
        secondaryPositions: ["LB"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/JP/JPMix.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "JPPrime",
        name: "JEAN-PIERRE LAPIN",
        version: "Prime",
        rarity: "Especial",
        rating: 94,
        position: "GK",
        secondaryPositions: ["LB"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/JP/JPPrime.png",
        background: "assets/Cartas/Tots.png"
    }
];
