// database/jude_sharp_cards.js
const judeSharpCards = [
    {
        id: "jude_oro",
        name: "JUDE SHARP",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Royal.png",
        image: "assets/characters/Jude/JudeOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jude_espejismo",
        name: "JUDE SHARP",
        version: "Espejismo",
        rarity: "Especial",
        rating: 87,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Jude/JudeEspejismo.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "jude_ruptura",
        name: "JUDE SHARP",
        version: "Ruptura",
        rarity: "Trueno",
        rating: 91,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Jude/JudeRuptura.png",
        background: "assets/Cartas/Trueno.png"
    },
    {
        id: "jude_polaris_oro",
        name: "JUDE SHARP",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Jude/JudePolarisOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jude_polaris_if",
        name: "JUDE SHARP",
        version: "Polaris",
        rarity: "Especial",
        rating: 90,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Jude/JudePolaris.png",
        background: "assets/Cartas/If.png"
    },
    {
        id: "jude_pin",
        name: "JUDE SHARP",
        version: "Future Star",
        rarity: "Especial",
        rating: 92,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Jude/JudePin.png",
        background: "assets/Cartas/FutureStar.png"
    },
    {
        id: "polaris_larry",
        name: "LARRY LYRE",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CB",
        secondaryPositions: ["GK"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/LarryLyre.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "polaris_cygnus",
        name: "CYGNUS STARKEY",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "LB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/CygnusStarkey.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "polaris_ari",
        name: "ARI ZIMMERMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "RB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/AriZimmerman.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "polaris_jimmy",
        name: "JIMMY NIGH",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CDM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/JimmyNigh.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "polaris_caesar",
        name: "CAESAR PIKE",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/CaesarPike.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "polaris_oliver",
        name: "OLIVER GOLIGHTLY",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CAM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/OliverGolightly.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "polaris_holt",
        name: "HOLT NORTHAM",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "CB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/HoltNortham.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "polaris_braveon",
        name: "BRAVEON HALVORS",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "ST",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/BraveonHalvors.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "polaris_konrad",
        name: "KONRAD HARDIN",
        version: "Oro",
        rarity: "Oro",
        rating: 72,
        position: "GK",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/KonradHardin.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "polaris_aren",
        name: "AREN YARROW",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "RM",
        secondaryPositions: ["LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/ArenYarrow.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "polaris_oscar_oro",
        name: "OSCAR PIO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "LW",
        secondaryPositions: ["CAM", "RW", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/OscarPioOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "polaris_oscar_if",
        name: "OSCAR PIO",
        version: "If",
        rarity: "Especial",
        rating: 84,
        position: "LW",
        secondaryPositions: ["CAM", "RW", "LM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/OscarPio.png",
        background: "assets/Cartas/If.png"
    },
    {
        id: "polaris_mickey_oro",
        name: "MICKEY WAY",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "GK",
        secondaryPositions: ["CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/MickeyWayOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "polaris_mickey_if",
        name: "MICKEY WAY",
        version: "If",
        rarity: "Especial",
        rating: 84,
        position: "GK",
        secondaryPositions: ["CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/MickeyWay.png",
        background: "assets/Cartas/If.png"
    },
    {
        id: "polaris_eddy_oro",
        name: "EDDY O'RYAN",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "RW",
        secondaryPositions: ["CAM", "LW", "RM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/EddyO'RyanOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "polaris_eddy_if",
        name: "EDDY O'RYAN",
        version: "If",
        rarity: "Especial",
        rating: 84,
        position: "RW",
        secondaryPositions: ["CAM", "LW", "RM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/EddyO'Ryan.png",
        background: "assets/Cartas/If.png"
    },
    {
        id: "polaris_acker_oro",
        name: "ACKER REESE",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        secondaryPositions: ["CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/AckerReeseOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "polaris_acker_if",
        name: "ACKER REESE",
        version: "If",
        rarity: "Especial",
        rating: 86,
        position: "CB",
        secondaryPositions: ["CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/AckerReesedf.png",
        background: "assets/Cartas/If.png"
    },
    {
        id: "polaris_acker_hielo",
        name: "ACKER REESE",
        version: "Hielo",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        secondaryPositions: ["CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/AckerReeseEnt.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "polaris_acker_manshine",
        name: "ACKER REESE",
        version: "Manshine",
        rarity: "Especial",
        rating: 89,
        position: "CB",
        secondaryPositions: ["CDM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/Polaris/AckerReeseAir.png",
        background: "assets/Cartas/Manshine.png"
    },
    {
        id: "polaris_acker_tots",
        name: "ACKER REESE",
        version: "Tots",
        rarity: "Tots",
        rating: 91,
        position: "CB",
        secondaryPositions: ["CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/Polaris/AckerReese.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "polaris_acker_toty",
        name: "ACKER REESE",
        version: "Toty",
        rarity: "Toty",
        rating: 92,
        position: "CB",
        secondaryPositions: ["CDM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/Polaris/AckerReesePrime.png",
        background: "assets/Cartas/Toty.png"
    },
    {
        id: "elliot_ember_oro",
        name: "ELLIOT EMBER",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/ElliotEmber/ElliotEmberOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "elliot_ember_if",
        name: "ELLIOT EMBER",
        version: "If",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/ElliotEmber/ElliotEmber.png",
        background: "assets/Cartas/If.png"
    },
    {
        id: "elliot_ember_morado",
        name: "ELLIOT EMBER",
        version: "Morado",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/ElliotEmber/ElliotEmberDEm.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "elliot_ember_trueno",
        name: "ELLIOT EMBER",
        version: "Trueno",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/ElliotEmber/ElliotEmberLanza.png",
        background: "assets/Cartas/Trueno.png"
    },
    {
        id: "elliot_ember_trophy",
        name: "ELLIOT EMBER",
        version: "Trophy",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: [],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/ElliotEmber/ElliotEmberDor.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "elliot_ember_milan",
        name: "ELLIOT EMBER",
        version: "Milan",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        secondaryPositions: [],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/ElliotEmber/ElliotEmber2.png",
        background: "assets/Cartas/Milan.png"
    },
    {
        id: "elliot_ember_roja",
        name: "ELLIOT EMBER",
        version: "Roja",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/ElliotEmber/ElliotEmberPingDor.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "elliot_ember_rulebreaker",
        name: "ELLIOT EMBER",
        version: "Trailblazer",
        rarity: "Especial",
        rating: 93,
        position: "ST",
        secondaryPositions: [],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/ElliotEmber/ElliotEmberTiburao.png",
        background: "assets/Cartas/Trailblaze.png"
    },
    {
        id: "elliot_ember_futurestar",
        name: "ELLIOT EMBER",
        version: "Future Star",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Polaris.png",
        image: "assets/characters/ElliotEmber/ElliotEmberTiburao2.png",
        background: "assets/Cartas/FutureStar.png"
    },
    {
        id: "jude_legen_oro",
        name: "JUDE SHARP",
        version: "Oro",
        rarity: "Oro",
        rating: 90,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Jude/JudeLegenOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jude_legen",
        name: "JUDE SHARP",
        version: "Icono",
        rarity: "Icono",
        rating: 95,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Jude/JudeLegen.png",
        background: "assets/Cartas/Icono.png"
    },
    {
        id: "jude_toty",
        name: "JUDE SHARP",
        version: "Toty",
        rarity: "Toty",
        rating: 93,
        position: "CAM",
        secondaryPositions: ["CM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Jude/JudeCross.png",
        background: "assets/Cartas/Toty.png"
    },
    {
        id: "juleb",
        name: "JULEB",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        secondaryPositions: ["CAM"],
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/Jude/Juleb.png",
        background: "assets/Cartas/Oro.png"
    }
];

// ==========================================
// NATHAN
// ==========================================
