const legendsUpdateCards = [
    {
        id: "victor_sanchez_oro",
        name: "VICTOR SANCHEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "RM",
        secondaryPositions: ["LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/España/Victor Sanchez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "albert_luque_oro",
        name: "ALBERT LUQUE",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LW",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/España/Albert Luque.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ricardo_lopez_oro",
        name: "RICARDO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Racing.png",
        image: "assets/characters/España/RicardoLopezOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ricardo_lopez_espana",
        name: "RICARDO",
        version: "Espana",
        rarity: "Especial",
        rating: 85,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/es.png",
        teamIcon: "teams/Racing.png",
        image: "assets/characters/España/RicardoLopez.png",
        background: "assets/Cartas/Espana.png"
    },
    {
        id: "mauro_silva_oro",
        name: "MAURO SILVA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/br.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/Brasil/Mauro Silva.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "batistuta_oro",
        name: "BATISTUTA",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Fiorentina.png",
        image: "assets/characters/Argentina/Batistuta.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "crespo_oro",
        name: "CRESPO",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Argentina/Crespo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "veron_oro",
        name: "VERON",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Lazio.png",
        image: "assets/characters/Argentina/Veron.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kages_oro",
        name: "KAGES",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/gr.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/Grecia/KagesOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kages_bundes",
        name: "KAGES",
        version: "Bundes",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/gr.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/Grecia/Kages.png",
        background: "assets/Cartas/Bundes.png"
    }
];
