const luzSomCards = [
    {
        id: "BailongOro",
        name: "BAILONG",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BailongLuz",
        name: "BAILONG",
        version: "Real",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongLuz.png",
        background: "assets/Cartas/Real.png"
    },
    {
        id: "BailongFlash",
        name: "BAILONG",
        version: "Flashback",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongFlash.png",
        background: "assets/Cartas/FlashBack.png"
    },
    {
        id: "BailongEsp",
        name: "BAILONG",
        version: "Centurion",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongEsp.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "BailongTez",
        name: "BAILONG",
        version: "Trueno",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongTez.png",
        background: "assets/Cartas/Trueno.png"
    },
    {
        id: "BailongDor",
        name: "BAILONG",
        version: "Radioactiva",
        rarity: "Especial",
        rating: 93,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongDor.png",
        background: "assets/Cartas/Radioactiva.png"
    },
    {
        id: "BailongArm",
        name: "BAILONG",
        version: "Trophy",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongArm.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "BailongArturo",
        name: "BAILONG",
        version: "Tots",
        rarity: "Especial",
        rating: 95,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongArturo.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "BailongPrime",
        name: "BAILONG",
        version: "Toty",
        rarity: "Especial",
        rating: 96,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/LuzSom/BailongPrime.png",
        background: "assets/Cartas/Toty.png"
    },
    {
        id: "TezcatOro",
        name: "TEZCAT",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/LuzSom/TezcatOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "TezcatCen",
        name: "TEZCAT",
        version: "Morado",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/LuzSom/TezcatCen.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "TezcatFlash",
        name: "TEZCAT",
        version: "Flashback",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/LuzSom/TezcatFlash.png",
        background: "assets/Cartas/FlashBack.png"
    },
    {
        id: "TezcatBailong",
        name: "TEZCAT",
        version: "Trueno",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/LuzSom/TezcatBailong.png",
        background: "assets/Cartas/Trueno.png"
    },
    {
        id: "Tezcat",
        name: "TEZCAT",
        version: "Rulebreaker",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/LuzSom/Tezcat.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "TezcatEsp",
        name: "TEZCAT",
        version: "Mordiscos",
        rarity: "Especial",
        rating: 93,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/LuzSom/TezcatEsp.png",
        background: "assets/Cartas/Mordiscos.png"
    },
    {
        id: "TezArturo",
        name: "TEZCAT",
        version: "Tots",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/LuzSom/TezArturo.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "TezEspArturo",
        name: "TEZCAT",
        version: "Toty",
        rarity: "Especial",
        rating: 95,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW", "LM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/LuzSom/TezEspArturo.png",
        background: "assets/Cartas/Toty.png"
    }
];
