// database/mexico_cards.js
const mexicoCards = [
    {
        id: "alvez_oro",
        name: "ALVEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CAM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Mexico/AlvezOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "garcia_oro",
        name: "GARCIA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/Mexico/GarciaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "lopez_oro",
        name: "LOPEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Mexico/LopezOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ramirez_oro",
        name: "RAMIREZ",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/Mexico/RamirezOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "suarez_oro",
        name: "SUAREZ",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LW",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Mexico/SuarezOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "zaragoza_oro",
        name: "ZARAGOZA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/Mexico/ZaragozaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "espadas_oro",
        name: "ESPADAS",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Mexico/EspadasOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "espadas_neutro",
        name: "ESPADAS",
        version: "Rulebreaker",
        rarity: "Especial",
        rating: 89,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Mexico/EspadasNeutro.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "espadas_ata",
        name: "ESPADAS",
        version: "Manshine",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Mexico/EspadasAta.png",
        background: "assets/Cartas/Manshine.png"
    },
    {
        id: "espadas_def",
        name: "ESPADAS",
        version: "Trueno",
        rarity: "Trueno",
        rating: 88,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Mexico/EspadasDef.png",
        background: "assets/Cartas/Trueno.png"
    },
    {
        id: "espadas_dl",
        name: "ESPADAS",
        version: "Shapesifter",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Mexico/EspadasDL.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "espadas_especial",
        name: "ESPADAS",
        version: "Especial",
        rarity: "Especial",
        rating: 91,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Mexico/EspadasEspecial.png",
        background: "assets/backgrounds/Fondo_Espadas.png"
    },
    {
        id: "alvez_shapesifters",
        name: "ALVEZ",
        version: "Shapesifter",
        rarity: "Especial",
        rating: 84,
        position: "CAM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Mexico/Alvez.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "garcia_shapesifters",
        name: "GARCIA",
        version: "Shapesifter",
        rarity: "Especial",
        rating: 86,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/Mexico/Garcia.png",
        background: "assets/Cartas/Shapesifters.png"
    }
];

// ==========================================
// TAILANDIA
// ==========================================
