// database/nathan_cards.js
const nathanCards = [
    {
        id: "igorschneider_alemania",
        name: "IGOR SCHNEIDER",
        version: "Alemania",
        rarity: "Especial",
        rating: 83,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/IgorSchneider.png",
        background: "assets/Cartas/Alemania.png"
    },
{
        id: "jito_oro",
        name: "JITO",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/Jito/JitoOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "jito_prime",
        name: "JITO",
        version: "Tots",
        rarity: "Tots",
        rating: 89,
        position: "CB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/Jito/JitoPrime.png",
        background: "assets/Cartas/Tots.png"
    },
{
        id: "jito_mun",
        name: "JITO",
        version: "Mundial",
        rarity: "Especial",
        rating: 91,
        position: "CB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/Jito/JitoMun.png",
        background: "assets/backgrounds/Fondo_Jito.png"
    },
{
        id: "masao_oro",
        name: "MASAO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Tachis/MasaoOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "masao_hielo",
        name: "MASAO",
        version: "Hielo",
        rarity: "Hielo",
        rating: 86,
        position: "RM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Tachis/Masao1.png",
        background: "assets/Cartas/Hielo.png"
    },
{
        id: "masao_flashback",
        name: "MASAO",
        version: "Flashback",
        rarity: "Especial",
        rating: 89,
        position: "RM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Tachis/Masao2.png",
        background: "assets/Cartas/Flashback.png"
    },
{
        id: "kazuo_oro",
        name: "KAZUO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "LM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Tachis/KasuoOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "kazuo_hielo",
        name: "KAZUO",
        version: "Hielo",
        rarity: "Hielo",
        rating: 86,
        position: "LM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Tachis/Kazuo1.png",
        background: "assets/Cartas/Hielo.png"
    },
{
        id: "kazuo_flashback",
        name: "KAZUO",
        version: "Flashback",
        rarity: "Especial",
        rating: 89,
        position: "LM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Tachis/Kazuo2.png",
        background: "assets/Cartas/Flashback.png"
    },
{
        id: "ishizaki_oro",
        name: "ISHIZAKI",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Ishizaki/IshizakiOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "ishizaki_inter",
        name: "ISHIZAKI",
        version: "Inter",
        rarity: "Especial",
        rating: 87,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Ishizaki/Ishizaki.png",
        background: "assets/Cartas/Inter.png"
    },
{
        id: "ishizaki_mun",
        name: "ISHIZAKI",
        version: "Trophy",
        rarity: "Especial",
        rating: 89,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Ishizaki/IshizakiMun.png",
        background: "assets/Cartas/Trophy.png"
    },
{
        id: "nitta_oro",
        name: "NITTA",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Nitta/ShunNittaOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "nitta_futbirthday",
        name: "NITTA",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 87,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Nitta/ShunNitta.png",
        background: "assets/Cartas/FutBirthday.png"
    },
{
        id: "nitta_toty",
        name: "NITTA",
        version: "Toty",
        rarity: "Toty",
        rating: 89,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Nitta/ShunNittaG.png",
        background: "assets/Cartas/Toty.png"
    },
{
        id: "nitta_dormund",
        name: "NITTA",
        version: "Dortmund",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Nitta/ShunNittaDor.png",
        background: "assets/Cartas/Dormund.png"
    },
{
        id: "akai_oro",
        name: "AKAI",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Akai/AkaiOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "akai_cabras",
        name: "AKAI",
        version: "Cabras",
        rarity: "Especial",
        rating: 87,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Akai/Akai.png",
        background: "assets/Cartas/Cabras.png"
    },
{
        id: "akai_toty",
        name: "AKAI",
        version: "Toty",
        rarity: "Toty",
        rating: 90,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Akai/AkaiPrime.png",
        background: "assets/Cartas/Toty.png"
    },
{
        id: "morisaki_oro",
        name: "MORISAKI",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Morisaki/MorisakiOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "morisaki_naranja",
        name: "MORISAKI",
        version: "Naranja",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Morisaki/Morisaki.png",
        background: "assets/Cartas/Naranja.png"
    },
{
        id: "ina_xavier_morada",
        name: "XAVIER",
        version: "Génesis",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Xavier/Xavier.png",
        background: "assets/Cartas/Morado.png"
    },
{
        id: "ina_xavier_toty",
        name: "XAVIER",
        version: "Tottenham",
        rarity: "Toty",
        rating: 93,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Xavier/XavierPrime.png",
        background: "assets/Cartas/Toty.png"
    },
{
        id: "ina_xavier_leg_oro",
        name: "XAVIER",
        version: "Tottenham",
        rarity: "Normal",
        rating: 90,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Xavier/XavierLegOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "ina_xavier_leg",
        name: "XAVIER",
        version: "Tottenham",
        rarity: "Icono",
        rating: 94,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Xavier/XavierLeg.png",
        background: "assets/Cartas/Icono.png"
    },
{
        id: "sonny_oro",
        name: "SONNY WRIGHT",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        background: "assets/Cartas/Oro.png",
        image: "assets/characters/Sonny/SonnyOro.png"
    },
{
        id: "sonny_if",
        name: "SONNY WRIGHT",
        version: "If",
        rarity: "If",
        rating: 87,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        background: "assets/Cartas/If.png",
        image: "assets/characters/Sonny/SonnyIf.png"
    },
{
        id: "sonny_flashback",
        name: "SONNY WRIGHT",
        version: "Flashback",
        rarity: "Flashback",
        rating: 89,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        background: "assets/Cartas/Flashback.png",
        image: "assets/characters/Sonny/SonnyMang.png"
    },
{
        id: "sonny_trueno",
        name: "SONNY WRIGHT",
        version: "Trueno",
        rarity: "Trueno",
        rating: 91,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        background: "assets/Cartas/Trueno.png",
        image: "assets/characters/Sonny/SonnyTrueno.png"
    },
{
        id: "sonny_tots",
        name: "SONNY WRIGHT",
        version: "Tots",
        rarity: "Tots",
        rating: 93,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        background: "assets/Cartas/Tots.png",
        image: "assets/characters/Sonny/SonnyPaj.png"
    },
{
        id: "sonny_centurion",
        name: "SONNY WRIGHT",
        version: "Centurion",
        rarity: "Centurion",
        rating: 90,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Superliga Europea",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Benfica.png",
        background: "assets/Cartas/Centurion.png",
        image: "assets/characters/Sonny/SonnyFuego.png"
    },
{
        id: "sonny_trophy",
        name: "SONNY WRIGHT",
        version: "Trophy",
        rarity: "Trophy",
        rating: 92,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Superliga Europea",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Benfica.png",
        background: "assets/Cartas/Trophy.png",
        image: "assets/characters/Sonny/SonnyPrime.png"
    },
{
        id: "xavier_schiller_oro",
        name: "XAVIER SCHILLER",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "ST",
        secondaryPositions: ["CF", "RW"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        background: "assets/Cartas/Oro.png",
        image: "assets/characters/Xavier/XavierSchillerOro.png"
    },
{
        id: "xavier_schiller_if",
        name: "XAVIER SCHILLER",
        version: "If",
        rarity: "If",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF", "RW"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        background: "assets/Cartas/If.png",
        image: "assets/characters/Xavier/XavierSchillerIf.png"
    },
{
        id: "xavier_schiller_tro",
        name: "XAVIER SCHILLER",
        version: "Centurion",
        rarity: "Centurion",
        rating: 90,
        position: "ST",
        secondaryPositions: ["CF", "RW"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        background: "assets/Cartas/Centurion.png",
        image: "assets/characters/Xavier/XavierSchillerTro.png"
    },
{
        id: "xavier_schiller_rosa",
        name: "XAVIER SCHILLER",
        version: "Rosa",
        rarity: "Rosa",
        rating: 91,
        position: "ST",
        secondaryPositions: ["CF", "RW"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        background: "assets/Cartas/Rosa.png",
        image: "assets/characters/Xavier/XavierSchillerRosa.png"
    },
{
        id: "xavier_schiller_fuego",
        name: "XAVIER SCHILLER",
        version: "FutBirthday",
        rarity: "FutBirthday",
        rating: 92,
        position: "ST",
        secondaryPositions: ["CF", "RW"],
        league: "Premier League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Liverpool.png",
        background: "assets/Cartas/FutBirthday.png",
        image: "assets/characters/Xavier/XavierSchillerFuego.png"
    },
{
        id: "xavier_schiller_prime2",
        name: "XAVIER SCHILLER",
        version: "Toty",
        rarity: "Toty",
        rating: 93,
        position: "ST",
        secondaryPositions: ["CF", "RW"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        background: "assets/Cartas/Toty.png",
        image: "assets/characters/Xavier/XavierSchillerPrime2.png"
    },
{
        id: "xavier_schiller_prime",
        name: "XAVIER SCHILLER",
        version: "Joker",
        rarity: "Joker",
        rating: 94,
        position: "ST",
        secondaryPositions: ["CF", "RW"],
        league: "Premier League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Liverpool.png",
        background: "assets/Cartas/Joker.png",
        image: "assets/characters/Xavier/XavierSchillerPrime.png"
    },
{
        id: "adriano_oro",
        name: "ADRIANO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        secondaryPositions: ["CF"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        background: "assets/Cartas/Oro.png",
        image: "assets/characters/Adriano/AdrianoOro.png"
    },
{
        id: "adriano_brasil",
        name: "ADRIANO",
        version: "Brasil",
        rarity: "Brasil",
        rating: 87,
        position: "ST",
        secondaryPositions: ["CF"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        background: "assets/Cartas/Brasil.png",
        image: "assets/characters/Adriano/AdrianoLem.png"
    },
{
        id: "adriano_inter",
        name: "ADRIANO",
        version: "Inter",
        rarity: "Inter",
        rating: 88,
        position: "ST",
        secondaryPositions: ["CF"],
        league: "Serie A",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Inter.png",
        background: "assets/Cartas/Inter.png",
        image: "assets/characters/Adriano/AdrianoJp.png"
    },
{
        id: "adriano_tots",
        name: "ADRIANO",
        version: "Tots",
        rarity: "Tots",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF"],
        league: "J-League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        background: "assets/Cartas/Tots.png",
        image: "assets/characters/Adriano/AdrianoIn.png"
    },
{
        id: "lucas_oro",
        name: "LUCAS STAR",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Premier League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        background: "assets/Cartas/Oro.png",
        image: "assets/characters/Lucas/LucasOro.png"
    },
{
        id: "lucas_if",
        name: "LUCAS STAR",
        version: "If",
        rarity: "If",
        rating: 88,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Premier League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        background: "assets/Cartas/If.png",
        image: "assets/characters/Lucas/LucasIF.png"
    },
{
        id: "lucas_azul",
        name: "LUCAS STAR",
        version: "Especial",
        rarity: "Especial",
        rating: 89,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Premier League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        background: "assets/Cartas/Azul.png",
        image: "assets/characters/Lucas/LucasSp.png"
    },
{
        id: "lucas_hielo",
        name: "LUCAS STAR",
        version: "Hielo",
        rarity: "Hielo",
        rating: 90,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Premier League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        background: "assets/Cartas/Hielo.png",
        image: "assets/characters/Lucas/LusStar.png"
    },
{
        id: "lucas_cabras",
        name: "LUCAS STAR",
        version: "Cabras",
        rarity: "Cabras",
        rating: 91,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Premier League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        background: "assets/Cartas/Cabras.png",
        image: "assets/characters/Lucas/LucasReg.png"
    },
{
        id: "lucas_toty",
        name: "LUCAS STAR",
        version: "Toty",
        rarity: "Toty",
        rating: 93,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Premier League",
        nation: "Japón",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Chelsea.png",
        background: "assets/Cartas/Toty.png",
        image: "assets/characters/Lucas/LucasPrime.png"
    },
{
        id: "cabassos_oro",
        name: "CABASSOS",
        version: "Oro",
        rarity: "Oro",
        rating: 88,
        position: "CF",
        secondaryPositions: ["CM","CAM","ST"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Argentina/CabassosOro.png",
        background: "assets/Cartas/Oro.png"
    },
{
        id: "cabassos_futbirthday",
        name: "CABASSOS",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 92,
        position: "CF",
        secondaryPositions: ["CM","CAM","ST"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Argentina/Cabassos.png",
        background: "assets/Cartas/FutBirthday.png"
    },
{
        id: "cabassos_prime",
        name: "CABASSOS",
        version: "Rulebraker",
        rarity: "Especial",
        rating: 94,
        position: "CF",
        secondaryPositions: ["CM","CAM","ST"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ar.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Argentina/CabassosPrime.png",
        background: "assets/Cartas/Rulebraker.png"
    }
,
    {
        id: "agbim_brasil",
        name: "AGBIM",
        version: "Brasil",
        rarity: "Especial",
        rating: 81,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/ng.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Nigeria/AgbimOro.png",
        background: "assets/Cartas/Brasil.png"
    },
    {
        id: "sadiq_brasil",
        name: "SADIQ",
        version: "Brasil",
        rarity: "Especial",
        rating: 81,
        position: "CDM",
        secondaryPositions: ["CM"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ng.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/Nigeria/SadiqOro.png",
        background: "assets/Cartas/Brasil.png"
    },
    {
        id: "bello_brasil",
        name: "BELLO",
        version: "Brasil",
        rarity: "Especial",
        rating: 87,
        position: "RM",
        secondaryPositions: ["RW"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/ng.png",
        teamIcon: "teams/Benfica.png",
        image: "assets/characters/Nigeria/BelloOro.png",
        background: "assets/Cartas/Brasil.png"
    },
    {
        id: "obabona_brasil",
        name: "OBABONA",
        version: "Brasil",
        rarity: "Especial",
        rating: 87,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/ng.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Nigeria/ObabonaOro.png",
        background: "assets/Cartas/Brasil.png"
    }
,
    {
        id: "jimmywongfu_trueno",
        name: "JIMMY WONGFU",
        version: "Trueno",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/cn.png",
        teamIcon: "teams/Manshine.png",
        image: "assets/characters/China/JimmyWongfuTrueno.png",
        background: "assets/Cartas/Trueno.png"
    }
];


// ==========================================
// TECMO CHARACTERS
// ==========================================
