const ogreCards = [
    {
        id: "LarsLuceafarOro",
        name: "LARS LUCEAFAR",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/Ogre/LarsLuceafărOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "LarsLuceafarBL",
        name: "LARS LUCEAFAR",
        version: "Trophy",
        rarity: "Especial",
        rating: 89,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/Ogre/LarsLuceafărBL.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "LarsLuceafarElec",
        name: "LARS LUCEAFAR",
        version: "Tots",
        rarity: "Especial",
        rating: 92,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/Ogre/LarsLuceafărElec.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "BumpTrungus",
        name: "BUMP TRUNGUS",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/Ogre/BumpTrungus.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "LumpTrungus",
        name: "LUMP TRUNGUS",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        secondaryPositions: ["LB", "RB", "CDM"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/Ogre/LumpTrungus.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "RaddIscher",
        name: "RADD ISCHER",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LB",
        secondaryPositions: ["CB", "LWB", "RB"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Fiorentina.png",
        image: "assets/characters/Ogre/RaddIscher.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "EscavanMaliceOro",
        name: "ESCAVAN MALICE",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        secondaryPositions: ["CF", "LW", "RW", "CAM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Ogre/EscavanMaliceOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "EscavanMalice",
        name: "ESCAVAN MALICE",
        version: "Morado",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        secondaryPositions: ["CF", "LW", "RW", "CAM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Ogre/EscavanMalice.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "DrachenGunther",
        name: "DRACHEN GUNTHER",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "RM",
        secondaryPositions: ["LM", "RW", "CM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Ogre/DrachenGunther.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "JynxJenkins",
        name: "JYNX JENKINS",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RB",
        secondaryPositions: ["RWB", "CB", "LB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Racing.png",
        image: "assets/characters/Ogre/JynxJenkins.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "IchabodStark",
        name: "ICHABOD STARK",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/Ogre/IchabodStark.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "OniTriumvir",
        name: "ONI TRIUMVIR",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "LM",
        secondaryPositions: ["RM", "LW", "CM"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/Ogre/OniTriumvir.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MystralCallousOro",
        name: "MYSTRAL CALLOUS",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/Ogre/MystralCallousOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MystralCallous",
        name: "MYSTRAL CALLOUS",
        version: "Rojiazul",
        rarity: "Especial",
        rating: 87,
        position: "ST",
        secondaryPositions: ["CF", "RW", "LW"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/Ogre/MystralCallous.png",
        background: "assets/Cartas/Rojiazul.png"
    }
];
