// database/otros_francia_cards.js
const otrosFranciaCards = [
{
    id: "rogerpialat_oro",
    name: "ROGER PIALAT",
    version: "Oro",
    rarity: "Oro",
    rating: 78,
    position: "GK",
    league: "Superliga Europea",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Monaco.png",
    image: "assets/characters/Francia/RogerPialat.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "pierregodin_oro",
    name: "PIERRE GODIN",
    version: "Oro",
    rarity: "Oro",
    rating: 85,
    position: "CB",
    league: "Superliga Europea",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Marsella.png",
    image: "assets/characters/Francia/PierreGodin.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "michaëlaron_oro",
    name: "MICHAËL ARON",
    version: "Oro",
    rarity: "Oro",
    rating: 79,
    position: "CB",
    league: "Superliga Europea",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Monaco.png",
    image: "assets/characters/Francia/MichaëlAron.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "francispoujol_oro",
    name: "FRANCIS POUJOL",
    version: "Oro",
    rarity: "Oro",
    rating: 80,
    position: "RB",
    league: "Superliga Europea",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Monaco.png",
    image: "assets/characters/Francia/FrancisPoujol.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "kevinpinot_oro",
    name: "KEVIN PINOT",
    version: "Oro",
    rarity: "Oro",
    rating: 79,
    position: "LB",
    league: "La Liga",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/RealBetis.png",
    image: "assets/characters/Francia/KevinPinot.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "rolandperec_oro",
    name: "ROLAND PEREC",
    version: "Oro",
    rarity: "Oro",
    rating: 83,
    position: "CM",
    league: "Superliga Europea",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Marsella.png",
    image: "assets/characters/Francia/RolandPerec.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "romualdhuysmans_oro",
    name: "ROMUALD HUYSMANS",
    version: "Oro",
    rarity: "Oro",
    rating: 81,
    position: "CM",
    league: "Superliga Europea",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Monaco.png",
    image: "assets/characters/Francia/RomualdHuysmans.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "stephanehinault_oro",
    name: "STEPHANE HINAULT",
    version: "Oro",
    rarity: "Oro",
    rating: 83,
    position: "CM",
    league: "Bundesliga",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/WerderBremen.png",
    image: "assets/characters/Francia/StephaneHinault.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "julienrousseau_oro",
    name: "JULIEN ROUSSEAU",
    version: "Oro",
    rarity: "Oro",
    rating: 86,
    position: "CM",
    league: "Premier League",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Chelsea.png",
    image: "assets/characters/Francia/JulienRousseau.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "jeromehervaud_oro",
    name: "JEROME HERVAUD",
    version: "Oro",
    rarity: "Oro",
    rating: 79,
    position: "LW",
    league: "Superliga Europea",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Monaco.png",
    image: "assets/characters/Francia/JeromeHervaud.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "alainfavreau_oro",
    name: "ALAIN FAVREAU",
    version: "Oro",
    rarity: "Oro",
    rating: 82,
    position: "ST",
    league: "Premier League",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/ManchesterUnited.png",
    image: "assets/characters/Francia/AlainFavreau.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "emilelazare_oro",
    name: "EMILE LAZARE",
    version: "Oro",
    rarity: "Oro",
    rating: 81,
    position: "GK",
    league: "Premier League",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Chelsea.png",
    image: "assets/characters/Francia/EmileLazare.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "andrepinson_oro",
    name: "ANDRE PINSON",
    version: "Oro",
    rarity: "Oro",
    rating: 80,
    position: "CDM",
    league: "Superliga Europea",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Marsella.png",
    image: "assets/characters/Francia/AndrePinson.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "jeangutain_oro",
    name: "JEAN GUTAIN",
    version: "Oro",
    rarity: "Oro",
    rating: 80,
    position: "RB",
    league: "La Liga",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Sevilla.png",
    image: "assets/characters/Francia/JeanGutain.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "claudemoreau_oro",
    name: "CLAUDE MOREAU",
    version: "Oro",
    rarity: "Oro",
    rating: 81,
    position: "LM",
    league: "La Liga",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/Athletic.png",
    image: "assets/characters/Francia/ClaudeMoreau.png",
    background: "assets/Cartas/Oro.png"
},
{
    id: "michelmorland_oro",
    name: "MICHEL MORLAND",
    version: "Oro",
    rarity: "Oro",
    rating: 82,
    position: "RW",
    league: "La Liga",
    nationFlag: "https://flagcdn.com/w40/fr.png",
    teamIcon: "teams/RealSociedad.png",
    image: "assets/characters/Francia/MichelMorland.png",
    background: "assets/Cartas/Oro.png"
},

// ==========================================
// NUEVOS JUGADORES ITALIA
// ==========================================
    {
        id: "clorinda_luzzago_oro",
        name: "C. LUZZAGO",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/ClorindaLuzzago.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "camilla_gonzaga_oro",
        name: "C. GONZAGA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Italia/CamillaGonzaga.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "bellamante_medici_oro",
        name: "B. MEDICI",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/BellamanteMedici.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "bellona_orsini_oro",
        name: "B. ORSINI",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Italia/BellonaOrsini.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "zerbino_savelli_oro",
        name: "Z. SAVELLI",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/ZerbinoSavelli.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "dardinello_foscari_oro",
        name: "D. FOSCARI",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/DardinelloFoscari.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "medoro_gritti_oro",
        name: "M. GRITTI",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Italia/MedoroGritti.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "grandazzo_corsin_oro",
        name: "G. CORSIN",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/GrandazzoCorsin.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "brandimarte_ruffo_oro",
        name: "B. RUFFO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/BrandimarteRuffo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "domenico_barberini_oro",
        name: "BARBERINI",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/DomenicoBarberiniOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "domenico_barberini_cabras",
        name: "BARBERINI",
        version: "Cabras",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/DomenicoBarberini.png",
        background: "assets/Cartas/Cabras.png"
    },
    {
        id: "orlando_pacelli_oro",
        name: "O. PACELLI",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/OrlandoPacelliOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "orlando_pacelli_futurestar",
        name: "O. PACELLI",
        version: "FutureStar",
        rarity: "Especial",
        rating: 89,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/OrlandoPacelli.png",
        background: "assets/Cartas/FutureStar.png"
    },
    {
        id: "oliviero_albizzi_oro",
        name: "O. ALBIZZI",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/OlivieroAlbizzi.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "fantaghiro_petrucci_oro",
        name: "F. PETRUCCI",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Italia/FantaghiroPetrucci.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "rinaldo_torelli_oro",
        name: "R. TORELLI",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/RinaldoTorelli.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "marfisa_corsi_oro",
        name: "M. CORSI",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/MarfisaCorsi.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ruggiero_spinola_oro",
        name: "R. SPINOLA",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/RuggieroSpinola.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "indigo_lazuli_oro",
        name: "I. LAZULI",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Italia/IndigoLazuli.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// NUEVOS JUGADORES ITALIA (PARTE 2)
// ==========================================
    {
        id: "rosseo_diamante_oro",
        name: "R. DIAMANTE",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "LB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/RosseoDiamante.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "julio_acuto_oro",
        name: "J. ACUTO",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Italia/JulioAcuto.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "vittorio_amatista_oro",
        name: "V. AMATISTA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "LM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Italia/VittorioAmatista.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "pardo_berillo_oro",
        name: "P. BERILLO",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RW",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Italia/PardoBerillo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "enrico_oconti_oro",
        name: "E. OCONTI",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "RM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Italia/EnricoOconti.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gianluca_zanardi_oro",
        name: "G. ZANARDI",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Italia/GianlucaZanardi.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "paolo_bianchi_oro",
        name: "P. BIANCHI",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CF",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/PaoloBianchiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "paolo_bianchi_cabras",
        name: "P. BIANCHI",
        version: "Cabras",
        rarity: "Especial",
        rating: 90,
        position: "CF",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/PaoloBianchi.png",
        background: "assets/Cartas/Cabras.png"
    },
    {
        id: "amaranto_rubino_oro",
        name: "A. RUBINO",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/AmarantoRubino.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "dante_diavolo_oro",
        name: "D. DIAVOLO",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LW",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/DanteDiavolo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "vento_galliano_oro",
        name: "V. GALLIANO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "LB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/VentoGalliano.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "marco_maserati_oro",
        name: "M. MASERATI",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Italia/MarcoMaserati.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "angelo_gabrini_oro",
        name: "A. GABRINI",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Italia/AngeloGabrini.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "giallo_topazio_oro",
        name: "G. TOPAZIO",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Italia/GialloTopazio.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "azzuro_zaffiro_oro",
        name: "A. ZAFFIRO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Italia/AzzuroZaffiro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "alessandro_rossa_oro",
        name: "A. ROSSA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/Italia/AlessandroRossa.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "bianco_perla_oro",
        name: "B. PERLA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/BiancoPerla.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "raffaele_generani_oro",
        name: "R. GENERANI",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RW",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/RaffaeleGenerani.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "berdeo_smeraldo_oro",
        name: "B. SMERALDO",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/BerdeoSmeraldo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "rosso_granato_oro",
        name: "R. GRANATO",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "RM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/RossoGranato.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "grigio_quarzo_oro",
        name: "G. QUARZO",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/GrigioQuarzo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gigi_blasi_oro",
        name: "G. BLASI",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/GigiBlasi.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "otto_nobili_oro",
        name: "O. NOBILI",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/OttoNobili.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "giacomo_yani_oro",
        name: "G. YANI",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/GiacomoYani.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "anton_graziuso_oro",
        name: "A. GRAZIUSO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/AntonGraziuso.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "daniele_santini_oro",
        name: "D. SANTINI",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Italia/DanieleSantini.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "azubel_turchese_oro",
        name: "A. TURCHESE",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Italia/AzubelTurchese.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "nereo_agata_oro",
        name: "N. AGATA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Italia/NereoAgata.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "marrone_corniola_oro",
        name: "M. CORNIOLA",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "LM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Italia/MarroneCorniola.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "giuseppe_carnivale_oro",
        name: "G. CARNIVALE",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "RB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Italia/GiuseppeCarnivale.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "nakata_oro",
        name: "NAKATA",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/NakataOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "nakata_cabras",
        name: "NAKATA",
        version: "Cabras",
        rarity: "Especial",
        rating: 90,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Italia/Nakata.png",
        background: "assets/Cartas/Cabras.png"
    },

// ==========================================
// JOFFREY Y MERILLO
// ==========================================
    {
        id: "joffrey_oro",
        name: "JOFFREY",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/fr.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Francia/Joffrey.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "merillo_oro",
        name: "MERILLO",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/co.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Colombia/Merillo.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// DON LORENZO
// ==========================================
    {
        id: "don_lorenzo_oro",
        name: "DON LORENZO",
        version: "Oro",
        rarity: "Oro",
        rating: 88,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/DonLorenzo/DonLorenzoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "don_lorenzo_ubers",
        name: "DON LORENZO",
        version: "Ubers",
        rarity: "Especial",
        rating: 90,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/DonLorenzo/DonLorenzo.png",
        background: "assets/Cartas/Ubers.png"
    },
    {
        id: "don_lorenzo_shapesifter",
        name: "DON LORENZO",
        version: "Shapesifters",
        rarity: "Especial",
        rating: 92,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/DonLorenzo/DonLorenzoReg.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "don_lorenzo_joker",
        name: "DON LORENZO",
        version: "Joker",
        rarity: "Especial",
        rating: 94,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/DonLorenzo/DonLorenzoPrime.png",
        background: "assets/Cartas/Joker.png"
    },

// ==========================================
// SNUFFY
// ==========================================
    {
        id: "snuffy_oro",
        name: "SNUFFY",
        version: "Oro",
        rarity: "Oro",
        rating: 90,
        position: "CF",
        altPositions: ["CM","CAM","CDM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/mt.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Snuffy/SnuffyOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "snuffy_ubers",
        name: "SNUFFY",
        version: "Ubers",
        rarity: "Especial",
        rating: 93,
        position: "CF",
        altPositions: ["CM","CAM","CDM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/mt.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Snuffy/Snuffy.png",
        background: "assets/Cartas/Ubers.png"
    },
    {
        id: "snuffy_fenix",
        name: "SNUFFY",
        version: "Naranja",
        rarity: "Especial",
        rating: 96,
        position: "CF",
        altPositions: ["CM","CAM","CDM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/mt.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Snuffy/SnuffyFenix.png",
        background: "assets/Cartas/Naranja.png"
    },

// ==========================================
// MIKE MOON
// ==========================================
    {
        id: "mike_moon_oro",
        name: "M. MOON",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Snuffy/MikeMoon.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "mike_moon_flash",
        name: "M. MOON",
        version: "Flashback",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Snuffy/MikeMoonFlash.png",
        background: "assets/Cartas/Flashback.png"
    },

// ==========================================
// ARABIA SAUDI
// ==========================================
    {
        id: "vulcan_oro",
        name: "VULCAN",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        altPositions: ["CB"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/ArabiaSaudi/VulcanOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "vulcan_shapesifter",
        name: "VULCAN",
        version: "Shapesifters",
        rarity: "Especial",
        rating: 87,
        position: "CB",
        altPositions: ["ST"],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Chicorid.png",
        image: "assets/characters/ArabiaSaudi/Vulcan.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "khalis_oro",
        name: "KHALIS",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/ArabiaSaudi/KhalisOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "khalis_rulebreaker",
        name: "KHALIS",
        version: "Rulebreaker",
        rarity: "Especial",
        rating: 87,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/ArabiaSaudi/Khalis.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "owairan_oro",
        name: "OWAIRAN",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/ArabiaSaudi/OwairanOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "owairan_tots",
        name: "OWAIRAN",
        version: "Tots",
        rarity: "Especial",
        rating: 89,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/ArabiaSaudi/Owairan2.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "owairan_shapesifter",
        name: "OWAIRAN",
        version: "Shapesifters",
        rarity: "Especial",
        rating: 91,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/ArabiaSaudi/Owairan.png",
        background: "assets/Cartas/Shapesifters.png"
    },

// ==========================================
// ARABIA SAUDI BASE
// ==========================================
    {
        id: "saidashraf_normal",
        name: "SAID ASHRAF",
        version: "Normal",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/ArabiaSaudi/SaidAshraf.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "falconalsaqir_normal",
        name: "FALCON AL-SAQIR",
        version: "Normal",
        rarity: "Oro",
        rating: 81,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/ArabiaSaudi/FalconAl-Saqir.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "khalilhaddaoui_normal",
        name: "KHALIL HADDAOUI",
        version: "Normal",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/ArabiaSaudi/KhalilHaddaoui.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "shakirzahir_normal",
        name: "SHAKIR ZAHIR",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/ArabiaSaudi/ShakirZahir.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "condoralkundur_normal",
        name: "CONDOR AL-KUNDUR",
        version: "Normal",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/ArabiaSaudi/CondorAl-Kundur.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "griffonalqahir_normal",
        name: "GRIFFON AL-QAHIR",
        version: "Normal",
        rarity: "Normal",
        rating: 79,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/ArabiaSaudi/GriffonAl-Qahir.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "salmankarim_normal",
        name: "SALMAN KARIM",
        version: "Normal",
        rarity: "Oro",
        rating: 80,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/ArabiaSaudi/SalmanKarim.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "asadgheisari_normal",
        name: "ASAD GHEISARI",
        version: "Normal",
        rarity: "Normal",
        rating: 78,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/ArabiaSaudi/AsadGheisari.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "qasimbatal_normal",
        name: "QASIM BATAL",
        version: "Normal",
        rarity: "Normal",
        rating: 76,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/ArabiaSaudi/QasimBatal.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ospreyalbahar_normal",
        name: "OSPREY AL-BAHAR",
        version: "Normal",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/ArabiaSaudi/OspreyAl-Bahar.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "shrikealjazzar_normal",
        name: "SHRIKE AL-JAZZAR",
        version: "Normal",
        rarity: "Normal",
        rating: 77,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/ArabiaSaudi/ShrikeAl-Jazzar.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "nazimnizar_normal",
        name: "NAZIM NIZAR",
        version: "Normal",
        rarity: "Normal",
        rating: 78,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/ArabiaSaudi/NazimNizar.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "batalmajid_normal",
        name: "BATAL MAJID",
        version: "Normal",
        rarity: "Normal",
        rating: 77,
        position: "RB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/ArabiaSaudi/BatalMajid.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "rashidhakim_normal",
        name: "RASHID HAKIM",
        version: "Normal",
        rarity: "Normal",
        rating: 79,
        position: "LM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/ArabiaSaudi/RashidHakim.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kestrelalsahir_normal",
        name: "KESTREL AL-SAHIR",
        version: "Normal",
        rarity: "Normal",
        rating: 77,
        position: "LB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/ArabiaSaudi/KestrelAl-Sahir.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "robinalahmar_normal",
        name: "ROBIN AL-AHMAR",
        version: "Normal",
        rarity: "Normal",
        rating: 75,
        position: "RW",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/ArabiaSaudi/RobinAl-Ahmar.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "hawkealjazzar_normal",
        name: "HAWKE AL-JAZZAR",
        version: "Normal",
        rarity: "Normal",
        rating: 76,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/ArabiaSaudi/HawkeAl-Bazzar.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "merlinalyaman_normal",
        name: "MERLIN AL-YAMAN",
        version: "Normal",
        rarity: "Normal",
        rating: 78,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/ArabiaSaudi/MerlinAl-Yaman.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "parryalsurah_normal",
        name: "PARRY AL-SURAH",
        version: "Normal",
        rarity: "Normal",
        rating: 78,
        position: "LW",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/ArabiaSaudi/PerryAl-Surah.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "qamarsadir_normal",
        name: "QAMAR SADIR",
        version: "Normal",
        rarity: "Normal",
        rating: 79,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/ArabiaSaudi/QamarSadir.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "buzzardalsahma_normal",
        name: "BUZZARD AL-SAHMA",
        version: "Normal",
        rarity: "Normal",
        rating: 79,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/ArabiaSaudi/BuzzardAl-Sahma.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "tamirnasr_normal",
        name: "TAMIR NASR",
        version: "Normal",
        rarity: "Normal",
        rating: 79,
        position: "RM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/ArabiaSaudi/TamirNasr.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "harrisalsuhra_normal",
        name: "HARRIS AL-SUHRA",
        version: "Normal",
        rarity: "Normal",
        rating: 76,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/ArabiaSaudi/HarrisAl-Suhra.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "eaglealsuhra_normal",
        name: "EAGLE AL-SUHRA",
        version: "Normal",
        rarity: "Normal",
        rating: 78,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/sa.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/ArabiaSaudi/EagleAl-Suhra.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// TAILANDIA EXTRA
// ==========================================
    {
        id: "thanakornjaa_normal",
        name: "THANAKORN JAA",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Tailandia/ThanakornJaa.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "soladakulkit_normal",
        name: "SOLADA KULKIT",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Tailandia/SoladaKulkit.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "naparattana_normal",
        name: "NAPA RATTANA",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Tailandia/NapaRattana.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "udomkaochuea_normal",
        name: "UDOM KAOCHUEA",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/Athletic.png",
        image: "assets/characters/Tailandia/UdomKaochuea.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "naowaratrahman_normal",
        name: "NAOWARAT RAHMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "LM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Tailandia/NaowaratRahman.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "meichaptri_normal",
        name: "MEI CHAPTRI",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "RM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Tailandia/MeiChaptri.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "klaharnsangsorn_normal",
        name: "KLAHARN SANGSORN",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/Tailandia/KlaharnSangsorn.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "bhaksepakroh_normal",
        name: "BHAK SEPAKROH",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/Tailandia/BhakSepakroh.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "naidsirisukha_normal",
        name: "NAID SIRISUKHA",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Tailandia/NaidSirisukha.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "suchartchaowarat_normal",
        name: "SUCHART CHAOWARAT",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CAM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/Tailandia/SuchartChaowarat.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "yuthpoonlarp_normal",
        name: "YUTH POONLARP",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "RB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/th.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Tailandia/YuthPoonlarp.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// MEXICO EXTRA
// ==========================================
    {
        id: "guillermorobles_normal",
        name: "GUILLERMO ROBLES",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/Mexico/GuillermoRobles.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hectorvaldes_normal",
        name: "HECTOR VALDES",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Mexico/HectorValdes.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "raulsalcedo_normal",
        name: "RAUL SALCEDO",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/Mexico/RaulSalcedo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "santiagoherrera_normal",
        name: "SANTIAGO HERRERA",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Mexico/SantiagoHerrera.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "javiermontes_normal",
        name: "JAVIER MONTES",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "RM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Benfica.png",
        image: "assets/characters/Mexico/JavierMontes.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "vicentegarza_normal",
        name: "VICENTE GARZA",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/Mexico/VicenteGarza.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "andresespinoza_normal",
        name: "ANDRES ESPINOZA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Mexico/AndresEspinoza.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "luisrojas_normal",
        name: "LUIS ROJAS",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "RB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Mexico/LuisRojas.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "diegoalvarez_normal",
        name: "DIEGO ALVAREZ",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LW",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Mexico/DiegoAlvarez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "mateojimenez_normal",
        name: "MATEO JIMENEZ",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/Mexico/MateoJimenez.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "emiliocruz_normal",
        name: "EMILIO CRUZ",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CDM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/mx.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/Mexico/EmilioCruz.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// HOLANDA EXTRA
// ==========================================
    {
        id: "malder_oro",
        name: "MALDER",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Holanda/MalderOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "malder_naranja",
        name: "MALDER",
        version: "Naranja",
        rarity: "Especial",
        rating: 86,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Holanda/Malder.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "gullit_oro",
        name: "GULLIT",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Holanda/GullitOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gullit_milan",
        name: "GULLIT",
        version: "Milan",
        rarity: "Especial",
        rating: 89,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Holanda/Gullit.png",
        background: "assets/Cartas/Milan.png"
    },
    {
        id: "vaalenvoort_oro",
        name: "VAALENVOORT",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Holanda/VaalenVoort.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "buhon_oro",
        name: "BUHON",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Italia/Buhon.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// CROACIA EXTRA
// ==========================================
    {
        id: "seaken_oro",
        name: "SEAKEN",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/hr.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Croacia/SeakenOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "seaken_bastard",
        name: "SEAKEN",
        version: "Bastard",
        rarity: "Especial",
        rating: 86,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/hr.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Croacia/Seaken.png",
        background: "assets/Cartas/Bastard.png"
    },

// ==========================================
// LEYENDAS EXTRA
// ==========================================
    {
        id: "alexidallas_oro",
        name: "ALEXI DALLAS",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/us.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/USA/AlexiDallas.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "carlosvalderroca_oro",
        name: "CARLOS VALDERROCA",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/co.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Colombia/CarlosValderroca.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// ALEMANIA EXTRA
// ==========================================
    {
        id: "dremer_oro",
        name: "DREMER",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Dremer.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// MULLER
// ==========================================
    {
        id: "muller_oro",
        name: "MULLER",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Alemania/MullerOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "muller_base",
        name: "MULLER",
        version: "Bundes",
        rarity: "Especial",
        rating: 89,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Alemania/MullerBase.png",
        background: "assets/Cartas/Bundes.png"
    },
    {
        id: "muller_trueno",
        name: "MULLER",
        version: "Trueno",
        rarity: "Especial",
        rating: 91,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Alemania/Muller.png",
        background: "assets/Cartas/Trueno.png"
    },
    {
        id: "muller_custom",
        name: "MULLER",
        version: "Custom",
        rarity: "Especial",
        rating: 93,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Alemania/MullerCustom.png",
        background: "assets/backgrounds/Fondo_Muller.png"
    },
// ==========================================
// TEIGERBRAN
// ==========================================
    {
        id: "teigerbran_oro",
        name: "TEIGERBRAN",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Alemania/TeigerbranOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "teigerbran_alemania",
        name: "TEIGERBRAN",
        version: "Alemania",
        rarity: "Especial",
        rating: 87,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Alemania/Teigerbran.png",
        background: "assets/Cartas/Alemania.png"
    },
// ==========================================
// SCHMIDT BROS
// ==========================================
    {
        id: "kevinschmidt_oro",
        name: "KEVIN SCHMIDT",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Alemania/KevinSchmidt.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ericschmidt_oro",
        name: "ERIC SCHMIDT",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Alemania/EricSchmidt.png",
        background: "assets/Cartas/Oro.png"
    },
// ==========================================
// SCHESTER
// ==========================================
    {
        id: "schester_oro",
        name: "SCHESTER",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/SchesterOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "schester_verde",
        name: "SCHESTER",
        version: "Shapesifters",
        rarity: "Especial",
        rating: 88,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/SchesterVerde.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "schester_alemania",
        name: "SCHESTER",
        version: "Alemania",
        rarity: "Especial",
        rating: 89,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/Schester.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "schester_custom",
        name: "SCHESTER",
        version: "Custom",
        rarity: "Especial",
        rating: 90,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/SchesterCustom.png",
        background: "assets/backgrounds/Fondo_Schester.png"
    },
// ==========================================
// MARGUS
// ==========================================
    {
        id: "margus_oro",
        name: "MARGUS",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/MargusOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "margus_shapesifters",
        name: "MARGUS",
        version: "Shapesifters",
        rarity: "Especial",
        rating: 87,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/Margus.png",
        background: "assets/Cartas/Shapesifters.png"
    },
// ==========================================
// GOETHE
// ==========================================
    {
        id: "goethe_oro",
        name: "GOETHE",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CAM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/GoetheOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "goethe_rosa",
        name: "GOETHE",
        version: "Rosa",
        rarity: "Especial",
        rating: 86,
        position: "CAM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/Goethe.png",
        background: "assets/Cartas/Rosa.png"
    },
// ==========================================
// KALTZ
// ==========================================
    {
        id: "kaltz_oro",
        name: "KALTZ",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Alemania/KaltzOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kaltz_alemania",
        name: "KALTZ",
        version: "Alemania",
        rarity: "Especial",
        rating: 89,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Alemania/KaltzHam.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "kaltz_fondo2",
        name: "KALTZ",
        version: "Custom 2",
        rarity: "Especial",
        rating: 90,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Alemania/KaltzFondo2.png",
        background: "assets/backgrounds/Fondo_Kaltz2.png"
    },
    {
        id: "kaltz_fondo1",
        name: "KALTZ",
        version: "Custom 1",
        rarity: "Especial",
        rating: 91,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Alemania/KaltzFondo1.png",
        background: "assets/backgrounds/Fondo_Kaltz1.jpg"
    },
// ==========================================
// SCHNEIDER
// ==========================================
    {
        id: "schneider_oro",
        name: "SCHNEIDER",
        version: "Oro",
        rarity: "Oro",
        rating: 88,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/SchneiderOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "schneider_bastard",
        name: "SCHNEIDER",
        version: "Bastard",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Schneider.png",
        background: "assets/Cartas/Bastard.png"
    },
    {
        id: "schneider_alemania",
        name: "SCHNEIDER",
        version: "Alemania",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/SchneiderFull.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "schneider_fondo2",
        name: "SCHNEIDER",
        version: "Custom 2",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Schneiderfondo2.png",
        background: "assets/backgrounds/Fondo_Schneider2.png"
    },
    {
        id: "schneider_fondo1",
        name: "SCHNEIDER",
        version: "Custom 1",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Schneiderfondo1.png",
        background: "assets/backgrounds/Fondo_Schneider1.jpg"
    },

// ==========================================
// ALEMANIA EXTRA PART 2
// ==========================================
    {
        id: "thorsten_welger_oro",
        name: "T. WELGER",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Alemania/ThorstenWelger.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kurt_zawel_oro",
        name: "K. ZAWEL",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Alemania/KurtZawel.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jonas_polk_oro",
        name: "J. POLK",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "RM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Alemania/JonasPolk.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "erwin_volz_oro",
        name: "E. VÖLZ",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "LW",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Dortmund.png",
        image: "assets/characters/Alemania/ErwinVölz.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "maximilian_muller_oro",
        name: "M. MÜLLER",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Alemania/MaximilianMüller.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "heinrich_farber_oro",
        name: "H. FARBER",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Alemania/HeinrichFarber.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jan_oster_oro",
        name: "J. OSTER",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Alemania/JanOster.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gerhard_enders_oro",
        name: "G. ENDERS",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Alemania/GerhardEnders.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "alexander_hausen_oro",
        name: "A. HAUSEN",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/AlexanderHausen.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "peter_naumann_oro",
        name: "P. NAUMANN",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/PeterNaumann.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "niklas_kuster_oro",
        name: "N. KUSTER",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CAM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/NiklasKuster.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "emmanuel_ewerz_oro",
        name: "E. EWERZ",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Alemania/EmmanuelEwerz.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "lukas_schmidt_oro",
        name: "L. SCHMIDT",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Alemania/LukasSchmidt.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "theodor_ulrich_oro",
        name: "T. ULRICH",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Alemania/TheodorUlrich.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ernst_fliender_oro",
        name: "E. FLIENDER",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Alemania/ErnstFliender.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jens_hoffman_oro",
        name: "J. HOFFMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Alemania/JensHoffman.png",
        background: "assets/Cartas/Orobase.png"
    },

// ==========================================
// BASTARD EXTRA
// ==========================================
    {
        id: "bachman_oro",
        name: "BACHMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/BachmanOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "bachman_alemania",
        name: "BACHMAN",
        version: "Alemania",
        rarity: "Especial",
        rating: 81,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Bachman.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "theosachs_oro",
        name: "THEO SACHS",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/TheoSachsOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "theosachs_alemania",
        name: "THEO SACHS",
        version: "Alemania",
        rarity: "Especial",
        rating: 83,
        position: "LB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/TheoSachs.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "birkenstock_oro",
        name: "BIRKENSTOCK",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/BirkenstockOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "birkenstock_alemania",
        name: "BIRKENSTOCK",
        version: "Alemania",
        rarity: "Especial",
        rating: 83,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Birkenstock.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "mensah_oro",
        name: "MENSAH",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/MensahOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "mensah_alemania",
        name: "MENSAH",
        version: "Alemania",
        rarity: "Especial",
        rating: 82,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Mensah.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "ali_oro",
        name: "ALI",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/AliOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ali_alemania",
        name: "ALI",
        version: "Alemania",
        rarity: "Especial",
        rating: 83,
        position: "CDM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Ali.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "benedictgrim_oro",
        name: "BENEDICT GRIM",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "LM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/BenedictGrimOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "benedictgrim_alemania",
        name: "BENEDICT GRIM",
        version: "Alemania",
        rarity: "Especial",
        rating: 86,
        position: "LM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/BenedictGrim.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "erikgesner_oro",
        name: "ERIK GESNER",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/ErikGesnerOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "erikgesner_alemania",
        name: "ERIK GESNER",
        version: "Alemania",
        rarity: "Especial",
        rating: 85,
        position: "RM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/ErikGesner.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "igorschneider_oro",
        name: "IGOR SCHNEIDER",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/IgorSchneider.png",
        background: "assets/Cartas/Oro.png"
    },

// ==========================================
// INGLATERRA
// ==========================================
    {
        id: "beekham_oro",
        name: "BEEKHAM",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "RM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/Inglaterra/Beekham.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "edgar_partinus_oro",
        name: "EDGAR",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Inglaterra/EdgarPartinusOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "edgar_partinus_tots",
        name: "EDGAR",
        version: "Tots",
        rarity: "TOTS",
        rating: 89,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Inglaterra/EdgarPartinus.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "jonny_gascoigne_oro",
        name: "JONNY",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Inglaterra/JonnyGascoigne.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "mikey_richards_oro",
        name: "MIKEY",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CDM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Chelsea.png",
        image: "assets/characters/Inglaterra/MikeyRichards.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "robson_oro",
        name: "ROBSON",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Inglaterra/Robosn.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "philip_owen_oro",
        name: "PHILIP",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Inglaterra/PhilipArwen.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "edge_ripper_oro",
        name: "EDGE",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "LB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Inglaterra/EdgeRipper.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "eric_purpleton_oro",
        name: "ERIC",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Inglaterra/EricPurpleton.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "servilius_jeeves_oro",
        name: "JEEVES",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Inglaterra/ServiliusJeeves.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "barnes_oro",
        name: "BARNES",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Inglaterra/Barnes.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "freddy_mcqueen_oro",
        name: "FREDDY",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Inglaterra/FreddyMcQueen.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gary_mane_oro",
        name: "GARY",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "LM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Inglaterra/GaryMane.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "martin_squall_oro",
        name: "MARTIN",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "RB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Arsenal.png",
        image: "assets/characters/Inglaterra/MartinSquall.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "lance_ralton_oro",
        name: "LANCE",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/Inglaterra/LanceRalton.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "peter_cole_oro",
        name: "PETER",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "RM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/Inglaterra/PeterCoole.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "nick_woodgate_oro",
        name: "NICK",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/Inglaterra/NickWoodgate.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "david_buckingham_oro",
        name: "DAVID",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Inglaterra/DavidBuckingham.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "paul_appleton_oro",
        name: "PAUL",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Inglaterra/PaulAppleton.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sirius_pounding_oro",
        name: "SIRIUS",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "RM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/gb-eng.png",
        teamIcon: "teams/Tottenham.png",
        image: "assets/characters/Inglaterra/SiriusPounding.png",
        background: "assets/Cartas/Oro.png"
    },
// ==========================================
// CORNELIUS HEINE
    {
        id: "corneliusheine_oro",
        name: "HEINE",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CAM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/Alemania/HeineOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "corneliusheine_joker",
        name: "HEINE",
        version: "Joker",
        rarity: "Especial",
        rating: 90,
        position: "CAM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Liverpool.png",
        image: "assets/characters/Alemania/Heine.png",
        background: "assets/Cartas/Joker.png"
    },

// NESS
// ==========================================
    {
        id: "ness_oro",
        name: "NESS",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/NessOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ness_alemania",
        name: "NESS",
        version: "Alemania",
        rarity: "Especial",
        rating: 90,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/Ness.png",
        background: "assets/Cartas/Alemania.png"
    },
    {
        id: "ness_bastard",
        name: "NESS",
        version: "Future Star",
        rarity: "Especial",
        rating: 92,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/NessBastard.png",
        background: "assets/Cartas/FutureStar.png"
    },

// ==========================================
// MICHAEL KAISER
// ==========================================
    {
        id: "michaelkaiser_oro",
        name: "KAISER",
        version: "Oro",
        rarity: "Oro",
        rating: 88,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/KaiserOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "michaelkaiser_bastard",
        name: "KAISER",
        version: "Bastard",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/KaiserBastard.png",
        background: "assets/Cartas/Bastard.png"
    },
    {
        id: "michaelkaiser_rulebreaker",
        name: "KAISER",
        version: "Rulebreaker",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/KaiserChute.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "michaelkaiser_tots",
        name: "KAISER",
        version: "TOTS",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Alemania/KaiserCelebracion.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "michaelkaiser_alemania",
        name: "KAISER",
        version: "Alemania",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/de.png",
        teamIcon: "teams/Real.png",
        image: "assets/characters/Alemania/KaiserAlemania.png",
        background: "assets/Cartas/Alemania.png"
    }
];

// ==========================================
// SUDAFRICA
// ==========================================
