// database/porto_cards.js
const portoCards = [
    {
        id: "deco_oro",
        name: "DECO",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/pt.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/DecoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "deco_tots",
        name: "DECO",
        version: "Tots",
        rarity: "Especial",
        rating: 90,
        position: "CM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/pt.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/Deco.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "dragonfly_oro",
        name: "DRAGONFLY",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "RW",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/rs.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/DragonflyOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "dragonfly_tots",
        name: "DRAGONFLY",
        version: "Tots",
        rarity: "Especial",
        rating: 88,
        position: "RW",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/rs.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/Dragonfly.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "krusler_oro",
        name: "KRUSLER JR",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LW",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/dk.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/KruslerJr.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "woods_oro",
        name: "WOODS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jm.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/WoodsOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "woods_tots",
        name: "WOODS",
        version: "Tots",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jm.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/Woods.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "kofi_oro",
        name: "KOFI",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CAM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/ng.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/KofiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kofi_tots",
        name: "KOFI",
        version: "Tots",
        rarity: "Especial",
        rating: 88,
        position: "CAM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/ng.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/Kofi.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "oliveira_oro",
        name: "OLIVEIRA",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/pt.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/Oliveira.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "oliveira_cabras",
        name: "OLIVEIRA",
        version: "Cabras",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/pt.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Porto/Oliviera.png",
        background: "assets/Cartas/Cabras.png"
    }
];
