// database/raimon_cards.js
const raimonCards = [
    { id: "jim_oro", name: "JIM", version: "Oro", rarity: "Oro", rating: 75, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/JimOro.png", background: "assets/Cartas/Orobase.png" },
    { id: "jim_raimon", name: "JIM", version: "Raimon", rarity: "Especial", rating: 81, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Jim.png", background: "assets/Cartas/Raimon.png" },
    { id: "max_oro", name: "MAX", version: "Oro", rarity: "Oro", rating: 76, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/MaxOro.png", background: "assets/Cartas/Oro.png" },
    { id: "max_raimon", name: "MAX", version: "Raimon", rarity: "Especial", rating: 81, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Max.png", background: "assets/Cartas/Raimon.png" },
    { id: "sam_oro", name: "SAM", version: "Oro", rarity: "Oro", rating: 75, position: "RM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/SamOro.png", background: "assets/Cartas/Orobase.png" },
    { id: "steve_oro", name: "STEVE", version: "Oro", rarity: "Oro", rating: 76, position: "LM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/SteveOro.png", background: "assets/Cartas/Oro.png" },
    { id: "steve_raimon", name: "STEVE", version: "Raimon", rarity: "Especial", rating: 81, position: "LM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Steve.png", background: "assets/Cartas/Raimon.png" },
    { id: "tim_oro", name: "TIM", version: "Oro", rarity: "Oro", rating: 76, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/TimOro.png", background: "assets/Cartas/Oro.png" },
    { id: "tim_raimon", name: "TIM", version: "Raimon", rarity: "Especial", rating: 81, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Tim.png", background: "assets/Cartas/Raimon.png" },
    { id: "tod_oro", name: "TOD", version: "Oro", rarity: "Oro", rating: 79, position: "RB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/TodOro.png", background: "assets/Cartas/Oro.png" },
    { id: "willy_oro", name: "WILLY", version: "Oro", rarity: "Oro", rating: 73, position: "ST", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/WillyOro.png", background: "assets/Cartas/Orobase.png" },
    { id: "willy_raimon", name: "WILLY", version: "Raimon", rarity: "Especial", rating: 81, position: "ST", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Willy.png", background: "assets/Cartas/Raimon.png" }
];
