// database/raimon_cards.js
const raimonCards = [
    { id: "jim_oro", name: "JIM", version: "Oro", rarity: "Oro", rating: 75, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/JimOro.png", background: "assets/Cartas/Orobase.png" },
    { id: "jim_raimon", name: "JIM", version: "Raimon", rarity: "Especial", rating: 81, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Jim.png", background: "assets/Cartas/Raimon.png" },
    { id: "max_oro", name: "MAX", version: "Oro", rarity: "Oro", rating: 76, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/MaxOro.png", background: "assets/Cartas/Oro.png" },
    { id: "max_raimon", name: "MAX", version: "Raimon", rarity: "Especial", rating: 81, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Max.png", background: "assets/Cartas/Raimon.png" },
    { id: "sam_oro", name: "SAM", version: "Oro", rarity: "Oro", rating: 75, position: "RM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/SamOro.png", background: "assets/Cartas/Orobase.png" },
    { id: "steve_oro", name: "STEVE", version: "Oro", rarity: "Oro", rating: 76, position: "LM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/SteveOro.png", background: "assets/Cartas/Oro.png" },
    { id: "steve_raimon", name: "STEVE", version: "Raimon", rarity: "Especial", rating: 81, position: "LM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Steve.png", background: "assets/Cartas/Raimon.png" },
    { id: "tim_oro", name: "TIM", version: "Oro", rarity: "Oro", rating: 76, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/TimOro.png", background: "assets/Cartas/Oro.png" },
    { id: "tim_raimon", name: "TIM", version: "Raimon", rarity: "Especial", rating: 81, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Tim.png", background: "assets/Cartas/Raimon.png" },
    { id: "tod_oro", name: "TOD", version: "Oro", rarity: "Oro", rating: 79, position: "RB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/TodOro.png", background: "assets/Cartas/Oro.png" },
    { id: "willy_oro", name: "WILLY", version: "Oro", rarity: "Oro", rating: 73, position: "ST", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/WillyOro.png", background: "assets/Cartas/Orobase.png" },
    { id: "willy_raimon", name: "WILLY", version: "Raimon", rarity: "Especial", rating: 81, position: "ST", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Raimon/Willy.png", background: "assets/Cartas/Raimon.png" },
    {
        id: "zanderwarmington_oro",
        name: "ZANDER WARMINGTON",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Zander Warmington.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "zander_warmingtonprime",
        name: "ZANDER WARMINGTON",
        version: "Prime",
        rarity: "Especial",
        rating: 88,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Zander WarmingtonPrime.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "viorainmaleby_oro",
        name: "VIORAIN MALEBY",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Viorain Maleby.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "clementmariner_oro",
        name: "CLEMENT MARINER",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Clement Mariner.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "boonewretman_oro",
        name: "BOONE WRETMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Boone Wretman.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "jazminecarmine_oro",
        name: "JAZMINE CARMINE",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Jazmine Carmine.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "coltonsharps_oro",
        name: "COLTON SHARPS",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Colton Sharps.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "maddockjackson_oro",
        name: "MADDOCK JACKSON",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CAM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Maddock Jackson.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "eleanorestrella_oro",
        name: "ELEANOR ESTRELLA",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Eleanor Estrella.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "darianmoonward_oro",
        name: "DARIAN MOONWARD",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CAM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Darian Moonward.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "darian_moonward2",
        name: "DARIAN MOONWARD",
        version: "2",
        rarity: "Especial",
        rating: 89,
        position: "CAM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Darian Moonward2.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "harperevans_oro",
        name: "HARPER EVANS",
        version: "Oro",
        rarity: "Oro",
        rating: 90,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Harper Evans.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "harper_evansbase",
        name: "HARPER EVANS",
        version: "Base",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Harper EvansBase.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "harper_evanstor",
        name: "HARPER EVANS",
        version: "Tor",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Harper EvansTor.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "harper_evansnike",
        name: "HARPER EVANS",
        version: "Nike",
        rarity: "Especial",
        rating: 96,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Harper EvansNike.png",
        background: "assets/Cartas/Trailblaze.png"
    },
    {
        id: "talonlewis_oro",
        name: "TALON LEWIS",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Talon Lewis.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "talon_lewisprime",
        name: "TALON LEWIS",
        version: "Prime",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Talon LewisPrime.png",
        background: "assets/Cartas/Morada.png"
    },
    {
        id: "ninogamberini_oro",
        name: "NINO GAMBERINI",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Nino Gamberini.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kaeospringfield_oro",
        name: "KAEO SPRINGFIELD",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CDM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Kaeo Springfield.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "milanmcgrath_oro",
        name: "MILAN MC GRATH",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Milan McGrath.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hortensiaraintree_oro",
        name: "HORTENSIA RAINTREE",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Hortensia Raintree.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "matildashadebough_oro",
        name: "MATILDA SHADEBOUGH",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Matilda Shadebough.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "matilda_shadeboughprime",
        name: "MATILDA SHADEBOUGH",
        version: "Prime",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Raimon/Matilda ShadeboughPrime.png",
        background: "assets/Cartas/Raimon.png"
    }
];
