const realjaponCards = [
    {
        id: "furukawaoro_realjapon",
        name: "KOTARO FURUKAWA",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/RealJapon/FurukawaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "furukawa_realjapon",
        name: "KOTARO FURUKAWA",
        version: "Hielo",
        rarity: "Especial",
        rating: 87,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/RealJapon/Furukawa.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "furukawaprime_realjapon",
        name: "KOTARO FURUKAWA",
        version: "Prime",
        rarity: "Especial",
        rating: 90,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/RealJapon/FurukawaPrime.png",
        background: "assets/Cartas/Verde.png"
    },
    {
        id: "gamooro_realjapon",
        name: "MINATO GAMO",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/CAOsasuna.png",
        image: "assets/characters/RealJapon/GamoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gamo_realjapon",
        name: "MINATO GAMO",
        version: "Icono",
        rarity: "Especial",
        rating: 92,
        position: "CDM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/CAOsasuna.png",
        image: "assets/characters/RealJapon/Gamo.png",
        background: "assets/Cartas/Icono.png"
    },
    {
        id: "igawaoro_realjapon",
        name: "GAKUTO IGAWA",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villarreal.png",
        image: "assets/characters/RealJapon/IgawaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "igawa_realjapon",
        name: "GAKUTO IGAWA",
        version: "Hielo",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villarreal.png",
        image: "assets/characters/RealJapon/Igawa.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "igawaprime_realjapon",
        name: "GAKUTO IGAWA",
        version: "Prime",
        rarity: "Especial",
        rating: 91,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villarreal.png",
        image: "assets/characters/RealJapon/IgawaPrime.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "katagirioro_realjapon",
        name: "MUNEMASA KATAGIRI",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Fiorentina.png",
        image: "assets/characters/RealJapon/KatagiriOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "katagiri_realjapon",
        name: "MUNEMASA KATAGIRI",
        version: "Icono",
        rarity: "Especial",
        rating: 93,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Fiorentina.png",
        image: "assets/characters/RealJapon/Katagiri.png",
        background: "assets/Cartas/Icono.png"
    },
    {
        id: "kazamioro_realjapon",
        name: "SHINNOSUKE KAZAMI",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "RM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/BayerLeverkusen.png",
        image: "assets/characters/RealJapon/KazamiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kazami_realjapon",
        name: "SHINNOSUKE KAZAMI",
        version: "Hielo",
        rarity: "Especial",
        rating: 87,
        position: "RM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/BayerLeverkusen.png",
        image: "assets/characters/RealJapon/Kazami.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "kazamiprime_realjapon",
        name: "SHINNOSUKE KAZAMI",
        version: "Prime",
        rarity: "Especial",
        rating: 90,
        position: "RM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/BayerLeverkusen.png",
        image: "assets/characters/RealJapon/KazamiPrime.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "mikamioro_realjapon",
        name: "TATSUO MIKAMI",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/RealJapon/MikamiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "mikami_realjapon",
        name: "TATSUO MIKAMI",
        version: "Icono",
        rarity: "Especial",
        rating: 92,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/RealJapon/Mikami.png",
        background: "assets/Cartas/Icono.png"
    },
    {
        id: "nakanishioro_realjapon",
        name: "TAICHI NAKANISHI",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AstonVilla.png",
        image: "assets/characters/RealJapon/NakanishiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "nakanishi_realjapon",
        name: "TAICHI NAKANISHI",
        version: "Hielo",
        rarity: "Especial",
        rating: 84,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AstonVilla.png",
        image: "assets/characters/RealJapon/Nakanishi.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "okanooro_realjapon",
        name: "TOSHIYA OKANO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "RW",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/CrystalPalace.png",
        image: "assets/characters/RealJapon/OkanoOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "okano_realjapon",
        name: "TOSHIYA OKANO",
        version: "Hielo",
        rarity: "Especial",
        rating: 87,
        position: "RW",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/CrystalPalace.png",
        image: "assets/characters/RealJapon/Okano.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "sakakioro_realjapon",
        name: "YUJI SAKAKI",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/RealJapon/SakakiOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sakaki_realjapon",
        name: "YUJI SAKAKI",
        version: "Hielo",
        rarity: "Especial",
        rating: 84,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/RealJapon/Sakaki.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "sogaoro_realjapon",
        name: "YUJI SOGA",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/RealJapon/SogaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "soga_realjapon",
        name: "YUJI SOGA",
        version: "Hielo",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/RealJapon/Soga.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "soga2_realjapon",
        name: "YUJI SOGA",
        version: "RojiAzul",
        rarity: "Especial",
        rating: 91,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/RealJapon/Soga2.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "sogaprime_realjapon",
        name: "YUJI SOGA",
        version: "Prime",
        rarity: "Especial",
        rating: 94,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/RealJapon/SogaPrime.png",
        background: "assets/Cartas/Mordiscos.png"
    },
    {
        id: "yamadaoro_realjapon",
        name: "MICHEL YAMADA",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Frankfurt.png",
        image: "assets/characters/RealJapon/YamadaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "yamada_realjapon",
        name: "MICHEL YAMADA",
        version: "Hielo",
        rarity: "Especial",
        rating: 84,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Frankfurt.png",
        image: "assets/characters/RealJapon/Yamada.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "yoshikawaoro_realjapon",
        name: "KOJI YOSHIKAWA",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/RealJapon/YoshikawaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "yoshikawa_realjapon",
        name: "KOJI YOSHIKAWA",
        version: "Hielo",
        rarity: "Especial",
        rating: 85,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Napoli.png",
        image: "assets/characters/RealJapon/Yoshikawa.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "yumikuraoro_realjapon",
        name: "NOBUYUKI YUMIKURA",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/CeltaVigo.png",
        image: "assets/characters/RealJapon/YumikuraOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "yumikura_realjapon",
        name: "NOBUYUKI YUMIKURA",
        version: "Hielo",
        rarity: "Especial",
        rating: 86,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/CeltaVigo.png",
        image: "assets/characters/RealJapon/Yumikura.png",
        background: "assets/Cartas/Hielo.png"
    }
];
