const riberaKasaminoCards = [
    {
        id: "JoeIngram",
        name: "JOE INGRAM",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/JoeIngram.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "KendallSefton",
        name: "KENDALL SEFTON",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/KendallSefton.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "JasonStrike",
        name: "JASON STRIKE",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/JasonStrike.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "NormanPorter",
        name: "NORMAN PORTER",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/NormanPorter.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MaxwellClaus",
        name: "MAXWELL CLAUS",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/MaxwellClaus.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "BruceChaney",
        name: "BRUCE CHANEY",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/BruceChaney.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "LeroyRhymes",
        name: "LEROY RHYMES",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/LeroyRhymes.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MildfordScott",
        name: "MILDFORD SCOTT",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "RM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/MildfordScott.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "LouEdmonds",
        name: "LOU EDMONDS",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/LouEdmonds.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "CameronMorefield",
        name: "CAMERON MOREFIELD",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "LM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/CameronMorefield.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "GregBernard",
        name: "GREG BERNARD",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/GregBernard.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "PeterBanker",
        name: "PETER BANKER",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "CDM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/PeterBanker.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "SaulTunk",
        name: "SAUL TUNK",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/SaulTunk.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "AlanMast",
        name: "ALAN MAST",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "RB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/AlanMast.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "PaulCaparock",
        name: "PAUL CAPAROCK",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/PaulCaparock.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "JuliusMolehill",
        name: "JULIUS MOLEHILL",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RiberaKasamino.png",
        image: "assets/characters/Umbrella/JuliusMolehill.png",
        background: "assets/Cartas/Oro.png"
    }
];
