const ryomaCards = [
    {
        id: "RyomaOro",
        name: "RYOMA NISHIKI",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "LM",
        secondaryPositions: ["RM", "RW", "LW", "LB", "RB", "CM", "CAM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Ryoma/RyomaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "RyomaMixOro",
        name: "RYOMA NISHIKI",
        version: "MixOro",
        rarity: "Oro",
        rating: 86,
        position: "LM",
        secondaryPositions: ["RM", "RW", "LW", "LB", "RB", "CM", "CAM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Ryoma/RyomaMixOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "RyomaBase",
        name: "RYOMA NISHIKI",
        version: "Base",
        rarity: "Especial",
        rating: 87,
        position: "LM",
        secondaryPositions: ["RM", "RW", "LW", "LB", "RB", "CM", "CAM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Ryoma/RyomaBase.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "RyomaChut",
        name: "RYOMA NISHIKI",
        version: "Chut",
        rarity: "Especial",
        rating: 89,
        position: "LM",
        secondaryPositions: ["RM", "RW", "LW", "LB", "RB", "CM", "CAM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Ryoma/RyomaChut.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "RyomaMix",
        name: "RYOMA NISHIKI",
        version: "Mix",
        rarity: "Especial",
        rating: 90,
        position: "LM",
        secondaryPositions: ["RM", "RW", "LW", "LB", "RB", "CM", "CAM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Ryoma/RyomaMix.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "RyomaPrime2",
        name: "RYOMA NISHIKI",
        version: "Prime2",
        rarity: "Especial",
        rating: 91,
        position: "LM",
        secondaryPositions: ["RM", "RW", "LW", "LB", "RB", "CM", "CAM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Ryoma/RyomaPrime2.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "RyomaArm",
        name: "RYOMA NISHIKI",
        version: "Arm",
        rarity: "Especial",
        rating: 92,
        position: "LM",
        secondaryPositions: ["RM", "RW", "LW", "LB", "RB", "CM", "CAM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Ryoma/RyomaPrime.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "RyomaPrime",
        name: "RYOMA NISHIKI",
        version: "Prime",
        rarity: "Especial",
        rating: 93,
        position: "LM",
        secondaryPositions: ["RM", "RW", "LW", "LB", "RB", "CM", "CAM"],
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Roma.png",
        image: "assets/characters/Ryoma/RyomaArmPrime.png",
        background: "assets/Cartas/Tots.png"
    }
];
