const sallysCards = [
    {
        id: "SuzanneYuma",
        name: "SUZANNE YUMA",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/Sallys/SuzanneYuma.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "TammyFielding",
        name: "TAMMY FIELDING",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Sallys/TammyFielding.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "AlexLovely",
        name: "ALEX LOVELY",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "LB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Sallys/AlexLovely.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "LouisHillside",
        name: "LOUIS HILLSIDE",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/Sallys/LouisHillside.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "NessSheldon",
        name: "NESS SHELDON",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "RB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/Sallys/NessSheldon.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "LizzySquirrel",
        name: "LIZZY SQUIRREL",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Racing.png",
        image: "assets/characters/Sallys/LizzySquirrel.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "KippyJones",
        name: "KIPPY JONES",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/Sallys/KippyJones.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "FayetteRiversong",
        name: "FAYETTE RIVERSONG",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "RM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Sallys/FayetteRiversong.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "SamanthaMoonlight",
        name: "SAMANTHA MOONLIGHT",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Osasuna.png",
        image: "assets/characters/Sallys/SamanthaMoonlight.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MitchSandstone",
        name: "MITCH SANDSTONE",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/malaga.png",
        image: "assets/characters/Sallys/MitchSandstone.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "EddiePrentice",
        name: "EDDIE PRENTICE",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Sallys/EddiePrentice.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "AlfHolmes",
        name: "ALF HOLMES",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/Sallys/AlfHolmes.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "IanStager",
        name: "IAN STAGER",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Sallys/IanStager.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "FredCrumb",
        name: "FRED CRUMB",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Sallys/FredCrumb.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "DoughBaughan",
        name: "DOUGH BAUGHAN",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/Sallys/DoughBaughan.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "PipDaltry",
        name: "PIP DALTRY",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "LB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Fiorentina.png",
        image: "assets/characters/Sallys/PipDaltry.png",
        background: "assets/Cartas/Oro.png"
    }
];
