const scoutsPartThreeCards = [
    {
        id: "ConanFox",
        name: "CONAN FOX",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AstonVilla.png",
        image: "assets/characters/Scouts1/ConanFox.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "SpikeCoiffs",
        name: "SPIKE COIFFS",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Newcastle.png",
        image: "assets/characters/Scouts1/SpikeCoiffs.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "RogerRocket",
        name: "ROGER ROCKET",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "RB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Leicester.png",
        image: "assets/characters/Scouts1/RogerRocket.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BillTeller",
        name: "BILL TELLER",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "LB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/LeedsUnited.png",
        image: "assets/characters/Scouts1/BillTeller.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "HarryCaine",
        name: "HARRY CAINE",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "GK",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/CrystalPalace.png",
        image: "assets/characters/Scouts1/HarryCaine.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "MartinSheller",
        name: "MARTIN SHELLER",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sunderland.png",
        image: "assets/characters/Scouts1/MartinSheller.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "CameronMann",
        name: "CAMERON MANN",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Fulham.png",
        image: "assets/characters/Scouts1/CameronMann.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "DonKeys",
        name: "DON KEYS",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/NottinghamFores.png",
        image: "assets/characters/Scouts1/DonKeys.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "FrankDrake",
        name: "FRANK DRAKE",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/WestHam.png",
        image: "assets/characters/Scouts1/FrankDrake.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "ChrisMassey",
        name: "CHRIS MASSEY",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Southampton.png",
        image: "assets/characters/Scouts1/ChrisMassey.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "CarlSacks",
        name: "CARL SACKS",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "ST",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Blackburn.png",
        image: "assets/characters/Scouts1/CarlSacks.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "SonnyEast",
        name: "SONNY EAST",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/Scouts1/SonnyEast.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "DanCarpenter",
        name: "DAN CARPENTER",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/Scouts1/DanCarpenter.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "DougWalker",
        name: "DOUG WALKER",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Scouts1/DougWalker.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BiffBeeston",
        name: "BIFF BEESTON",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/Scouts1/BiffBeeston.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "LouBeigh",
        name: "LOU BEIGH",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/Scouts1/LouBeigh.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "MarvErrick",
        name: "MARV ERRICK",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Osasuna.png",
        image: "assets/characters/Scouts1/MarvErrick.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "BobWhittle",
        name: "BOB WHITTLE",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Racing.png",
        image: "assets/characters/Scouts1/BobWhittle.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BertNeptune",
        name: "BERT NEPTUNE",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/Scouts1/BertNeptune.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "SolCrater",
        name: "SOL CRATER",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/Scouts1/SolCrater.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "PercyColdstair",
        name: "PERCY COLDSTAIR",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Getafe.png",
        image: "assets/characters/Scouts1/PercyColdstair.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "DuskySunfield",
        name: "DUSKY SUNFIELD",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Levante.png",
        image: "assets/characters/Scouts1/DuskySunfield.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "RockyShears",
        name: "ROCKY SHEARS",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/malaga.png",
        image: "assets/characters/Scouts1/RockyShears.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "PercyStent",
        name: "PERCY STENT",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Osasuna.png",
        image: "assets/characters/Scouts1/PercyStent.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ArtPendragon",
        name: "ART PENDRAGON",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Racing.png",
        image: "assets/characters/Scouts1/ArtPendragon.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "DomIttory",
        name: "DOM ITTORY",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Scouts1/DomIttory.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ChazBiggins",
        name: "CHAZ BIGGINS",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Celta.png",
        image: "assets/characters/Scouts1/ChazBiggins.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "SlyOHands",
        name: "SLY O'HANDS",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Depor.png",
        image: "assets/characters/Scouts1/SlyO'Hands.png",
        background: "assets/Cartas/Orobase.png"
    }
];
