const scoutsPartTwoCards = [
    {
        id: "DanRhino",
        name: "DAN RHINO",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Wolfsburg.png",
        image: "assets/characters/Scouts1/DanRhino.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "VinFleetwood",
        name: "VIN FLEETWOOD",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Frankfurt.png",
        image: "assets/characters/Scouts1/VinFleetwood.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "GeorgeWinters",
        name: "GEORGE WINTERS",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Hannover.png",
        image: "assets/characters/Scouts1/GeorgeWinters.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "DenHidden",
        name: "DEN HIDDEN",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/HerthaBSC.png",
        image: "assets/characters/Scouts1/DenHidden.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "ShaunImago",
        name: "SHAUN IMAGO",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Freiburg.png",
        image: "assets/characters/Scouts1/ShaunImago.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "JoeStraiter",
        name: "JOE STRAITER",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Hoffenheim.png",
        image: "assets/characters/Scouts1/JoeStraiter.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "RupertSpiers",
        name: "RUPERT SPIERS",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/UnionBerlin.png",
        image: "assets/characters/Scouts1/RupertSpiers.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "MarkSudor",
        name: "MARK SUDOR",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Augsburg.png",
        image: "assets/characters/Scouts1/MarkSudor.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "RingoStagg",
        name: "RINGO STAGG",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Everton.png",
        image: "assets/characters/Scouts1/RingoStagg.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "JodyMacGough",
        name: "JODY MACGOUGH",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Kaiserslautern.png",
        image: "assets/characters/Scouts1/JodyMacGough.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "JeevesDropper",
        name: "JEEVES DROPPER",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "CM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bochum.png",
        image: "assets/characters/Scouts1/JeevesDropper.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "DanDandy",
        name: "DAN DANDY",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Scouts1/DanDandy.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "RoryBoomer",
        name: "RORY BOOMER",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Scouts1/RoryBoomer.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "TimToppel",
        name: "TIM TOPPEL",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/Scouts1/TimToppel.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "AmesShivers",
        name: "AMES SHIVERS",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sevilla.png",
        image: "assets/characters/Scouts1/AmesShivers.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ChrisGlover",
        name: "CHRIS GLOVER",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "CM",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Brighton.png",
        image: "assets/characters/Scouts1/ChrisGlover.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "ThorToise",
        name: "THOR TOISE",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CDM",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Benfica.png",
        image: "assets/characters/Scouts1/ThorToise.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ColinSalts",
        name: "COLIN SALTS",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "ST",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Scouts1/ColinSalts.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "ChristianDear",
        name: "CHRISTIAN DEAR",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Scouts1/ChristianDear.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "IggyLoyaller",
        name: "IGGY LOYALLER",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/Scouts1/IggyLoyaller.png",
        background: "assets/Cartas/Oro.png"
    }
];
