const scoutsPartFourCards = [
    {
        id: "SeanLavender",
        name: "SEAN LAVENDER",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/WerderBremen.png",
        image: "assets/characters/Scouts1/SeanLavender.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "AceServer",
        name: "ACE SERVER",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Fiorentina.png",
        image: "assets/characters/Scouts1/AceServer.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "HoraceNelson",
        name: "HORACE NELSON",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Scouts1/HoraceNelson.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "PhilipPrince",
        name: "PHILIP PRINCE",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "GK",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Villareal.png",
        image: "assets/characters/Scouts1/PhilipPrince.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "HeathRower",
        name: "HEATH ROWER",
        version: "Oro",
        rarity: "Oro",
        rating: 77,
        position: "CM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealBetis.png",
        image: "assets/characters/Scouts1/HeathRower.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "KimArite",
        name: "KIM ARITE",
        version: "Oro",
        rarity: "Oro",
        rating: 73,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Hamburgo.png",
        image: "assets/characters/Scouts1/KimArite.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "JayArcher",
        name: "JAY ARCHER",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Schalke.png",
        image: "assets/characters/Scouts1/JayArcher.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "BoLing",
        name: "BO LING",
        version: "Oro",
        rarity: "Oro",
        rating: 75,
        position: "CB",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Koeln.png",
        image: "assets/characters/Scouts1/BoLing.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "ChuckHardy",
        name: "CHUCK HARDY",
        version: "Oro",
        rarity: "Oro",
        rating: 74,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Monchengladbach.png",
        image: "assets/characters/Scouts1/ChuckHardy.png",
        background: "assets/Cartas/Orobase.png"
    },
    {
        id: "BenEvolent",
        name: "BEN EVOLENT",
        version: "Oro",
        rarity: "Oro",
        rating: 76,
        position: "ST",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Bochum.png",
        image: "assets/characters/Scouts1/BenEvolent.png",
        background: "assets/Cartas/Oro.png"
    }
];
