const shidouCards = [
    {
        id: "shidou_oro",
        name: "RYUSEI SHIDOU",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/PXG.png",
        image: "assets/characters/Shidou/ShidouOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "shidou_rosa",
        name: "RYUSEI SHIDOU",
        version: "Rosa",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/PXG.png",
        image: "assets/characters/Shidou/Shidou2Sel.png",
        background: "assets/Cartas/Rosa.png"
    },
    {
        id: "shidou_pxg",
        name: "RYUSEI SHIDOU",
        version: "PXG",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/PXG.png",
        image: "assets/characters/Shidou/ShidouPXG.png",
        background: "assets/Cartas/PXG.png"
    },
    {
        id: "shidou_morado",
        name: "RYUSEI SHIDOU",
        version: "Morado",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/PXG.png",
        image: "assets/characters/Shidou/ShidouGol.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "shidou_joker",
        name: "RYUSEI SHIDOU",
        version: "Joker",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/PXG.png",
        image: "assets/characters/Shidou/ShidouDrag.png",
        background: "assets/Cartas/Joker.png"
    },
    {
        id: "shidou_rulebraker",
        name: "RYUSEI SHIDOU",
        version: "Rulebraker",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/PXG.png",
        image: "assets/characters/Shidou/ShidouSub.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "shidou_chicle",
        name: "RYUSEI SHIDOU",
        version: "Chicle",
        rarity: "Especial",
        rating: 93,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/PXG.png",
        image: "assets/characters/Shidou/ShidouPrime.png",
        background: "assets/Cartas/Chicle.png"
    },
    {
        id: "shidou_futurestar",
        name: "RYUSEI SHIDOU",
        version: "FutureStar",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/PXG.png",
        image: "assets/characters/Shidou/ShidouChil.png",
        background: "assets/Cartas/FutureStar.png"
    }
];
