const southCirrusCards = [
    {
        id: "DestinOro",
        name: "DESTIN",
        version: "Oro",
        rarity: "Oro",
        rating: 88,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/DestinOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Destin2",
        name: "DESTIN",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 92,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Destin2.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "Destin1",
        name: "DESTIN",
        version: "Tots",
        rarity: "Especial",
        rating: 94,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Destin1.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "RaikaOro",
        name: "RAIKA",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "LW",
        secondaryPositions: ["LM", "RW", "ST"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/RaikaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Raika",
        name: "RAIKA",
        version: "Chicle",
        rarity: "Especial",
        rating: 87,
        position: "LW",
        secondaryPositions: ["LM", "RW", "ST"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Raika.png",
        background: "assets/Cartas/Chicle.png"
    },
    {
        id: "RaikaPor",
        name: "RAIKA",
        version: "Shapesifters",
        rarity: "Especial",
        rating: 88,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/RaikaPor.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "Raika2",
        name: "RAIKA",
        version: "Rulebreaker",
        rarity: "Especial",
        rating: 90,
        position: "LW",
        secondaryPositions: ["LM", "RW", "ST"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Raika2.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "RaikaPrime",
        name: "RAIKA",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 91,
        position: "LW",
        secondaryPositions: ["LM", "RW", "ST"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/RaikaPrime.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "TierryOro",
        name: "TIERRY",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/TierryOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Tierry",
        name: "TIERRY",
        version: "Centurion",
        rarity: "Especial",
        rating: 88,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Tierry.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "TierryPrime",
        name: "TIERRY",
        version: "Trophy",
        rarity: "Especial",
        rating: 90,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/TierryPrime.png",
        background: "assets/Cartas/Trophy.png"
    }    ,
    {
        id: "AlixOro",
        name: "ALIX LA FONTAINE",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/AlixOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Alix",
        name: "ALIX LA FONTAINE",
        version: "Hielo",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Alix.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "AlixPrime",
        name: "ALIX LA FONTAINE",
        version: "Tots",
        rarity: "Especial",
        rating: 90,
        position: "GK",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/AlixPrime.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "CadeOro",
        name: "CADE SHELBY",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CadeOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Cade",
        name: "CADE SHELBY",
        version: "Azul",
        rarity: "Especial",
        rating: 85,
        position: "CB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Cade.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "CadeMix",
        name: "CADE SHELBY",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CadeMix.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "CedricOro",
        name: "CEDRIC FREUD",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CedricOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "CedricCon",
        name: "CEDRIC FREUD",
        version: "Trophy",
        rarity: "Especial",
        rating: 86,
        position: "CM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CedricCon.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "CedricReg",
        name: "CEDRIC FREUD",
        version: "Azul",
        rarity: "Especial",
        rating: 89,
        position: "CM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CedricReg.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "CedricPrime",
        name: "CEDRIC FREUD",
        version: "Brasil",
        rarity: "Especial",
        rating: 91,
        position: "CM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CedricPrime.png",
        background: "assets/Cartas/Brasil.png"
    },
    {
        id: "bodhifield_oro",
        name: "BODHI FIELD",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Bodhi Field.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "chasewinthrop_oro",
        name: "CHASE WINTHROP",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CAM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Chase Winthrop.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hawkysavard_oro",
        name: "HAWKY SAVARD",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CDM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Hawky Savard.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "taliesingreenhunt_oro",
        name: "TALIESIN GREENHUNT",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Taliesin Greenhunt.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "erdembarath_oro",
        name: "ERDEM BARATH",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Erdem Barath.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "milorankin_oro",
        name: "MILO RANKIN",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Milo Rankin.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "peakefletcher_oro",
        name: "PEAKE FLETCHER",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "RB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Peake Fletcher.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "sentryscarborough_oro",
        name: "SENTRY SCARBOROUGH",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Sentry Scarborough.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "autryrogers_oro",
        name: "AUTRY ROGERS",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Autry Rogers.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hughpronghorn_oro",
        name: "HUGH PRONGHORN",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Hugh Pronghorn.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "denzelharvest_oro",
        name: "DENZEL HARVEST",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Denzel Harvest.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "everettshipman_oro",
        name: "EVERETT SHIPMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CDM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Everett Shipman.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "arminmarshall_oro",
        name: "ARMIN MARSHALL",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Armin Marshall.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "conleyquiver_oro",
        name: "CONLEY QUIVER",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Conley Quiver.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "charisbenzaie_oro",
        name: "CHARIS BENZAIE",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Charis Benzaie.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "charisbenzaie_azul",
        name: "CHARIS BENZAIE",
        version: "Azul",
        rarity: "Especial",
        rating: 82,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Charis Benzaie2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "lycusfoxworth_oro",
        name: "LYCUS FOXWORTH",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Lycus Foxworth.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "lycusfoxworth_azul",
        name: "LYCUS FOXWORTH",
        version: "Azul",
        rarity: "Especial",
        rating: 84,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Lycus Foxworth2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "tairichter_oro",
        name: "TAI RICHTER",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Tai Richter.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "tairichter_azul",
        name: "TAI RICHTER",
        version: "Azul",
        rarity: "Especial",
        rating: 83,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Tai Richter2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "davinbullock_oro",
        name: "DAVIN BULLOCK",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CDM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Davin Bullock.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "davinbullock_azul",
        name: "DAVIN BULLOCK",
        version: "Azul",
        rarity: "Especial",
        rating: 85,
        position: "CDM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Davin Bullock2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "mainealsop_oro",
        name: "MAINE ALSOP",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CAM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Maine Alsop.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "mainealsop_azul",
        name: "MAINE ALSOP",
        version: "Azul",
        rarity: "Especial",
        rating: 81,
        position: "CAM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Maine Alsop2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "dariohighton_oro",
        name: "DARIO HIGHTON",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Dario Highton.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "dariohighton_azul",
        name: "DARIO HIGHTON",
        version: "Azul",
        rarity: "Especial",
        rating: 84,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Dario Highton2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "ameliarainwalker_oro",
        name: "AMELIA RAINWALKER",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Amelia Rainwalker.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ameliarainwalker_azul",
        name: "AMELIA RAINWALKER",
        version: "Azul",
        rarity: "Especial",
        rating: 83,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Amelia Rainwalker2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "winsorcompete_oro",
        name: "WINSOR COMPETE",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Winsor Compete.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "winsorcompete_azul",
        name: "WINSOR COMPETE",
        version: "Azul",
        rarity: "Especial",
        rating: 82,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Winsor Compete2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "marisolcavallo_oro",
        name: "MARISOL CAVALLO",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "RB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Marisol Cavallo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "marisolcavallo_azul",
        name: "MARISOL CAVALLO",
        version: "Azul",
        rarity: "Especial",
        rating: 85,
        position: "RB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Marisol Cavallo2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "meridiaalthoff_oro",
        name: "MERIDIA ALTHOFF",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Meridia Althoff.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "meridiaalthoff_azul",
        name: "MERIDIA ALTHOFF",
        version: "Azul",
        rarity: "Especial",
        rating: 84,
        position: "LB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Meridia Althoff2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "starlathorn_oro",
        name: "STARLA THORN",
        version: "Oro",
        rarity: "Oro",
        rating: 80,
        position: "CAM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Starla Thorn.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "starlathorn_azul",
        name: "STARLA THORN",
        version: "Azul",
        rarity: "Especial",
        rating: 83,
        position: "CAM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Starla Thorn2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "lemmystretchen_oro",
        name: "LEMMY STRETCHEN",
        version: "Oro",
        rarity: "Oro",
        rating: 78,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Lemmy Stretchen.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "lemmystretchen_azul",
        name: "LEMMY STRETCHEN",
        version: "Azul",
        rarity: "Especial",
        rating: 81,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Lemmy Stretchen2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "antoniafelicier_oro",
        name: "ANTONIA FELICIER",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Antonia Felicier.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "antoniafelicier_azul",
        name: "ANTONIA FELICIER",
        version: "Azul",
        rarity: "Especial",
        rating: 85,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Antonia Felicier2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "florentshorleigh_oro",
        name: "FLORENT SHORLEIGH",
        version: "Oro",
        rarity: "Oro",
        rating: 79,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Florent Shorleigh.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "florentshorleigh_azul",
        name: "FLORENT SHORLEIGH",
        version: "Azul",
        rarity: "Especial",
        rating: 82,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Florent Shorleigh2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "kelvinsteelborne_oro",
        name: "KELVIN STEELBORNE",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Kelvin Steelborne.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kelvinsteelborne_azul",
        name: "KELVIN STEELBORNE",
        version: "Azul",
        rarity: "Especial",
        rating: 84,
        position: "CB",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Kelvin Steelborne2.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "nikashimmelstein_oro",
        name: "NIKAS HIMMELSTEIN",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Nikas Himmelstein.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "nikashimmelstein_trophy",
        name: "NIKAS HIMMELSTEIN",
        version: "Trophy",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Nikas Himmelstein2.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "nikashimmelstein_prime",
        name: "NIKAS HIMMELSTEIN",
        version: "Prime",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Nikas HimmelsteinPrime.png",
        background: "assets/Cartas/Naranja.png"
    },
    {
        id: "milorankin_morado",
        name: "MILO RANKIN",
        version: "2",
        rarity: "Especial",
        rating: 86,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Milo Rankin2.png",
        background: "assets/Cartas/Morada.png"
    },
    {
        id: "milorankin_prime",
        name: "MILO RANKIN",
        version: "Prime",
        rarity: "Especial",
        rating: 89,
        position: "GK",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Milo RankinPrime.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "ivanmercer_oro",
        name: "IVAN MERCER",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Ivan Mercer.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "ivanmercer_trophy",
        name: "IVAN MERCER",
        version: "2",
        rarity: "Especial",
        rating: 84,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Ivan Mercer2.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "ivanmercer_prime",
        name: "IVAN MERCER",
        version: "Prime",
        rarity: "Especial",
        rating: 87,
        position: "CM",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Ivan MercerPrime.png",
        background: "assets/Cartas/Naranja.png"
    }
];
