const southCirrusCards = [
    {
        id: "DestinOro",
        name: "DESTIN",
        version: "Oro",
        rarity: "Oro",
        rating: 88,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/DestinOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Destin2",
        name: "DESTIN",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 92,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Destin2.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "Destin1",
        name: "DESTIN",
        version: "Tots",
        rarity: "Especial",
        rating: 94,
        position: "CM",
        secondaryPositions: ["CAM", "CDM"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/SouthCirrus/Destin1.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "RaikaOro",
        name: "RAIKA",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "LW",
        secondaryPositions: ["LM", "RW", "ST"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/RaikaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Raika",
        name: "RAIKA",
        version: "Chicle",
        rarity: "Especial",
        rating: 87,
        position: "LW",
        secondaryPositions: ["LM", "RW", "ST"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Raika.png",
        background: "assets/Cartas/Chicle.png"
    },
    {
        id: "RaikaPor",
        name: "RAIKA",
        version: "Shapesifters",
        rarity: "Especial",
        rating: 88,
        position: "GK",
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/SouthCirrus/RaikaPor.png",
        background: "assets/Cartas/Shapesifters.png"
    },
    {
        id: "Raika2",
        name: "RAIKA",
        version: "Rulebreaker",
        rarity: "Especial",
        rating: 90,
        position: "LW",
        secondaryPositions: ["LM", "RW", "ST"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Raika2.png",
        background: "assets/Cartas/Rulebraker.png"
    },
    {
        id: "RaikaPrime",
        name: "RAIKA",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 91,
        position: "LW",
        secondaryPositions: ["LM", "RW", "ST"],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Lyonn.png",
        image: "assets/characters/SouthCirrus/RaikaPrime.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "TierryOro",
        name: "TIERRY",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/TierryOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Tierry",
        name: "TIERRY",
        version: "Centurion",
        rarity: "Especial",
        rating: 88,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Tierry.png",
        background: "assets/Cartas/Centurion.png"
    },
    {
        id: "TierryPrime",
        name: "TIERRY",
        version: "Trophy",
        rarity: "Especial",
        rating: 90,
        position: "CDM",
        secondaryPositions: ["CM", "CB"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/SouthCirrus/TierryPrime.png",
        background: "assets/Cartas/Trophy.png"
    }    ,
    {
        id: "AlixOro",
        name: "ALIX LA FONTAINE",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/AlixOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Alix",
        name: "ALIX LA FONTAINE",
        version: "Hielo",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Alix.png",
        background: "assets/Cartas/Hielo.png"
    },
    {
        id: "AlixPrime",
        name: "ALIX LA FONTAINE",
        version: "Tots",
        rarity: "Especial",
        rating: 90,
        position: "GK",
        secondaryPositions: [],
        league: "Superliga Europea",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marsella.png",
        image: "assets/characters/SouthCirrus/AlixPrime.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "CadeOro",
        name: "CADE SHELBY",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CadeOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "Cade",
        name: "CADE SHELBY",
        version: "Azul",
        rarity: "Especial",
        rating: 85,
        position: "CB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/Cade.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "CadeMix",
        name: "CADE SHELBY",
        version: "FutBirthday",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        secondaryPositions: [],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/RealSociedad.png",
        image: "assets/characters/SouthCirrus/CadeMix.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "CedricOro",
        name: "CEDRIC FREUD",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CedricOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "CedricCon",
        name: "CEDRIC FREUD",
        version: "Trophy",
        rarity: "Especial",
        rating: 86,
        position: "CM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CedricCon.png",
        background: "assets/Cartas/Trophy.png"
    },
    {
        id: "CedricReg",
        name: "CEDRIC FREUD",
        version: "Azul",
        rarity: "Especial",
        rating: 89,
        position: "CM",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/SouthCirrus.png",
        image: "assets/characters/SouthCirrus/CedricReg.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "CedricPrime",
        name: "CEDRIC FREUD",
        version: "Brasil",
        rarity: "Especial",
        rating: 91,
        position: "CM",
        secondaryPositions: [],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Elche.png",
        image: "assets/characters/SouthCirrus/CedricPrime.png",
        background: "assets/Cartas/Brasil.png"
    }
];
