// database/suecia_cards.js
const sueciaCards = [
    {
        id: "zlatamovic_oro",
        name: "ZLATAMOVIC",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/Inter.png",
        image: "assets/characters/Suecia/Zlatamovic.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hansen_player_oro",
        name: "HANSEN",
        version: "Oro",
        rarity: "Oro",
        rating: 81,
        position: "CB",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Suecia/HansenOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "brolin_oro",
        name: "BROLIN",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Suecia/BrolinOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "brolin_suecia",
        name: "BROLIN",
        version: "Suecia",
        rarity: "Especial",
        rating: 86,
        position: "CB",
        league: "Premier League",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/ManchesterUnited.png",
        image: "assets/characters/Suecia/Brolin.png",
        background: "assets/Cartas/Suecia.png"
    },
    {
        id: "levin_oro",
        name: "LEVIN",
        version: "Oro",
        rarity: "Oro",
        rating: 88,
        position: "CAM",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/Bastard.png",
        image: "assets/characters/Suecia/LevinOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "frederiks_oro",
        name: "FREDERIKS",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CM",
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Suecia/FrederiksOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "frederiks_suecia",
        name: "FREDERIKS",
        version: "Suecia",
        rarity: "Especial",
        rating: 85,
        position: "CM",
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/Porto.png",
        image: "assets/characters/Suecia/Frederiiks.png",
        background: "assets/Cartas/Suecia.png"
    },
    {
        id: "larson_oro",
        name: "LARSON",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Suecia/LarsonOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "larson_suecia",
        name: "LARSON",
        version: "Suecia",
        rarity: "Especial",
        rating: 85,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/se.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Suecia/Larson.webp",
        background: "assets/Cartas/Suecia.png"
    }
    ,{
        id: "hol_brian_oro",
        name: "B. KLUIVOORT",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CAM",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/BrianKluivoortOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "stijn_oro",
        name: "S. KLUIVOORT",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CDM",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/StijnKluivoortOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "overus_oro",
        name: "OVERUS",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "CB",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Holanda/OverusOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "lensenblink_oro",
        name: "LENSENBLINK",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "CM",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/LensenblinkOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "doleman_oro",
        name: "DOLEMAN",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/DolemanOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "kaiser_oro_tsubasa",
        name: "KAISER",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/KaiserOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "davi_oro",
        name: "DAVI",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CDM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ubers.png",
        image: "assets/characters/Holanda/DaviOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "luikal_oro",
        name: "LUIKAL",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Holanda/LuikalOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "dick_oro",
        name: "DICK",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CB",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/DickOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "klismann_oro",
        name: "KLISMANN",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "ST",
        league: "Eredivisie",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Ajax.png",
        image: "assets/characters/Holanda/KlismannOro.png",
        background: "assets/Cartas/Oro.png"
    }

];

// ==========================================
// AMOROS
// ==========================================
