// database/tecmo_cards.js
const tecmoCards = [
    {
        id: "savicevic_oro",
        name: "SAVICEVIC",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/rs.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/Tecmo/SavicevicOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "savicevic_flashback",
        name: "SAVICEVIC",
        version: "Flashback",
        rarity: "Especial",
        rating: 87,
        position: "GK",
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/rs.png",
        teamIcon: "teams/Leverkusen.png",
        image: "assets/characters/Tecmo/Savicevic.png",
        background: "assets/Cartas/Flashback.png"
    },
    {
        id: "zagallo_oro",
        name: "ZAGALLO",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "ST",
        league: "Ligue 1",
        nationFlag: "https://flagcdn.com/w40/br.png",
        teamIcon: "teams/Monaco.png",
        image: "assets/characters/Tecmo/Zagallo.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "coimbra_oro",
        name: "COIMBRA",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "CF",
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/br.png",
        teamIcon: "teams/Benfica.png",
        image: "assets/characters/Tecmo/CoimbraOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "coimbra_brasil",
        name: "COIMBRA",
        version: "Brasil",
        rarity: "Especial",
        rating: 90,
        position: "CF",
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/br.png",
        teamIcon: "teams/Benfica.png",
        image: "assets/characters/Tecmo/Coimbra.png",
        background: "assets/Cartas/Brasil.png"
    },
    {
        id: "nascimento_oro",
        name: "NASCIMENTO",
        version: "Oro",
        rarity: "Oro",
        rating: 82,
        position: "ST",
        league: "Primeira Liga",
        name: "DIRCEU",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/br.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Tecmo/DirceuOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "dirceu_milan",
        name: "DIRCEU",
        version: "Milan",
        rarity: "Especial",
        rating: 88,
        position: "CB",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/br.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Tecmo/Dirceu.png",
        background: "assets/Cartas/Milan.png"
    },
    {
        id: "elzogertise_oro",
        name: "ELZO GERTISE",
        version: "Oro",
        rarity: "Oro",
        rating: 83,
        position: "GK",
        league: "Primeira Liga",
        nationFlag: "https://flagcdn.com/w40/br.png",
        teamIcon: "teams/Sporting.png",
        image: "assets/characters/Tecmo/ElzoGertise.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "gulia_oro",
        name: "GULIA",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "CM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/nl.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Tecmo/Gulia.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "signori_oro",
        name: "SIGNORI",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "CAM",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/br.png",
        teamIcon: "teams/Parma.png",
        image: "assets/characters/Tecmo/Signori.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "alcion_oro",
        name: "ALCION",
        version: "Oro",
        rarity: "Oro",
        rating: 86,
        position: "CM",
        secondaryPositions: ["ST"],
        league: "Bundesliga",
        nationFlag: "https://flagcdn.com/w40/rs.png",
        teamIcon: "teams/Stuttgart.png",
        image: "assets/characters/Tecmo/Alcion.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "stratto_oro",
        name: "STRATTO",
        version: "Oro",
        rarity: "Oro",
        rating: 87,
        position: "ST",
        league: "Serie A",
        nationFlag: "https://flagcdn.com/w40/it.png",
        teamIcon: "teams/Milan.png",
        image: "assets/characters/Tecmo/Stratto.png",
        background: "assets/Cartas/Oro.png"
    }
];
