// database/tsubasa_cards.js
const tsubasaCards = [

    {
        id: "ina_xene_oro",
        name: "XENE",
        version: "Genesis",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Xavier/Xene.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "xene",
        name: "XENE",
        version: "Básico",
        rarity: "Oro",
        rating: 81,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/AcademiaAlia.png",
        image: "assets/characters/Xavier/XeneOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "tsu_rising_new",
        name: "TSUBASA",
        version: "Rising",
        rarity: "Especial",
        rating: 91,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Tsubasa/TsubasaRising.png",
        background: "assets/Cartas/FutBirthday.png"
    },
    {
        id: "tsu_wy",
        name: "TSUBASA",
        version: "World Youth",
        rarity: "Especial",
        rating: 90,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Tsubasa/TsubasaWY.png",
        background: "assets/Cartas/Azul.png"
    },
        {
        id: "tsu_nankatsu",
        name: "TSUBASA",
        version: "Nankatsu",
        rarity: "Especial",
        rating: 89,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Tsubasa/TsubasaNankatsu.png",
        background: "assets/Cartas/Flashback.png"
    },
    {
        id: "tsubasa_oro",
        name: "TSUBASA",
        version: "Oro",
        rarity: "Oro",
        rating: 89,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Tsubasa/TsubasaOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "tsu_risingsun",
        name: "TSUBASA",
        version: "Rising Sun",
        rarity: "Especial",
        rating: 92,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Tsubasa/TsubasaRisingSun.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "tsu_barcha",
        name: "TSUBASA",
        version: "Barcha",
        rarity: "Especial",
        rating: 93,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Barcha.png", 
        image: "assets/characters/Tsubasa/TsubasaBarcha.png",
        background: "assets/Cartas/Barcha.png"
    },
    {
        id: "tsu_mundial26",
        name: "TSUBASA",
        version: "Mundial 2026",
        rarity: "Especial",
        rating: 95,
        position: "CAM",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Barcha.png",
        image: "assets/characters/Tsubasa/TsubasaMundial26.png",
        background: "assets/backgrounds/Fondo_TsubasaMundial.jpg"
    },
    {
        id: "hurley_oro",
        name: "HURLEY KANE",
        version: "Oro",
        rarity: "Oro",
        rating: 85,
        position: "LB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/Hurley/HurleyOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hurley_if",
        name: "HURLEY KANE",
        version: "If",
        rarity: "Especial",
        rating: 87,
        position: "LB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/Hurley/Hurley.png",
        background: "assets/Cartas/If.png"
    },
    {
        id: "hurley_sam",
        name: "HURLEY KANE",
        version: "Samurai",
        rarity: "Especial",
        rating: 89,
        position: "LB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/Hurley/HurleySam.png",
        background: "assets/Cartas/Azul.png"
    },
    {
        id: "hurley_tots",
        name: "HURLEY KANE",
        version: "Tots",
        rarity: "Especial",
        rating: 91,
        position: "LB",
        secondaryPositions: [],
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Marea-Pirata.png",
        image: "assets/characters/Hurley/HurleyJP.png",
        background: "assets/Cartas/Tots.png"
    },
    {
        id: "hurley_leg_oro",
        name: "HURLEY KANE",
        version: "Leyenda Oro",
        rarity: "Oro",
        rating: 89,
        position: "LB",
        secondaryPositions: [],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Hurley/HurleyLegOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "hurley_leg",
        name: "HURLEY KANE",
        version: "Icono",
        rarity: "Icono",
        rating: 93,
        position: "LB",
        secondaryPositions: [],
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Valencia.png",
        image: "assets/characters/Hurley/HurleyLeg.png",
        background: "assets/Cartas/Icono.png"
    }
];
