const victorCards = [
    {
        id: "VictorOro",
        name: "VICTOR",
        version: "Oro",
        rarity: "Oro",
        rating: 84,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Victor/VictorOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "VictorMixOro",
        name: "VICTOR",
        version: "MixOro",
        rarity: "Oro",
        rating: 86,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/Victor/VictorMixOro.png",
        background: "assets/Cartas/Oro.png"
    },
    {
        id: "VictorChute",
        name: "VICTOR",
        version: "Chute",
        rarity: "Especial",
        rating: 87,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Victor/VictorChute.png",
        background: "assets/Cartas/Raimon.png"
    },
    {
        id: "VictorArmor",
        name: "VICTOR",
        version: "Armor",
        rarity: "Especial",
        rating: 88,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/Victor/VictorArmor.png",
        background: "assets/Cartas/Morado.png"
    },
    {
        id: "Victor1",
        name: "VICTOR",
        version: "1",
        rarity: "Especial",
        rating: 89,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Victor/Victor1.png",
        background: "assets/Cartas/RojiAzul.png"
    },
    {
        id: "VictorArmadura",
        name: "VICTOR",
        version: "Armadura",
        rarity: "Especial",
        rating: 90,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/Victor/VictorArmadura.png",
        background: "assets/Cartas/Roja.png"
    },
    {
        id: "VictorArmor2",
        name: "VICTOR",
        version: "Armor2",
        rarity: "Especial",
        rating: 91,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Victor/VictorArmor2.png",
        background: "assets/Cartas/SBC.png"
    },
    {
        id: "VictorGalaxy",
        name: "VICTOR",
        version: "Galaxy",
        rarity: "Especial",
        rating: 92,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/Victor/VictorGalaxy.png",
        background: "assets/Cartas/EEUU.png"
    },
    {
        id: "VictorTotem",
        name: "VICTOR",
        version: "Totem",
        rarity: "Especial",
        rating: 93,
        position: "ST",
        league: "J-League",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Raimon.png",
        image: "assets/characters/Victor/VictorTotem.png",
        background: "assets/Cartas/FutureStar.png"
    },
    {
        id: "VictorGuapo",
        name: "VICTOR",
        version: "Guapo",
        rarity: "Especial",
        rating: 94,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/Victor/VictorGuapo.png",
        background: "assets/Cartas/Trailblaze.png"
    },
    {
        id: "VictorChrono",
        name: "VICTOR",
        version: "Chrono",
        rarity: "Especial",
        rating: 95,
        position: "ST",
        league: "La Liga",
        nationFlag: "https://flagcdn.com/w40/jp.png",
        teamIcon: "teams/Espanol.png",
        image: "assets/characters/Victor/VictorChrono.png",
        background: "assets/Cartas/Tots.png"
    }
];
