// database/zeus_cards.js
const zeusCards = [
    { id: "andy_chronic_oro", name: "ANDY CHRONIC", version: "Oro", rarity: "Oro", rating: 80, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/AndyChronic.png", background: "assets/Cartas/Oro.png" },
    { id: "apollo_light_oro", name: "APOLLO LIGHT", version: "Oro", rarity: "Oro", rating: 82, position: "LB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ApolloLight.png", background: "assets/Cartas/Oro.png" },
    
    { id: "arion_matlock_oro", name: "ARION MATLOCK", version: "Oro", rarity: "Oro", rating: 83, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ArionMatlockOro.png", background: "assets/Cartas/Oro.png" },
    { id: "arion_matlock_trophy", name: "ARION MATLOCK", version: "Trophy", rarity: "Especial", rating: 86, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ArionMatlock.png", background: "assets/Cartas/Trophy.png" },
    
    { id: "artie_mishman_oro", name: "ARTIE MISHMAN", version: "Oro", rarity: "Oro", rating: 83, position: "LW", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ArtieMishman.png", background: "assets/Cartas/Oro.png" },
    
    { id: "danny_wood_oro", name: "DANNY WOOD", version: "Oro", rarity: "Oro", rating: 83, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/DannyWoodOro.png", background: "assets/Cartas/Oro.png" },
    { id: "danny_wood_trophy", name: "DANNY WOOD", version: "Trophy", rarity: "Especial", rating: 86, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/DannyWood.png", background: "assets/Cartas/Trophy.png" },
    
    { id: "gus_heeley_oro", name: "GUS HEELEY", version: "Oro", rarity: "Oro", rating: 80, position: "ST", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/GusHeeley.png", background: "assets/Cartas/Oro.png" },
    { id: "harry_closs_oro", name: "HARRY CLOSS", version: "Oro", rarity: "Oro", rating: 80, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/HarryCloss.png", background: "assets/Cartas/Oro.png" },
    
    { id: "henry_house_oro", name: "HENRY HOUSE", version: "Oro", rarity: "Oro", rating: 84, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/HenryHouseOro.png", background: "assets/Cartas/Oro.png" },
    { id: "henry_house_trophy", name: "HENRY HOUSE", version: "Trophy", rarity: "Especial", rating: 87, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/HenryHouse.png", background: "assets/Cartas/Trophy.png" },
    
    { id: "iggy_russ_oro", name: "IGGY RUSS", version: "Oro", rarity: "Oro", rating: 80, position: "GK", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/IggyRuss.png", background: "assets/Cartas/Oro.png" },
    { id: "jeff_iron_oro", name: "JEFF IRON", version: "Oro", rarity: "Oro", rating: 81, position: "RB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/JeffIron.png", background: "assets/Cartas/Oro.png" },
    
    { id: "jonas_demetrius_oro", name: "JONAS DEMETRIUS", version: "Oro", rarity: "Oro", rating: 85, position: "ST", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/JonasDemetriusOro.png", background: "assets/Cartas/Oro.png" },
    { id: "jonas_demetrius_trophy", name: "JONAS DEMETRIUS", version: "Trophy", rarity: "Especial", rating: 88, position: "ST", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/JonasDemetrius.png", background: "assets/Cartas/Trophy.png" },
    
    { id: "lane_war_oro", name: "LANE WAR", version: "Oro", rarity: "Oro", rating: 82, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/LaneWarOro.png", background: "assets/Cartas/Oro.png" },
    { id: "lane_war_trophy", name: "LANE WAR", version: "Trophy", rarity: "Especial", rating: 85, position: "CB", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/LaneWar.png", background: "assets/Cartas/Trophy.png" },
    
    { id: "ned_yousef_oro", name: "NED YOUSEF", version: "Oro", rarity: "Oro", rating: 80, position: "CM", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/NedYousef.png", background: "assets/Cartas/Oro.png" },
    
    { id: "paul_siddon_oro", name: "PAUL SIDDON", version: "Oro", rarity: "Oro", rating: 85, position: "GK", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/PaulSiddonOro.png", background: "assets/Cartas/Oro.png" },
    { id: "paul_siddon_trophy", name: "PAUL SIDDON", version: "Trophy", rarity: "Especial", rating: 88, position: "GK", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/PaulSiddon.png", background: "assets/Cartas/Trophy.png" },
    
    { id: "wesley_knox_oro", name: "WESLEY KNOX", version: "Oro", rarity: "Oro", rating: 82, position: "RW", league: "J-League", nationFlag: "https://flagcdn.com/w40/jp.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/WesleyKnox.png", background: "assets/Cartas/Oro.png" },

    { id: "byron_love_oro", name: "BYRON LOVE", version: "Oro", rarity: "Oro", rating: 87, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ByronLoveOro.png", background: "assets/Cartas/Oro.png" },
    { id: "byron_love_oroares", name: "BYRON LOVE", version: "Oro", rarity: "Oro", rating: 86, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLoveOroAres.png", background: "assets/Cartas/Oro.png" },
    { id: "byron_love_trophy", name: "BYRON LOVE", version: "Trophy", rarity: "Especial", rating: 89, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ByronLove.png", background: "assets/Cartas/Trophy.png" },
    { id: "byron_love_alas", name: "BYRON LOVE", version: "Cabras", rarity: "Especial", rating: 90, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ByronLoveAlas.png", background: "assets/Cartas/Cabras.png" },
    { id: "byron_love_ares", name: "BYRON LOVE", version: "Ubers", rarity: "Especial", rating: 88, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLoveAres.png", background: "assets/Cartas/Ubers.png" },
    { id: "byron_love_ar", name: "BYRON LOVE", version: "FutBirthday", rarity: "Especial", rating: 89, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLoveAr.png", background: "assets/Cartas/FutBirthday.png" },
    { id: "byron_love_plumas", name: "BYRON LOVE", version: "EEUU", rarity: "Especial", rating: 91, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ByronLovePlumas.png", background: "assets/Cartas/EEUU.png" },
    { id: "byron_love_rai", name: "BYRON LOVE", version: "Raimon", rarity: "Especial", rating: 92, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Raimon.png", image: "assets/characters/Zeus/ByronLoveRai.png", background: "assets/Cartas/Raimon.png" },
    { id: "byron_love_corea", name: "BYRON LOVE", version: "Roja", rarity: "Especial", rating: 93, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ByronLoveCorea.png", background: "assets/Cartas/Roja.png" },
    { id: "byron_love_cor", name: "BYRON LOVE", version: "Trailblaze", rarity: "Especial", rating: 95, position: "CAM", league: "J-League", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Zeus.png", image: "assets/characters/Zeus/ByronLoveCor.png", background: "assets/Cartas/Trailblaze.png" },
    { id: "byron_love_cross", name: "BYRON LOVE", version: "SBC", rarity: "Especial", rating: 92, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLoveCross.png", background: "assets/Cartas/SBC.png" },
    { id: "byron_love_chut", name: "BYRON LOVE", version: "Centurion", rarity: "Especial", rating: 90, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLoveChut.png", background: "assets/Cartas/Centurion.png" },
    { id: "byron_love_gran", name: "BYRON LOVE", version: "Trueno", rarity: "Especial", rating: 91, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLoveGran.png", background: "assets/Cartas/Trueno.png" },
    { id: "byron_love_hora", name: "BYRON LOVE", version: "Tots", rarity: "Especial", rating: 92, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLoveHora.png", background: "assets/Cartas/Tots.png" },
    { id: "byron_love_orion", name: "BYRON LOVE", version: "Toty", rarity: "Especial", rating: 94, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLoveOrion.png", background: "assets/Cartas/Toty.png" },
    { id: "byron_love_prime", name: "BYRON LOVE", version: "Icono", rarity: "Icono", rating: 96, position: "CAM", league: "Serie A", nationFlag: "https://flagcdn.com/w40/kr.png", teamIcon: "teams/Ubers.png", image: "assets/characters/Zeus/ByronLovePrime.png", background: "assets/Cartas/Icono.png" }
];
